CodeSystem: CodeSystemSpecimenContainerTypeMyCore
Id: specimen-container-type-my-core
Title: "CodeSystemSpecimenContainerType (MY Core)"
Description: "Malaysia specimen container type"
* ^language = #en
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel"
* ^extension.valueCode = #executable
* ^url = "https://standards.moh.gov.my/fhir/my-core/CodeSystem/specimen-container-type-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^publisher = "Malaysia MOH - HIE Steering Committee"
* ^contact.name = "Saifuldaulah Bin Mohd Hafiz Ngoo"
* ^contact.telecom.system = #email
* ^contact.telecom.value = "saifuldaulah@mhn.asia"
* ^caseSensitive = true
* ^content = #complete
* ^property[0].code = #definition
* ^property[=].description = "Definition"
* ^property[=].type = #string
* ^property[+].code = #display
* ^property[=].uri = "http://terminology.hl7.org/CodeSystem/designation-usage|display"
* ^property[=].description = "Display"
* ^property[=].type = #string
* #001 "Plain tube" "Tube containing no additive; blood clots and serum is separated after centrifugation."
* #002 "Urine container" "Container for a single voided urine specimen."
* #003 "24hr urine bottle with 10mL 25% HCl" "Bottle for a 24-hour urine collection, pre-charged with 10 mL of 25% hydrochloric acid as preservative."
* #004 "Whatmann 903 Filter Paper" "Whatman 903 protein saver filter paper for dried blood spot collection."
* #005 "EDTA tube" "Tube containing EDTA anticoagulant, which chelates calcium to prevent clotting."
* #006 "Pre-chilled EDTA" "EDTA tube chilled before collection, for analytes that degrade at ambient temperature."
* #007 "Falcon tube" "Conical centrifuge tube used for larger-volume fluid and tissue specimens."
* #008 "Sodium Fluoride tube" "Tube containing sodium fluoride, which inhibits glycolysis and preserves glucose concentration."
* #009 "Lithium Heparin tube" "Tube containing lithium heparin anticoagulant, for plasma and whole blood chemistry."
* #010 "K2 EDTA tube" "Tube containing dipotassium EDTA anticoagulant."
* #011 "Clean tube" "Container that is clean but not sterile, for specimens where sterility is not required."
* #012 "Heparinised syringe" "Syringe pre-coated with heparin, used for arterial blood gas collection."
* #013 "24hr urine bottle" "Bottle for a 24-hour urine collection with no preservative."
* #014 "EDTA tube / Heparin tube" "Either an EDTA tube or a heparin tube is acceptable for this test."
* #015 "Plain tube & Urine container" "Requires both a plain tube and a urine container."
* #016 "Potassium Oxalate + Sodium Fluoride tube" "Tube containing potassium oxalate with sodium fluoride; oxalate anticoagulates and fluoride preserves glucose."
* #017 "Plain tube / EDTA tube" "Either a plain tube or an EDTA tube is acceptable for this test."
* #018 "Sodium Fluoride tube tube" "Tube containing sodium fluoride."
* #019 "Urine container & EDTA tube" "Requires both a urine container and an EDTA tube."
* #020 "24hr urine bottle 0.2g Sodium Bicarbonate" "Bottle for a 24-hour urine collection, pre-charged with 0.2 g sodium bicarbonate as preservative."
* #021 "Heparin tube" "Tube containing heparin anticoagulant."
* #022 "Special microtube with EDTA & DTE" "Microtube containing EDTA and dithioerythritol, for analytes requiring a reducing agent."
* #023 "Tissue cassette" "Cassette holding tissue through processing, embedding and sectioning."
* #024 "Fixed thin smear prepared on glass slide or sterile container" "Fixed thin smear on a glass slide, or a sterile container."
* #025 "Sterile container" "Container sterilised before use, for specimens intended for culture."
* #027 "Fixed thin smear prepared on glass slide" "Thin smear fixed on a glass slide before transport."
* #028 "Capped container" "Container with a secure cap, not necessarily sterile."
* #030 "Supplied vial with fixative" "Vial supplied pre-charged with fixative appropriate to the specimen."
* #031 "3.2% trisodium citrate" "Tube containing 3.2% trisodium citrate anticoagulant, used for coagulation testing."
* #032 "Lithium Heparin tube" "Tube containing lithium heparin anticoagulant."
* #033 "Direct Smear" "Specimen applied directly to a slide without fixation or staining before transport."
* #034 "Sodium Heparin tube" "Tube containing sodium heparin anticoagulant."
* #035 "Microtainer K2EDTA tube" "Paediatric microtainer containing dipotassium EDTA, for small-volume capillary collection."
* #036 "EDTA tube MAP (pediatric infectious sample)" "EDTA tube with molecular transport medium, for paediatric infectious disease specimens."
* #037 "Filter paper" "Absorbent paper onto which blood or fluid is applied and dried."
* #038 "Fresh finger prick" "Capillary blood obtained by finger prick and tested without transfer to a container."
* #039 "NA Slant/ Culture plate" "Nutrient agar slant or culture plate inoculated at the point of collection."
* #040 "Sterile container / Falcon tube" "Either a sterile container or a Falcon tube is acceptable."
* #041 "Myco F Lytic blood bottle" "BACTEC Myco/F Lytic bottle for culture of mycobacteria and fungi from blood."
* #042 "Aerobic blood bottle" "Blood culture bottle supporting growth of aerobic organisms."
* #043 "Anaerobic blood bottle" "Blood culture bottle supporting growth of anaerobic organisms."
* #044 "Pediatric blood bottle" "Blood culture bottle with reduced fill volume, for paediatric collection."
* #045 "Thick film" "Thick blood film for detection of blood-borne parasites."
* #046 "Thin film" "Thin blood film for species identification of blood-borne parasites."
* #047 "Charcoal/ Stuart transport medium" "Charcoal or Stuart medium maintaining organism viability without multiplication during transport."
* #048 "Attest" "Biological indicator used to verify sterilisation cycle efficacy."
* #049 "Plain sterile swab" "Sterile swab without transport medium."
* #050 "Myco F Lytic BACTEC bottle" "BACTEC Myco/F Lytic bottle."
* #051 "Instrument in wrapping/ actual pack" "Instrument submitted in its sterilisation wrapping or pack for sterility monitoring."
* #052 "Stuart transport medium" "Stuart transport medium maintaining organism viability during transport."
* #053 "Thioglycolate transport medium" "Thioglycolate medium supporting recovery of anaerobic organisms during transport."
* #054 "Sterile container / boric acid" "Sterile container containing boric acid, which preserves urine for culture by inhibiting bacterial multiplication."
* #055 "Sterile container contains VTM" "Sterile container pre-charged with viral transport medium."
* #056 "Viral Transport Medium" "Medium maintaining viral viability during transport to the laboratory."
* #057 "Plain tube / EDTA tube / Lithium Heparin tube" "Any of a plain tube, an EDTA tube or a lithium heparin tube is acceptable."
* #26 "Smear" "Material spread onto a slide for microscopic examination."
