CodeSystem: CodeSystemLabMethodMyCore
Id: lab-method-my-core
Title: "CodeSystemLabMethod (MY Core)"
Description: "Malaysia Lab method"
* ^language = #en
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel"
* ^extension.valueCode = #executable
* ^url = "https://standards.moh.gov.my/fhir/my-core/CodeSystem/lab-method-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^publisher = "Malaysia MOH - HIE Steering Committee"
* ^contact.name = "Saifuldaulah Bin Mohd Hafiz Ngoo"
* ^contact.telecom.system = #email
* ^contact.telecom.value = "saifuldaulah@mhn.asia"
* ^caseSensitive = true
* ^content = #complete
* ^property[0].code = #definition
* ^property[=].description = "Definition"
* ^property[=].type = #string
* ^property[+].code = #display
* ^property[=].uri = "http://terminology.hl7.org/CodeSystem/designation-usage|display"
* ^property[=].description = "Display"
* ^property[=].type = #string
* ^valueSet = "https://standards.moh.gov.my/fhir/my-core/ValueSet/lab-method-my-core"
* #00 "No Information" "Placeholder used when the examination method was not recorded at the source system. Not a method."
* #01 "Immune Stain" "Immunohistochemical stain using labelled antibodies to demonstrate a specific antigen in tissue."
* #02 "Other stain" "Any special stain not separately enumerated in this code system."
* #03 "Masson Trichrome" "Trichrome stain differentiating collagen from muscle and cytoplasm; used to assess fibrosis."
* #04 "Alcian Blue PAS" "Combined Alcian blue and periodic acid-Schiff stain distinguishing acidic from neutral mucins."
* #05 "PAS" "Periodic acid-Schiff stain demonstrating glycogen, neutral mucins, basement membrane and fungal cell walls."
* #06 "PAS+D" "Periodic acid-Schiff stain with diastase digestion, distinguishing glycogen from other PAS-positive material."
* #07 "Mucincarmine" "Mucicarmine stain demonstrating epithelial mucin; also stains the capsule of Cryptococcus."
* #08 "AFB" "Acid-fast bacilli stain demonstrating mycobacteria, which retain carbol fuchsin after acid-alcohol decolourisation."
* #09 "Wade Fite" "Modified acid-fast stain for weakly acid-fast organisms, principally Mycobacterium leprae."
* #10 "Giemsa" "Romanowsky stain used for blood films, bone marrow and haemoparasites."
* #11 "Gram Stain" "Differential stain separating Gram-positive from Gram-negative bacteria by cell wall retention of crystal violet."
* #12 "Luxol Fast Blue" "Stain demonstrating myelin in central nervous system tissue."
* #13 "Methanamine" "Methenamine silver stain demonstrating fungal cell walls and basement membrane."
* #14 "Van Gieson" "Stain differentiating collagen from muscle and fibrin."
* #15 "Verhoeff-Van Gieson" "Elastic stain combining Verhoeff elastin with Van Gieson counterstain; used to assess vessel wall elastic laminae."
* #16 "Reticulin" "Silver impregnation stain demonstrating reticulin fibres; used to assess marrow fibrosis and tissue architecture."
* #17 "Von Kossa stain" "Silver stain demonstrating calcium deposits in tissue."
* #18 "Fouchet stain" "Stain demonstrating bile pigment in tissue."
* #19 "Congo red stain" "Stain demonstrating amyloid, which shows apple-green birefringence under polarised light."
* #20 "Oil red O stain" "Lipid stain performed on frozen sections; demonstrates neutral fat."
* #21 "Masson Fontana" "Silver stain demonstrating melanin and argentaffin granules."
* #22 "Rhodamine stain" "Fluorescent acid-fast stain for mycobacteria, read under fluorescence microscopy."
* #23 "Bielschowsky stain" "Silver impregnation stain demonstrating axons and neurofibrillary structures."
* #24 "PTAH" "Phosphotungstic acid haematoxylin stain demonstrating glial fibres, muscle striations and fibrin."
* #25 "Grimelius" "Silver stain demonstrating argyrophilic neuroendocrine granules."
* #26 "Touludine Blue" "Metachromatic stain demonstrating mast cell granules, cartilage matrix and mucins."
* #27 "Alcian Blue" "Stain demonstrating acidic mucins and mucosubstances."
* #28 "Melanin Bleach" "Bleaching procedure removing melanin pigment so underlying tissue detail can be assessed."
* #29 "Sudan IV" "Lipid stain performed on frozen sections."
* #30 "Crystal Violet" "Stain used to demonstrate amyloid and certain bacteria."
* #31 "Molgen" "Molecular genetics technique, not otherwise specified."
* #32 "FISH" "Fluorescence in situ hybridisation using labelled probes to detect specific nucleic acid sequences in situ."
* #33 "Wet preparation" "Unstained microscopic examination of a specimen suspended in fluid."
* #34 "Gram stain" "Differential stain separating Gram-positive from Gram-negative bacteria."
* #35 "Manual" "Manual technique performed without automated instrumentation."
* #36 "Latex agglutination" "Agglutination of antibody-coated latex particles by a target antigen."
* #37 "Rapid ICT" "Rapid immunochromatographic lateral flow test giving a qualitative result at the point of testing."
* #38 "Culture" "Growth of organisms on or in a culture medium for isolation and identification."
* #39 "Agar diffusion" "Antimicrobial susceptibility testing by diffusion of antibiotic from a disc into inoculated agar."
* #40 "Gradient strip" "Antimicrobial susceptibility testing using a strip carrying a predefined antibiotic concentration gradient."
* #41 "MIC" "Determination of the minimum inhibitory concentration of an antimicrobial agent."
* #42 "Gradient strip ARD" "Gradient strip method used to detect antimicrobial resistance determinants."
* #43 "PCR" "Polymerase chain reaction amplifying a target nucleic acid sequence."
* #44 "Probe.amp.tar" "Target amplification by nucleic acid probe."
* #45 "Molecular" "Molecular technique, not otherwise specified."
* #46 "Latex agglutination" "Agglutination of antibody-coated latex particles by a target antigen."
* #47 "ZN Stain" "Ziehl-Neelsen acid-fast stain for mycobacteria."
* #48 "IF Stain" "Immunofluorescence stain using fluorochrome-labelled antibody."
* #49 "Modified ZN" "Modified Ziehl-Neelsen stain for weakly acid-fast organisms including Nocardia and coccidian parasites."
* #50 "IF" "Immunofluorescence technique."
* #51 "IA" "Immunoassay, not otherwise specified."
* #52 "ICT(Immunochromatographic)" "Immunochromatographic lateral flow assay."
* #53 "Floculation" "Antigen-antibody reaction producing visible flocculation."
* #54 "Agglutination" "Antigen-antibody reaction producing visible clumping, reported qualitatively."
* #55 "Agglutination (titre)" "Agglutination reaction reported as an endpoint titre."
* #56 "Not Mention" "Placeholder used when the source system did not state the method."
* #57 "Not mention (titre)" "Placeholder used when the method was not stated but a titre was reported."
* #58 "IIP" "Indirect immunoperoxidase technique."
* #59 "KOH preparation" "Potassium hydroxide preparation clearing keratin to reveal fungal elements."
* #60 "India ink preparation" "Negative staining preparation demonstrating the capsule of Cryptococcus in cerebrospinal fluid."
* #61 "LPCB stain" "Lactophenol cotton blue stain demonstrating fungal morphology."
* #62 "wet preparation" "Unstained microscopic examination of a specimen suspended in fluid."
* #63 "Environmental culture" "Culture of a specimen taken from the care environment rather than from a patient."
* #64 "Colorzyme" "Colorimetric enzyme-based detection method."
* #65 "Elisa" "Enzyme-linked immunosorbent assay."
* #66 "ICT" "Immunochromatographic test."
* #67 "EIA/ICT" "Enzyme immunoassay or immunochromatographic test, method not further specified."
* #68 "Immunoblot" "Detection of antigen or antibody by transfer to a membrane followed by immunological detection."
* #69 "FEI" "Fluorescent enzyme immunoassay."
* #70 "IB" "Immunoblot technique."
* #71 "Flow cytometry" "Analysis of cell populations by laser interrogation of individually suspended labelled cells."
* #72 "RAST" "Radioallergosorbent test measuring allergen-specific IgE."
* #73 "LA" "Latex agglutination."
* #74 "Nephelometry" "Measurement of analyte concentration by light scattered from an antigen-antibody complex."
* #75 "FC" "Flow cytometry."
* #76 "EM" "Electron microscopy."
* #77 "IA rapid" "Rapid immunoassay giving a result at the point of testing."
* #78 "IFAT" "Indirect fluorescent antibody test."
* #79 "Western blot" "Immunoblot separating proteins by electrophoresis before membrane transfer and immunological detection."
* #80 "sequencing" "Determination of the nucleotide order of a nucleic acid target."
* #81 "RT-PCR" "Reverse transcription polymerase chain reaction amplifying an RNA target via complementary DNA."
* #82 "Probe.amp.tar" "Target amplification by nucleic acid probe."
* #83 "Serology" "Detection of antibody or antigen in serum."
* #84 "Isolation" "Recovery of an organism in pure culture from a clinical specimen."
* #85 "Giemsa stain" "Romanowsky stain used for blood films, bone marrow and haemoparasites."
* #86 "DMSO stain/Gram chromotrope stain" "Modified trichrome stain demonstrating microsporidial spores in faecal and tissue specimens."
* #87 "Wet Mount" "Unstained microscopic examination of a specimen under a coverslip."
* #88 "Direct smear" "Microscopic examination of material applied directly to a slide without culture or concentration."
* #89 "Fecal concentration" "Concentration of a faecal specimen to increase recovery of ova, cysts and parasites."
* #90 "Trichrome stain" "Trichrome stain demonstrating intestinal protozoa in faecal specimens."
* #91 "Multiplex PCR" "Polymerase chain reaction amplifying several targets in a single reaction."
* #92 "Seminested PCR" "Two-stage polymerase chain reaction in which the second reaction shares one primer with the first."
