CodeSystem: CodeSystemSpecialtyMyCore
Id: specialty-my-core
Title: "CodeSystemSpecialty (MY Core)"
Description: "Specialty My Core"
* ^language = #en
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel"
* ^extension.valueCode = #executable
* ^url = "https://standards.moh.gov.my/fhir/my-core/CodeSystem/specialty-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^publisher = "Malaysia MOH - HIE Steering Committee"
* ^caseSensitive = true
* ^content = #complete
* ^property[0].code = #definition
* ^property[=].description = "Definition"
* ^property[=].type = #string
* ^property[+].code = #display
* ^property[=].uri = "http://terminology.hl7.org/CodeSystem/designation-usage|display"
* ^property[=].description = "Display"
* ^property[=].type = #string
* ^valueSet = "https://standards.moh.gov.my/fhir/my-core/ValueSet/location-type-my-core"
* #02 "General Medicine" "General Medicine"
* #03 "Cardiology" "Cardiology"
* #04 "Clinical Haematology" "Clinical Haematology"
* #05 "Dermatology" "Dermatology"
* #06 "Endocrinology" "Endocrinology"
* #07 "Gastroenterology" "Gastroenterology"
* #08 "Geriatric" "Geriatric"
* #09 "Hepatology" "Hepatology"
* #10 "Infectious Disease" "Infectious Disease"
* #105 "General Emergency Medicine" "General Emergency Medicine"
* #107 "General Sports Medicine" "General Sports Medicine"
* #109 "General Anaesthesiology" "General Anaesthesiology"
* #11 "Advanced Internal Medicine" "Advanced Internal Medicine"
* #110 "Obstetric Anaesthesia" "Obstetric Anaesthesia"
* #111 "Paediatric Anaesthesia" "Paediatric Anaesthesia"
* #112 "Adult Intensive Care" "Adult Intensive Care"
* #113 "Cardiac Anaesthesia" "Cardiac Anaesthesia"
* #114 "Neuroanaesthesia & Trauma" "Neuroanaesthesia & Trauma"
* #115 "Pain Management" "Pain Management"
* #117 "Anatomical Pathology (Histhopathology)" "Anatomical Pathology (Histhopathology)"
* #118 "Chemical Pathology" "Chemical Pathology"
* #119 "Haematology" "Haematology"
* #12 "Medical Oncology" "Medical Oncology"
* #120 "Medical Microbiology" "Medical Microbiology"
* #122 "General Transfusion Medicine" "General Transfusion Medicine"
* #124 "General Radiology" "General Radiology"
* #125 "Interventional Radiology" "Interventional Radiology"
* #126 "Paediatric Radiology" "Paediatric Radiology"
* #127 "Breast & Endocrine" "Breast & Endocrine"
* #128 "Cardiac Radiology" "Cardiac Radiology"
* #129 "Gastro Hepatobiliary" "Gastro Hepatobiliary"
* #13 "Nephrology" "Nephrology"
* #130 "Uroradiology" "Uroradiology"
* #131 "Musculoskeletal Radiology" "Musculoskeletal Radiology"
* #132 "Women's Imaging" "Women's Imaging"
* #133 "Forensic Radiology" "Forensic Radiology"
* #134 "Neuroradiology" "Neuroradiology"
* #136 "General Forensic Medicine" "General Forensic Medicine"
* #137 "Clinical Forensic Medicine" "Clinical Forensic Medicine"
* #138 "Forensic Anthropology" "Forensic Anthropology"
* #139 "Forensic Pathology" "Forensic Pathology"
* #14 "Neurology" "Neurology"
* #140 "Forensic Toxicology" "Forensic Toxicology"
* #142 "General Multi Disciplines" "General Multi Disciplines"
* #143 "Obstetrics" "Obstetrics"
* #144 "Gynaecology" "Gynaecology"
* #146 "General Family Medicine" "General Family Medicine"
* #148 "Public Health Medicine" "Public Health Medicine"
* #149 "Communicable Disease" "Communicable Disease"
* #15 "Palliative Care" "Palliative Care"
* #150 "Non-communicable Disease" "Non-communicable Disease"
* #151 "Family Health" "Family Health"
* #152 "Health Management" "Health Management"
* #153 "Occupational Health" "Occupational Health"
* #154 "Environmental Health" "Environmental Health"
* #155 "Military Medicine" "Military Medicine"
* #156 "Paediatric Rehabilitation Medicine" "Paediatric Rehabilitation Medicine"
* #157 "General Paediatrics & Child Health" "General Paediatrics & Child Health"
* #158 "Comprehensive Ophthalmology" "Comprehensive Ophthalmology"
* #16 "Respiratory Medicine" "Respiratory Medicine"
* #163 "Clinical Toxicology" "Clinical Toxicology"
* #164 "Emergency Critical Care" "Emergency Critical Care"
* #165 "Emergency Trauma Care" "Emergency Trauma Care"
* #166 "Pre-Hospital Care & Disaster" "Pre-Hospital Care & Disaster"
* #167 "Paediatric Emergency Medicine" "Paediatric Emergency Medicine"
* #168 "Regional Anaethesia" "Regional Anaethesia"
* #169 "General Pathology" "General Pathology"
* #17 "Rheumatology" "Rheumatology"
* #170 "Oncology Imaging" "Oncology Imaging"
* #171 "Head & Neck Radiology" "Head & Neck Radiology"
* #172 "Thoracic Imaging" "Thoracic Imaging"
* #173 "Emergency Radiology" "Emergency Radiology"
* #174 "Paediatric Forensic Medicine" "Paediatric Forensic Medicine"
* #176 "General Special Care Dentistry" "General Special Care Dentistry"
* #178 "General Forensic Odontology" "General Forensic Odontology"
* #180 "General Oral Pathology & Oral Medicine" "General Oral Pathology & Oral Medicine"
* #182 "General Oral Maxillofacial Surgery" "General Oral Maxillofacial Surgery"
* #184 "General Paediatric Dentistry" "General Paediatric Dentistry"
* #186 "General Orthodontics" "General Orthodontics"
* #188 "General Dental Public Health" "General Dental Public Health"
* #19 "General Surgery" "General Surgery"
* #190 "General Periodontology" "General Periodontology"
* #192 "General Restorative Dentistry" "General Restorative Dentistry"
* #194 "General Endodontics" "General Endodontics"
* #196 "General Oral Maxillofacial Imaging" "General Oral Maxillofacial Imaging"
* #198 "General Prosthodontics" "General Prosthodontics"
* #20 "Breast & Endocrine Surgery" "Breast & Endocrine Surgery"
* #21 "Burns & Trauma Surgery" "Burns & Trauma Surgery"
* #22 "Cardiothoracic Surgery" "Cardiothoracic Surgery"
* #23 "Colorectal Surgery" "Colorectal Surgery"
* #24 "Surgical Oncology" "Surgical Oncology"
* #25 "Hepatopancreaticobiliary (HPB) Surgery" "Hepatopancreaticobiliary (HPB) Surgery"
* #26 "Neurosurgery" "Neurosurgery"
* #27 "Paediatric Surgery" "Paediatric Surgery"
* #28 "Plastic & Reconstructive Surgery" "Plastic & Reconstructive Surgery"
* #29 "Thoracic Surgery" "Thoracic Surgery"
* #30 "Upper Gastrointestinal Surgery" "Upper Gastrointestinal Surgery"
* #31 "Urology" "Urology"
* #32 "Vascular Surgery" "Vascular Surgery"
* #34 "General Obstetrics & Gynaecology" "General Obstetrics & Gynaecology"
* #35 "Gynae-oncology" "Gynae-oncology"
* #36 "Maternal Fetal Medicine" "Maternal Fetal Medicine"
* #37 "Reproductive Medicine" "Reproductive Medicine"
* #38 "Urogynaecology" "Urogynaecology"
* #40 "General Paediatrics" "General Paediatrics"
* #41 "Adolescent Medicine" "Adolescent Medicine"
* #42 "Developmental Paeds" "Developmental Paeds"
* #43 "Clinical Genetics" "Clinical Genetics"
* #44 "Neonatology" "Neonatology"
* #45 "Paediatric Cardiology" "Paediatric Cardiology"
* #46 "Paediatric Palliative Medicine" "Paediatric Palliative Medicine"
* #47 "Paediatric Dermatology" "Paediatric Dermatology"
* #48 "Paediatric Emergency Medicine" "Paediatric Emergency Medicine"
* #49 "Paediatric Endocrine" "Paediatric Endocrine"
* #50 "Paediatric Gastroenterology" "Paediatric Gastroenterology"
* #500 "Adult Health (Health screening)" "Adult Health (Health screening)"
* #501 "Antenatal Clinic" "Antenatal Clinic"
* #502 "Children With Special Need" "Children With Special Need"
* #503 "Community Health (Mobile clinic)" "Community Health (Mobile clinic)"
* #504 "Dietetic Service" "Dietetic Service"
* #505 "DOTS" "DOTS"
* #506 "Domicilliary Care" "Domicilliary Care"
* #507 "Family Planning" "Family Planning"
* #508 "Home visit - Delivery" "Home visit - Delivery"
* #509 "Home Visit - Others" "Home Visit - Others"
* #51 "Paediatric Haemato-oncology" "Paediatric Haemato-oncology"
* #510 "Home visit - Postnatal" "Home visit - Postnatal"
* #511 "Methadone Clinic" "Methadone Clinic"
* #512 "Nutrition Service" "Nutrition Service"
* #513 "Mental Health" "Mental Health"
* #514 "Postnatal Care - Baby" "Postnatal Care - Baby"
* #515 "Postnatal Care - Mother" "Postnatal Care - Mother"
* #516 "Pre-pregnancy Care" "Pre-pregnancy Care"
* #517 "Occupational Therapy Service" "Occupational Therapy Service"
* #518 "Physiotherapy Service" "Physiotherapy Service"
* #519 "Counselling Service" "Counselling Service"
* #52 "Paediatric Infectious Diseases" "Paediatric Infectious Diseases"
* #520 "RME - IPT/MRSM/Badan Berkanun" "RME - IPT/MRSM/Badan Berkanun"
* #521 "RME - Kerajaan (> 40 thn)/Medical Surveillance" "RME - Kerajaan (> 40 thn)/Medical Surveillance"
* #522 "RME - Orang Awam/Insuran/Lesen/Umrah/Keluarga-Luar Negara" "RME - Orang Awam/Insuran/Lesen/Umrah/Keluarga-Luar Negara"
* #523 "RME - Pelantikan Kerajaan/Jemaah Haji/Atlet/PLKN" "RME - Pelantikan Kerajaan/Jemaah Haji/Atlet/PLKN"
* #524 "RME - Sekolah Berasrama" "RME - Sekolah Berasrama"
* #525 "RME - Warga Asing" "RME - Warga Asing"
* #526 "Saringan Pengantin" "Saringan Pengantin"
* #527 "School Health" "School Health"
* #528 "Smoking Cessation" "Smoking Cessation"
* #529 "Medical Social Work Service" "Medical Social Work Service"
* #53 "Paediatric Intensive Care" "Paediatric Intensive Care"
* #530 "Womens Health (CBE)" "Womens Health (CBE)"
* #531 "Diabetic Education" "Diabetic Education"
* #532 "Whole Blood Donation" "Whole Blood Donation"
* #533 "Vaccination" "Vaccination"
* #534 "Platelet Apheresis Donation (A)" "Platelet Apheresis Donation (A)"
* #535 "Platelet Apheresis Donation (B)" "Platelet Apheresis Donation (B)"
* #536 "Platelet Apheresis Donation (O)" "Platelet Apheresis Donation (O)"
* #537 "Platelet Apheresis Donation (AB)" "Platelet Apheresis Donation (AB)"
* #538 "Plasma Apheresis Donation (A)" "Plasma Apheresis Donation (A)"
* #539 "Plasma Apheresis Donation (B)" "Plasma Apheresis Donation (B)"
* #54 "Paediatric Rheumatology" "Paediatric Rheumatology"
* #540 "Plasma Apheresis Donation (O)" "Plasma Apheresis Donation (O)"
* #541 "Plasma Apheresis Donation (AB)" "Plasma Apheresis Donation (AB)"
* #542 "Medication Therapy Adherence Clinic (MTAC)" "Medication Therapy Adherence Clinic (MTAC)"
* #543 "Medication Counselling (MC)" "Medication Counselling (MC)"
* #544 "Therapeutic Drug Monitoring (TDM)" "Therapeutic Drug Monitoring (TDM)"
* #545 "Parenteral Nutrition (PN)" "Parenteral Nutrition (PN)"
* #546 "Cytotoxic Drug Reconstitution (CDR)" "Cytotoxic Drug Reconstitution (CDR)"
* #547 "Radiopharmaceutical" "Radiopharmaceutical"
* #548 "IV Admixture" "IV Admixture"
* #549 "Galenical" "Galenical"
* #55 "Paediatrics Nephrology" "Paediatrics Nephrology"
* #550 "Ward Pharmacy" "Ward Pharmacy"
* #551 "Drug Information & Consumer Education (DICE)" "Drug Information & Consumer Education (DICE)"
* #552 "Primary Oral Health Care" "Primary Oral Health Care"
* #553 "Dental School Health" "Dental School Health"
* #554 "Men's Health" "Men's Health"
* #555 "General Health screening" "General Health screening"
* #556 "Clinical Psychology Service" "Clinical Psychology Service"
* #557 "Speech Language Therapy Service" "Speech Language Therapy Service"
* #558 "Audiology  Service" "Audiology  Service"
* #559 "Jabatan Pesakit Luar" "Jabatan Pesakit Luar"
* #56 "Paediatrics Neurology" "Paediatrics Neurology"
* #560 "Procedure" "Procedure"
* #561 "National Health Screening (NHSI)" "National Health Screening (NHSI)"
* #562 "Peka B40 Screening" "Peka B40 Screening"
* #563 "Information Technology" "Information Technology"
* #564 "STD Clinic" "STD Clinic"
* #565 "Combine Clinic" "Combine Clinic"
* #566 "Keputusan Saringan Makmal" "Keputusan Saringan Makmal"
* #567 "Keputusan Saringan Radiologi" "Keputusan Saringan Radiologi"
* #57 "Paediatrics Respiratory Medicine" "Paediatrics Respiratory Medicine"
* #59 "General Orthopaedics" "General Orthopaedics"
* #60 "Joint Arthroplasty" "Joint Arthroplasty"
* #61 "Arthroscopy & Sports Surgery" "Arthroscopy & Sports Surgery"
* #62 "Advanced Musculoskeletal Trauma" "Advanced Musculoskeletal Trauma"
* #63 "Foot & Ankle Surgery" "Foot & Ankle Surgery"
* #64 "Oncology Orthopaedic" "Oncology Orthopaedic"
* #65 "Paediatric Orthopaedic" "Paediatric Orthopaedic"
* #66 "Spine Surgery" "Spine Surgery"
* #67 "Upper Limb, Hand  & Microsurgery" "Upper Limb, Hand  & Microsurgery"
* #69 "General Ophthalmology" "General Ophthalmology"
* #70 "Cornea" "Cornea"
* #71 "Neuro Ophthalmology" "Neuro Ophthalmology"
* #72 "Glaucoma" "Glaucoma"
* #73 "Medical Retinal" "Medical Retinal"
* #74 "Oculoplastic Surgery" "Oculoplastic Surgery"
* #75 "Paediatric Ophthalmology" "Paediatric Ophthalmology"
* #76 "Vitreoretinal" "Vitreoretinal"
* #78 "General Otorhinolaryngology" "General Otorhinolaryngology"
* #79 "Head & Neck Surgery" "Head & Neck Surgery"
* #80 "Otology/Skull Based Surgery" "Otology/Skull Based Surgery"
* #81 "Paediatric ORL" "Paediatric ORL"
* #82 "Rhinology" "Rhinology"
* #84 "General Psychiatry" "General Psychiatry"
* #85 "Child & Adolescent Psychiatry" "Child & Adolescent Psychiatry"
* #86 "Addiction & Substance Abuse" "Addiction & Substance Abuse"
* #87 "Community & Rehab Psychiatry" "Community & Rehab Psychiatry"
* #88 "Forensic Psychiatry" "Forensic Psychiatry"
* #89 "Liaison Psychiatry" "Liaison Psychiatry"
* #90 "Neuropsychiatry" "Neuropsychiatry"
* #91 "Psychogeriatrics" "Psychogeriatrics"
* #93 "General Rehabilitation Medicine" "General Rehabilitation Medicine"
* #95 "General Nuclear Medicine" "General Nuclear Medicine"
* #97 "General Radiotherapy/Clinical Oncology" "General Radiotherapy/Clinical Oncology"
