CodeSystem: CodeSystemPersonTitleMyCore
Id: person-title-my-core
Title: "CodeSystemPersonTitle (MY Core)"
* ^language = #en
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel"
* ^extension.valueCode = #executable
* ^url = "https://standards.moh.gov.my/fhir/my-core/CodeSystem/person-title-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^contact.telecom.system = #email
* ^caseSensitive = true
* ^content = #complete
* ^property[0].code = #definition
* ^property[=].description = "Definition"
* ^property[=].type = #string
* ^property[+].code = #display
* ^property[=].uri = "http://terminology.hl7.org/CodeSystem/designation-usage|display"
* ^property[=].description = "Display"
* ^property[=].type = #string
* ^valueSet = "https://standards.moh.gov.my/fhir/my-core/ValueSet/person-title-my-core"
* #0 "No Information" "No Information"
* #C001 "Tun" "Tun"
* #C002 "Tan Sri" "Tan Sri"
* #C003 "Tan Sri Dato'" "Tan Sri Dato'"
* #C004 "Tan Sri Dato' Dr" "Tan Sri Dato' Dr"
* #C005 "Tan Sri Dato' Ir" "Tan Sri Dato' Ir"
* #C006 "Tan Sri Dato Seri" "Tan Sri Dato Seri"
* #C007 "Tan Sri Datuk" "Tan Sri Datuk"
* #C008 "Tan Sri Datuk Dr" "Tan Sri Datuk Dr"
* #C009 "Tan Sri Datuk Professor" "Tan Sri Datuk Professor"
* #C010 "Tan Sri Datuk Professor Dr" "Tan Sri Datuk Professor Dr"
* #C011 "Tan Sri Dr" "Tan Sri Dr"
* #C012 "Tan Sri General" "Tan Sri General"
* #C013 "Tan Sri Professor" "Tan Sri Professor"
* #C014 "Dato'" "Dato'"
* #C015 "Dato' Dr" "Dato' Dr"
* #C016 "Dato' Ir" "Dato' Ir"
* #C017 "Dato' Ir Dr" "Dato' Ir Dr"
* #C018 "Dato' Paduka Dr" "Dato' Paduka Dr"
* #C019 "Dato' Professor Madya Dr" "Dato' Professor Madya Dr"
* #C020 "Dato' Senara Muda" "Dato' Senara Muda"
* #C021 "Dato' Seri" "Dato' Seri"
* #C022 "Dato' Sri" "Dato' Sri"
* #C024 "Datuk" "Datuk"
* #C025 "Datuk Amar" "Datuk Amar"
* #C026 "Datuk Bentara Luar" "Datuk Bentara Luar"
* #C027 "Datuk Bentara Raja" "Datuk Bentara Raja"
* #C028 "Datuk Dr" "Datuk Dr"
* #C029 "Datuk Ir" "Datuk Ir"
* #C030 "Datuk Patinggi" "Datuk Patinggi"
* #C031 "Datuk Professor" "Datuk Professor"
* #C032 "Datuk Professor Dr" "Datuk Professor Dr"
* #C033 "Datuk Setia" "Datuk Setia"
* #C034 "Datuk Setia Wangsa" "Datuk Setia Wangsa"
* #C035 "Datuk Sri" "Datuk Sri"
* #C036 "Datuk Sri Amar DiRaja" "Datuk Sri Amar DiRaja"
* #C037 "Datuk Sri Dr" "Datuk Sri Dr"
* #C038 "Datuk Wira" "Datuk Wira"
* #C039 "Datuk Wira Jaya" "Datuk Wira Jaya"
* #C040 "Doktor" "Doktor"
* #C041 "Ir" "Ir"
* #C042 "Ir Dr" "Ir Dr"
* #C047 "Major" "Major"
* #C048 "Professor" "Professor"
* #C049 "Professor DiRaja" "Professor DiRaja"
* #C050 "Professor Dr" "Professor Dr"
* #C051 "Professor Madya" "Professor Madya"
* #C052 "Professor Madya Dr" "Professor Madya Dr"
* #C053 "Datu" "Datu"
* #L001 "Encik" "Encik"
* #L002 "Tuan" "Tuan"
* #L003 "Haji" "Haji"
* #P001 "To' Puan" "To' Puan"
* #P002 "Toh Puan" "Toh Puan"
* #P003 "Puan Sri" "Puan Sri"
* #P004 "Puan Sri Datin" "Puan Sri Datin"
* #P005 "Puan Sri Datin Professor" "Puan Sri Datin Professor"
* #P006 "Puan Sri Dr" "Puan Sri Dr"
* #P007 "Puan Sri Utama" "Puan Sri Utama"
* #P008 "Datin" "Datin"
* #P009 "Datin Amar" "Datin Amar"
* #P010 "Datin Dr" "Datin Dr"
* #P011 "Datin Paduka" "Datin Paduka"
* #P012 "Datin Patinggi" "Datin Patinggi"
* #P013 "Datin Professor" "Datin Professor"
* #P014 "Datin Professor Dr" "Datin Professor Dr"
* #P015 "Datin Setia" "Datin Setia"
* #P016 "Datin Sri" "Datin Sri"
* #P017 "Datin Sri Cempaka" "Datin Sri Cempaka"
* #P018 "Datin Sri Dr" "Datin Sri Dr"
* #P019 "Cik" "Cik"
* #P020 "Puan" "Puan"
* #P021 "Hajjah" "Hajjah"
