CodeSystem: CodeSystemPractitionerRoleCodeMyCore
Id: practitioner-role-code-my-core
Title: "CodeSystemPractitionerRoleCode (MY Core)"
Description: "Malaysia list of practitioner role"
* ^language = #en
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel"
* ^extension.valueCode = #executable
* ^url = "https://standards.moh.gov.my/fhir/my-core/CodeSystem/practitioner-role-code-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^publisher = "Malaysia MOH - HIE Steering Committee"
* ^contact.name = "Saifuldaulah Bin Mohd Hafiz Ngoo"
* ^contact.telecom.system = #email
* ^contact.telecom.value = "saifuldaulah@mhn.asia"
* ^caseSensitive = true
* ^content = #complete
* ^property[0].code = #definition
* ^property[=].description = "Definition"
* ^property[=].type = #string
* ^property[+].code = #display
* ^property[=].uri = "http://terminology.hl7.org/CodeSystem/designation-usage|display"
* ^property[=].description = "Display"
* ^property[=].type = #string
* ^valueSet = "https://standards.moh.gov.my/fhir/my-core/ValueSet/practitioner-role-code-my-core"
* #2XL5EL5R9Y "Enviroment Health Officer" "Enviroment Health Officer"
* #AMO "Assistant Medical Officer" "Assistant Medical Officer"
* #APHRO "Assistant Pharmacy Officer" "Assistant Pharmacy Officer"
* #ASDOHD "Assistant Senior Director OHD" "Assistant Senior Director OHD"
* #ATTd "Dental Attendant" "Dental Attendant"
* #ATTh "Health Attendant" "Health Attendant"
* #CASDOHD "Chief Assistant Senior Director OHD" "Chief Assistant Senior Director OHD"
* #CN "Community Nurse" "Community Nurse"
* #CNTRLADMIN "Centraladmin" "Centraladmin"
* #COMFS "Consultant Oral Maxillo Facial Specialist" "Consultant Oral Maxillo Facial Specialist"
* #CORTHO "Consultant Orthodontist" "Consultant Orthodontist"
* #CPAEDO "Consultant Paediatric Dentistry" "Consultant Paediatric Dentistry"
* #CPERIO "Consultant Periodontist" "Consultant Periodontist"
* #CRESTO "Consultant Restorative Specialist" "Consultant Restorative Specialist"
* #CRKd "Dental Clerk" "Dental Clerk"
* #CRKh "Health Clerk" "Health Clerk"
* #CRKhA "Health Clerk (Accounts)" "Health Clerk (Accounts)"
* #CSND "Consultant Special Needs Dentistry" "Consultant Special Needs Dentistry"
* #DDO "District Dental Officer" "District Dental Officer"
* #DDOHD "Deputy Director Oral Health Division" "Deputy Director Oral Health Division"
* #DN "Dental Therapist" "Dental Therapist"
* #DO "Dental Officer" "Dental Officer"
* #DOHCP "Director Oral Health Control and Practice" "Director Oral Health Control and Practice"
* #DOHD "Director Oral Health Development" "Director Oral Health Development"
* #DOI "Dental Officer Incharge" "Dental Officer Incharge"
* #DPHS "Dental Public Health Specialist" "Dental Public Health Specialist"
* #DSA "Dental Surgery Assistant" "Dental Surgery Assistant"
* #DSHDD "Deputy State Health Director (Dental)" "Deputy State Health Director (Dental)"
* #DSTADMIN "District Admin" "District Admin"
* #DT "Dental Technologist" "Dental Technologist"
* #DTT "Dietitian" "Dietitian"
* #EX98C1G9RS "Pegawai Khidmat Pelanggan" "Pegawai Khidmat Pelanggan"
* #FAADMIN "Facility Admin" "Facility Admin"
* #FMS "Family Medicine Specialist" "Family Medicine Specialist"
* #FTEQASKWHS "Principal Dental Therapist" "Principal Dental Therapist"
* #FYDO "First Year Dental Officer" "First Year Dental Officer"
* #GDYEY1NKXO "Assistant Enviroment Health Officer" "Assistant Enviroment Health Officer"
* #HEO "Health Education Officer" "Health Education Officer"
* #HO "House Officer" "House Officer"
* #ITO "IT Officer" "IT Officer"
* #ITP "IT Programmer" "IT Programmer"
* #ITT "IT Technician" "IT Technician"
* #MLT "Medical Lab Technologist" "Medical Lab Technologist"
* #MO "Medical Officer" "Medical Officer"
* #MSW "Medical Social Worker" "Medical Social Worker"
* #MUQUG160J8 "Optometrist" "Optometrist"
* #NRS "Nurse" "Nurse"
* #NTR "Nutritionist" "Nutritionist"
* #OMFS "Oral Maxillo Facial Specialist" "Oral Maxillo Facial Specialist"
* #OMOAISVS8M "Counsellor" "Counsellor"
* #ORTHO "Orthodontist" "Orthodontist"
* #OT "Occupational Therapist" "Occupational Therapist"
* #PAEDO "Paediatric Dentistry" "Paediatric Dentistry"
* #PERIO "Periodontist" "Periodontist"
* #PHRO "Pharmacy Officer" "Pharmacy Officer"
* #PO "Pembantu Operasi" "Pembantu Operasi"
* #PSC "Physiotherapist" "Physiotherapist"
* #PSDT "Post Basic Dental Therapist" "Post Basic Dental Therapist"
* #TDT "Trainee Dental Technologist" "Trainee Dental Technologist"
* #VSp "Visiting Specialist" "Visiting Specialist"
* #VW9ER47J1B "Medical Army" "Medical Army"
* #WFFAKB4GYV "Part Time Worker (PSH)" "Part Time Worker (PSH)"
* #jknadmin "JKN Admin" "JKN Admin"
* #superadmin "Vendor" "Vendor"
