CodeSystem: CodeSystemDentalProcedureMyCore
Id: dental-procedure-my-core
Title: "CodeSystemDentalProcedure (MY Core)"
Description: "Dental Procedure"
* ^language = #en
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel"
* ^extension.valueCode = #executable
* ^url = "https://standards.moh.gov.my/fhir/my-core/CodeSystem/dental-procedure-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^publisher = "Malaysia MOH - HIE Steering Committee"
* ^contact.name = "Saifuldaulah Bin Mohd Hafiz Ngoo"
* ^contact.telecom.system = #email
* ^contact.telecom.value = "saifuldaulah@mhn.asia"
* ^caseSensitive = true
* ^content = #complete
* ^property[0].code = #definition
* ^property[=].description = "Definition"
* ^property[=].type = #string
* ^property[+].code = #display
* ^property[=].uri = "http://terminology.hl7.org/CodeSystem/designation-usage|display"
* ^property[=].description = "Display"
* ^property[=].type = #string
* #00 "Other"
* #1000 "Debridement soft tissue orofacial"
* #1001 "Surgical removal of simple impacted / unerupted tooth"
* #1002 "Soft laser therapy-orofacial"
* #1003 "Reimplantation tooth"
* #1004 "Apicoectomy - anterior tooth"
* #1005 "Apicoectomy - posterior tooth"
* #1006 "Apicoectomy with retrograde root filling - anterior tooh"
* #1007 "Apicoectomy with retrograde root filling - posterior tooh"
* #1008 "TMJ-reduction-closed"
* #1009 "Alveolar bone grafting"
* #1010 "Debridement Suture soft tissue orofacial-lip simple"
* #1011 "Debridement Suture soft tissue orofacial- mouth simple"
* #1012 "Debridement Suture soft tissue orofacial- lip complicated"
* #1013 "Debridement Suture soft tissue orofacial- mouth complicated"
* #1014 "Revision suture soft tissue orofacial-lip simple"
* #1015 "Revision suture soft tissue orofacial-nouth simple"
* #1016 "Revision suture soft tissue orofacial-complicated"
* #1017 "Revision suture soft tissue orofacial-complicated"
* #1021 "Temporary reduction and fixation-midfacial bone"
* #1022 "Temporary reduction and fixation-mandible"
* #1023 "Closed reduction & fixation- midfacial bone"
* #1024 "Closed reduction & fixation- mandible"
* #1025 "Incision and drainage orofacial abscess"
* #1026 "Alveolectomy/Alveoloplasty-maxilla <=4cm"
* #1027 "Alveolectomy / Alveoplasty - maxilla > 4cm"
* #1028 "Alveolectomy/Alveoloplasty-mandible <=4cm"
* #1029 "Alveolectomy/Alveoloplasty-mandible >4cm"
* #1030 "Vestibuloplasty-gingival/alveolar soft tissue"
* #1031 "Vestibuloplasty-gingival/alveolar soft tissue-autograft"
* #1032 "Frenotomy - lingual"
* #1033 "Frenotomy - labial"
* #1034 "Frenectomy - lingual"
* #1035 "Frenectomy - labial"
* #1036 "Frenectomy-LASER -lingual"
* #1037 "Frenectomy-LASER -labial"
* #1038 "Frenoplasty -lingual"
* #1039 "Frenoplasty- labial"
* #1040 "Transplantation tooth"
* #1041 "Surgical removal of retained root"
* #1042 "Surgical removal of displaced tooth / root"
* #1043 "Surgical removal of impacted / unerupted tooth-complex"
* #1044 "Surgical exposure of tooth without placement of attachment"
* #1045 "Surgical exposure of tooth with placement of attachment"
* #1046 "Antral washout-Caldwell-Luc-left"
* #1047 "Antral washout-Caldwell-Luc-right"
* #1048 "Closure oro-antral fistula"
* #1049 "Biopsy-upper lip"
* #1050 "Biopsy-lower lip"
* #1051 "Biopsy-Tongue"
* #1052 "Biopsy-floor of mouth"
* #1053 "Biopsy-Hard palate soft tissue"
* #1054 "Biopsy-Soft palate"
* #1055 "Biopsy-Buccal soft tissue"
* #1056 "Biopsy-gingiva/alveolar soft tissue"
* #1057 "Biopsy-retromolar/palatoglossal arch soft tissue"
* #1068 "Removal foreign body-orofacial-simple"
* #1069 "Removal foreign body-orofacial-complicated"
* #1070 "Removal dental implants-maxilla"
* #1071 "Removal dental implants-mandible"
* #1072 "Removal maxillofacial implants"
* #1073 "Removal internal fixation-maxillofacial"
* #1074 "Removal external fixation-maxillofacial"
* #1075 "Removal dental wires-upper arch"
* #1076 "Removal dental wires-lower arch"
* #1077 "Removal dental wires-both arch"
* #1078 "Injection Medication-orofacial"
* #1079 "Ultrasound therapy-oromaxillofacial"
* #1080 "Operculectomy"
* #1081 "Non-surgical reposition of tooth"
* #1082 "Surgical reposition of tooh"
* #1083 "Application of Prophylaxis"
* #1084 "Photography-oral/facial photo images -Intraoral"
* #1085 "Photography-oral/facial photo images -Extraoral"
* #1086 "Preliminary dental impression (alginate)"
* #1087 "Placement of orthodontic bands"
* #1088 "Provision of Removable Retainer - upper arch"
* #1089 "Provision of Removable Retainer - lower arch"
* #1090 "Provision of Removable Retainer - both arches"
* #1091 "Provision of  Removable Space Maintainer  - upper arch"
* #1092 "Provision of  Removable Space Maintainer  - lower arch"
* #1093 "Provision of  Removable Space Maintainer  - both arches"
* #1094 "Provision of fixed retainer - upper arch"
* #1095 "Provision of fixed retainer - lower arch"
* #1096 "Provision of fixed retainer - both arches"
* #1097 "Debond/Removal of fixed retainer - upper arch"
* #1098 "Debond/Removal of fixed retainer - lower arch"
* #1099 "Debond/Removal of fixed retainer - both arches"
* #1100 "Provision of  strapping appliance"
* #1101 "Provision of Removable Appliance - upper arch"
* #1102 "Provision of Removable Appliance - lower arch"
* #1103 "Provision of Removable Appliance - both arches"
* #1104 "Provision of Functional Appliance - Removable"
* #1105 "Provision of Functional Appliance - Fixed"
* #1106 "Provision of Fixed  expansion appliance - maxillary"
* #1107 "Provision of Fixed expansion appliance - mandibulary"
* #1108 "Provision of Fixed Space Maintainer  - upper arch  (Palatal Arch)"
* #1109 "Provision of  Fixed Space Maintainer  - lower arch (Lingual Arch)"
* #1110 "Provision of  Fixed Space Maintainer  - both arches"
* #1111 "Provision of Fixed Appliance-Upper"
* #1112 "Provision of Fixed Appliance-Lower"
* #1113 "Provision of Fixed Appliance-both"
* #1114 "Provision of Headgear"
* #1115 "Provision of face mask-extra-oral  component (Reverse Headgear)"
* #1116 "Provision of lingual arch"
* #1117 "Provision of lip bumper  (Removable Functional)"
* #1118 "Repair of Fixed Appliance"
* #1119 "Repair of Removable  Appliance"
* #1120 "Debond/Removal of Fixed Appliance -upper arch"
* #1121 "Debond/Removal of Fixed Appliance -lower arch"
* #1122 "Debond/Removal of Fixed Appliance -both arches"
* #1123 "Review of Fixed Appliance"
* #1124 "Replacement of orthodontic attachments (buttons,hooks,cleats)"
* #1126 "Replacement of orthodontic brackets"
* #1127 "Replacement of orthodontic wire- upper arch"
* #1128 "Replacement of orthodontic wire - lower arch"
* #1129 "Replacement of orthodontic wire - both arches"
* #1130 "Removal of fixed appliance components"
* #1131 "Insertion of orthodontic separator"
* #1132 "Interdental stripping"
* #1133 "Placement of traction chain"
* #1134 "Placement of Temporary Anchorage Device"
* #1138 "Chin cup treatment"
* #1139 "Intial examination and diagnosis"
* #1140 "Removable appliance (passive) - upper"
* #1141 "Removable appliance (passive) - lower"
* #1142 "Removable appliance (active)- upper"
* #1143 "Removable appliance (active) - lower"
* #1144 "Partial fixed appliance - upper"
* #1145 "Partial fixed appliance - lower"
* #1146 "Fixed appliance components replacement (per component)"
* #1147 "Repair of removable appliance component"
* #1148 "Repair Removable functional appliance"
* #1149 "Provision of Orthodontic auxiliary"
* #1150 "Provision of Transpalatal arch"
* #1151 "Repair of Transpalatal arch"
* #1152 "Repair of Lingual arch"
* #1153 "Transpalatal arch (each re- cementation)"
* #1154 "Lingual arch (each re- cementation)"
* #1155 "Provision of Essix retainer"
* #1156 "Repair Fixed retainer"
* #1157 "Provision of Gold chain"
* #1158 "Palatal expander treatment"
* #1159 "Headgear treatment"
* #1160 "Repair of Removable retainers"
* #1161 "Fissure sealant - per tooth"
* #1162 "Diet Counselling"
* #1163 "Root Canal Treatment- Arrest resorption"
* #1164 "Inhalation sedation (Nitrous oxide)"
* #1165 "Stainless steel crown - per unit"
* #1166 "Strip crown - per unit"
* #1167 "Behavioral therapy"
* #1168 "Splinting of teeth"
* #1169 "Feeding plate"
* #1170 "Sensory testing"
* #1171 "Functional removable appliance"
* #1172 "Taping/Bandaging/Strapping"
* #1173 "Oral muscle stimulation"
* #1174 "Other dental appliances"
* #1175 "Gingivectomy"
* #1176 "Scaling - supragingival-gross with polishing"
* #1177 "Scaling - supragingival-fine with polishing"
* #1178 "Scaling - subgingival-gross with polishing"
* #1179 "Scaling - subgingival-fine with polishing"
* #1180 "Occlusal adjustment"
* #1181 "Crown lengthening with ostectomy"
* #1182 "Immobilisation of teeth"
* #1183 "Gingivectomy-LASER"
* #1184 "Gingivoplasty"
* #1185 "Gingivoplasty-LASER"
* #1186 "Root planing of tooth"
* #1187 "Incision & drainage of peridontal abscess"
* #1188 "Flap surgery"
* #1189 "Open Flap Debridement"
* #1190 "Pocket Elimination Surgery"
* #1191 "Guided tissue regeneration"
* #1192 "Guided Bone Regeneration"
* #1193 "Guided tissue regeneration (second surgery)"
* #1194 "Mucogingival surgery-autograft"
* #1195 "Mucogingival surgery-allograft"
* #1196 "Pericision of periodontal ligament"
* #1197 "Furcationplasty-Tunnelling"
* #1198 "Furcationplasty-Grooveplasty"
* #1199 "Veneer gingival Labial"
* #1200 "Crown lengthening without ostectomy"
* #1201 "Periapical surgery"
* #1202 "Root resection"
* #1203 "Tooth Hemisection"
* #1204 "Periodontal examination"
* #1205 "Dental scaling and polishing"
* #1206 "To provide denture-upper full"
* #1207 "To provide  of denture-lower full"
* #1208 "To provide denture-upper partial (1 tooth)"
* #1209 "To provide denture-upper partial (2 teeth)"
* #1210 "To provide denture-upper partial (3 teeth)"
* #1211 "To provide denture-upper partial (4 teeth)"
* #1212 "To provide denture-upper partial (5 teeth)"
* #1213 "To provide denture-upper partial (6 teeth)"
* #1214 "To provide denture-upper partial (7 teeth)"
* #1215 "To provide denture-upper partial (8 teeth)"
* #1216 "To provide denture-upper partial (9 teeth)"
* #1217 "To provide denture-upper partial (10 teeth)"
* #1218 "To provide denture-upper partial (11 teeth)"
* #1219 "To provide denture-upper partial (12 teeth)"
* #1220 "To provide denture-upper partial (13 teeth)"
* #1221 "To provide denture-upper partial (14 teeth)"
* #1222 "To provide denture-upper partial (15 teeth)"
* #1223 "To provide denture-lower partial (1 tooth)"
* #1224 "To provide denture-lower partial (2 teeth)"
* #1225 "To provide denture-lower partial (3 teeth)"
* #1226 "To provide denture-lower partial (4 teeth)"
* #1227 "To provide denture-lower partial (5 teeth)"
* #1228 "To provide denture-lower partial (6 teeth)"
* #1229 "To provide denture-lower partial (7 teeth)"
* #1230 "To provide denture-lowerpartial (8 teeth)"
* #1231 "To provide denture-lower partial (9 teeth)"
* #1232 "To provide denture-lower partial (10 teeth)"
* #1233 "To provide denture-lower partial (11 teeth)"
* #1234 "To provide denture-lowerpartial (12 teeth)"
* #1235 "To provide denture-lower partial (13 teeth)"
* #1236 "To provide denture-lowerpartial (14 teeth)"
* #1237 "To provide denture-lower partial (15 teeth)"
* #1238 "Rebasing and relining of upper denture"
* #1239 "Rebasing and relining of lower denture"
* #1240 "Repair of broken appliance"
* #1241 "Repair of broken obturator"
* #1242 "Placement of restoration - deciduous"
* #1243 "Placement of restoration-permanent- one surface"
* #1244 "Placement of restoration-permanent-multiple surfaces"
* #1245 "Placement of Temporary restoration"
* #1246 "Root canal treatment - interim visits"
* #1247 "Root canal treatment-  obturation of anterior tooth"
* #1248 "Root canal treatment-obturation of premolar"
* #1249 "Root canal treatment - obturation of molar tooth"
* #1250 "Root canal treatment- retrieval of separated/ broken instrument"
* #1251 "Suture removal"
* #1252 "Consultation"
* #1253 "Dental examination and charting"
* #1254 "Comprehensive history and evaluation"
* #1255 "Surgical removal of supernumerary tooth (simple)"
* #1256 "Surgical removal of supernumerary tooth (complex)"
* #1257 "Surgical removal of retained root"
* #1258 "Pulpectomy - deciduous"
* #1259 "Pulpotomy deciduous tooth"
* #1260 "Provision of Dental appliances or obturators  -small"
* #1261 "Provision of Dental appliances or obturators  -medium"
* #1262 "Provision of Dental appliances or obturators -large"
* #1263 "Dental implant stage 1 surgery"
* #1264 "Dental implant stage 2 surgery"
* #1265 "Provision of veneer"
* #1266 "Bleaching of tooth - non vital"
* #1267 "Bleaching of teeth - vital"
* #1268 "Removal of bridge"
* #1269 "Provision of mouthguard"
* #1270 "Provision of  soft splint"
* #1271 "Provision of hard splint"
* #1272 "Provision of other splint"
* #1273 "Provision of eye prosthesis"
* #1274 "Provision of other maxillofacial prosthesis (ear /nose)"
* #1275 "To provide of overdenture-upper full"
* #1276 "To provide of overdenture-lower full"
* #1279 "Provision of feeding plate"
* #1280 "Repair of crown and bridge (with composite)"
* #1281 "Removal of post and core"
* #1282 "Removal of crown"
* #1283 "Provision of post and core device"
* #1284 "Construction of provisional restoration per unit (crown/bridge/onlay)"
* #1285 "Placement-restoration with pin retention"
* #1286 "Microabrasion"
* #1287 "Arrest of tooth resorption"
* #1288 "Root canal retreatment-obturation of anterior tooth"
* #1289 "Root canal retreatment-obturation of premolar"
* #1290 "Root canal retreatment-obturation of molar"
* #1291 "Repair  of procedural error - eg perforated root"
* #1292 "Retrieval of separated/ broken instrument"
* #1293 "Modification of tooth morphology"
* #1294 "Occlusal adjustment"
* #1295 "Recontouring of pre-existing restoration"
* #1297 "Intentional tooth  reimplantation"
* #1298 "provision of metal copings"
* #1299 "Preventive Resin Restoration I (PRR I)"
* #1300 "Preventive Resin Restoration II (PRR II)"
* #1301 "Preventive Resin Restoration III (PRR III)"
* #1302 "Topical application of fluoride - upper arch"
* #1303 "Topical application of fluoride - lower arch"
* #1304 "Topical application of fluoride - both arches"
* #1305 "Extraction permanent tooth"
* #1306 "Extraction supernumerary"
* #1307 "Extraction retained root"
* #1308 "Extraction deciduous tooth"
* #1309 "Control of post extraction haemorrhage"
* #1310 "Post-extraction complication"
* #1311 "Gingival operculectomy"
* #1312 "Provision of Inlay (per tooth) \n(not inclusive of metal charge)"
* #1313 "Provision of Crown \n(including temporary crown but not inclusive of metal charge)"
* #1314 "Provision of Fixed Bridge \n(per abutment teeth including provisional restoration but not inclusive of material and lab charges)"
* #1315 "Provision of Removable Bridge \n(per abutment teeth including provisional restoration but not inclusive of material and lab charges)"
* #1317 "Apexification (per tooth)"
* #1318 "Arrest of tooth resorption (per tooth)"
* #1319 "Coronal pulpotomy (per permanent tooth)"
* #1320 "Pulpectomy (per deciduous tooth)"
* #1321 "Pulp extirpation (per tooth)"
* #1322 "Tooth bleaching (external)(per arch)"
* #1323 "Tooth bleaching (internal) (per tooth)"
* #1324 "Desensitisation (per arch)"
* #1327 "Denture repair without changing the base plate"
* #1328 "Denture repair (addition of each acrylic tooth)"
* #1329 "Impression for working model"
* #1330 "Aversion therapy"
* #1331 "Behaviour modification"
* #1332 "Desensitization therapy"
* #1333 "Extinction therapy"
* #1334 "Relaxation training"
* #1335 "Hypnosis"
* #1336 "Sedation - Benzodiazepine"
* #1338 "Pulp vitality test"
* #1339 "Diagnostic cast"
* #1340 "Caries susceptibility test"
* #1341 "Zygoma X-Ray"
* #1342 "Post Nasal Space X-Ray"
* #1343 "TMJ-Transcranial - Single View"
* #1344 "TMJ-Transpharyngeal - Single View"
* #1345 "Internal Auditory Meatus (IAM) X-Ray"
* #1346 "Pituitary fossa X-Ray"
* #1347 "Mastoids X-Ray"
* #1348 "Petrous Temporal bone X-Ray"
* #1349 "Cephalometric Postero-anterior of Jaws X-Ray"
* #1350 "Panoramic Tomogram"
* #1351 "True Cephalometric Lateral Skull"
* #1352 "Periapical"
* #1353 "Bitewing"
* #1354 "Upper True Occlusal"
* #1355 "Upper Oblique Occlusal"
* #1356 "Lower Occlusal 450"
* #1357 "Lower Occlusal 900"
* #1358 "Lower Oblique Occlusal"
* #1359 "Digital Periapical"
* #1360 "Digital Bitewing"
* #1361 "Digital Upper True Occlusal"
* #1362 "Digital Upper Oblique Occlusal"
* #1363 "Digital Lower Occlusal 450"
* #1364 "Digital Lower Occlusal 900"
* #1365 "Digital Lower Oblique Occlusal"
* #1366 "CBCT Tooth"
* #1367 "CBCT Teeth"
* #1368 "CBCT Upper Jaw"
* #1369 "CBCT Lower Jaw"
* #1370 "CBCT Upper and Lower Jaw"
* #1371 "CBCT Face"
* #1372 "CBCT Pro Face"
* #1373 "Orthopanthomogram (OPG)"
* #1374 "3 D Orthopanthomogram (OPG)"
* #1375 "Lower True Occlusal"
* #1376 "Digital Lower True Occlusal"
* #1377 "Provision of Fixed Appliance (prior to Mar 2017)"
