ValueSet: MyCoreRadiologyProcedureImageGuidedProceduresMyCore
Id: radiology-procedure-guidance-my-core
Title: "MY Core Radiology Procedure - Image-guided procedures"
Description: "NATIONAL SELECTION. The image-guided procedures subset of the LOINC/RSNA Radiology Playbook. 241 codes. A modality-scoped pick list; the full catalogue is radiology-procedure-my-core."
* ^url = "https://standards.moh.gov.my/fhir/my-core/ValueSet/radiology-procedure-guidance-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^publisher = "Data Team, Digital Health Division, Ministry of Health Malaysia"
* ^copyright = "This value set enumerates LOINC codes. LOINC is copyright Regenstrief Institute, Inc. and the LOINC Committee, and is available at no cost under the LOINC licence. RPID identifiers are from the RSNA Radiology Playbook."
* ^compose.inactive = false
* $loinc#25027-4 "Guidance for placement of large bore CV catheter in Vein"
* $loinc#25072-0 "Guidance for placement of infusion port"
* $loinc#26307-9 "Guidance for placement of large bore CV catheter in Vein - bilateral"
* $loinc#26308-7 "Guidance for placement of large bore CV catheter in Vein - left"
* $loinc#26309-5 "Guidance for placement of large bore CV catheter in Vein - right"
* $loinc#86993-3 "Guidance for 1 level kyphoplasty of Spine vertebra"
* $loinc#86994-1 "Guidance for 1 or 2 injections of trigger point of Muscle"
* $loinc#86995-8 "Guidance for abscess"
* $loinc#86996-6 "Guidance for additional augmentation of Spine vertebra"
* $loinc#86997-4 "Guidance for additional day infusion of thrombolytic of Vessel-- W thrombolytic via catheter"
* $loinc#86998-2 "Guidance for additional percutaneous mechanical thrombectomy of Vein"
* $loinc#86999-0 "Guidance for additional percutaneous mechanical thrombectomy of Artery"
* $loinc#87000-6 "Guidance for additional placement of endovascular device of Vein"
* $loinc#87001-4 "Guidance for additional placement of stent of Artery"
* $loinc#87002-2 "Guidance for additional placement of wire"
* $loinc#87003-0 "Guidance for additional vertebroplasty of Spine vertebra"
* $loinc#87004-8 "Guidance for arthrocentesis of Joint.intermediate"
* $loinc#87005-5 "Guidance for arthrocentesis of Joint.major"
* $loinc#87006-3 "Guidance for arthrocentesis of Joint.small"
* $loinc#87007-1 "Guidance for arthrocentesis of Joint"
* $loinc#87008-9 "Guidance for fluid aspiration of Bone marrow"
* $loinc#87009-7 "Guidance for aspiration of cyst"
* $loinc#87010-5 "Guidance for aspiration of cyst of Bone"
* $loinc#87011-3 "Guidance for aspiration of ganglion cyst"
* $loinc#87012-1 "Guidance for fluid aspiration of Lymph node"
* $loinc#87013-9 "Guidance for percutaneous biopsy of Bone"
* $loinc#87014-7 "Guidance for biopsy of Bone marrow"
* $loinc#87015-4 "Guidance for biopsy of Lymph node"
* $loinc#87016-2 "Guidance for biopsy of Soft tissue"
* $loinc#87017-0 "Guidance for check of drainage catheter for abscess"
* $loinc#87018-8 "Guidance for deep biopsy of Bone"
* $loinc#87019-6 "Guidance for drainage"
* $loinc#87020-4 "Guidance for embolization of Artery"
* $loinc#87021-2 "Guidance for embolization of Vein"
* $loinc#87022-0 "Guidance for embolization of Vessels"
* $loinc#87023-8 "Guidance for exchange of drainage catheter for abscess"
* $loinc#87024-6 "Guidance for additional day infusion of thrombolytic of Chest-- W thrombolytic via chest tube"
* $loinc#87025-3 "Guidance for additional level kyphoplasty of Thoracic spine"
* $loinc#87026-1 "Guidance for additional vertebroplasty of Thoracic spine"
* $loinc#87027-9 "Guidance for biopsy of Chest Pleura"
* $loinc#87028-7 "Guidance for biopsy of Lung"
* $loinc#87029-5 "Guidance for biopsy of Mediastinum"
* $loinc#87030-3 "Guidance for biopsy of Neck or Chest Soft tissue"
* $loinc#87031-1 "Guidance for check of peritoneovenous shunt of Chest and Abdomen"
* $loinc#87032-9 "Guidance for cryoablation of Lung"
* $loinc#87033-7 "Guidance for drainage of Chest Pleura"
* $loinc#87034-5 "Guidance for exchange of catheter portion only of CV catheter with port of Chest"
* $loinc#87035-2 "Guidance for exchange of CV catheter with port of Chest"
* $loinc#87036-0 "Guidance for additional level kyphoplasty of Lumbar spine"
* $loinc#87037-8 "Guidance for additional placement of stent of Iliac artery"
* $loinc#87038-6 "Guidance for additional transluminal angioplasty of Iliac artery"
* $loinc#87039-4 "Guidance for additional vertebroplasty of Lumbar spine"
* $loinc#87040-2 "Guidance for aspiration of cyst of Kidney"
* $loinc#87041-0 "Guidance for percutaneous biopsy of Kidney"
* $loinc#87042-8 "Guidance for percutaneous biopsy of Liver"
* $loinc#87043-6 "Guidance for biopsy of Ureter"
* $loinc#87044-4 "Guidance for check of tube of Biliary ducts"
* $loinc#87045-1 "Guidance for cholangioscopy and removal of calculus of Gallbladder"
* $loinc#87046-9 "Guidance for cholangioscopy of Gallbladder"
* $loinc#87047-7 "Guidance for cholecystostomy of Gallbladder"
* $loinc#87048-5 "Guidance for conversion of G-tube to GJ-tube of Gastrointestinal tract upper"
* $loinc#87049-3 "Guidance for cryoablation of Kidney"
* $loinc#87050-1 "Guidance for cryoablation of Liver"
* $loinc#87051-9 "Guidance for dilation of stricture of Biliary ducts"
* $loinc#87052-7 "Guidance for exchange of G-tube of Stomach"
* $loinc#87053-5 "Guidance for exchange of J-tube of Gastrointestinal tract upper"
* $loinc#87054-3 "Guidance for exchange of nephrostomy tube of Kidney"
* $loinc#87055-0 "Guidance for biopsy of Pancreas"
* $loinc#87056-8 "Guidance for biopsy of Abdomen"
* $loinc#87057-6 "Guidance for placement of fiducial marker in Abdomen"
* $loinc#87058-4 "Guidance for radiofrequency ablation of Kidney"
* $loinc#87059-2 "Guidance for biopsy of Biliary ducts"
* $loinc#87060-0 "Guidance for removal of calculus from Biliary ducts"
* $loinc#87061-8 "Guidance for injection of contrast of Biliary ducts"
* $loinc#87062-6 "Guidance for nerve block of Celiac plexus"
* $loinc#87063-4 "Guidance for removal of GJ-tube from Gastrointestinal tract upper"
* $loinc#87064-2 "Guidance for placement of GJ-tube in Gastrointestinal tract upper"
* $loinc#87065-9 "Guidance for placement of G-tube in Gastrointestinal tract upper"
* $loinc#87066-7 "Guidance for percutaneous placement of nephrostomy tube of Kidney"
* $loinc#87067-5 "Guidance for transjugular biopsy of Kidney"
* $loinc#87068-3 "Guidance for transjugular biopsy and venography of Kidney"
* $loinc#87069-1 "Guidance for hemodynamic evaluation of Liver"
* $loinc#87070-9 "Guidance for microwave ablation of Liver"
* $loinc#87071-7 "Guidance for radiofrequency ablation of Liver"
* $loinc#87072-5 "Guidance for placement of TIPS of Liver"
* $loinc#87073-3 "Guidance for revision of TIPS of Liver"
* $loinc#87074-1 "Guidance for transhepatic revision of tube of Liver"
* $loinc#87075-8 "Guidance for transjugular biopsy of Liver"
* $loinc#87076-6 "Guidance for transjugular biopsy and hemodynamic evaluation of Liver"
* $loinc#87077-4 "Guidance for transjugular biopsy and venography of Liver"
* $loinc#87078-2 "Guidance for percutaneous drainage of Abdomen"
* $loinc#87079-0 "Guidance for paracentesis and insertion of tube of Peritoneum"
* $loinc#87080-8 "Guidance for paracentesis of Peritoneum"
* $loinc#87081-6 "Guidance for placement of catheter in Peritoneum"
* $loinc#87082-4 "Guidance for removal of catheter from Peritoneum"
* $loinc#87083-2 "Guidance for reposition of catheter in Peritoneum"
* $loinc#87084-0 "Guidance for removal of foreign body from Peritoneum"
* $loinc#87085-7 "Guidance for placement of port in Peritoneum"
* $loinc#87086-5 "Guidance for removal of port from Peritoneum"
* $loinc#87087-3 "Guidance for percutaneous transluminal angioplasty of Renal artery"
* $loinc#87088-1 "Guidance for puncture of Lumbar spine"
* $loinc#87089-9 "Guidance for kyphoplasty of Lumbar spine"
* $loinc#87090-7 "Guidance for myelography of Lumbar spine"
* $loinc#87091-5 "Guidance for vertebroplasty of Lumbar spine"
* $loinc#87092-3 "Guidance for placement of venous filter in Inferior vena cava"
* $loinc#87093-1 "Guidance for removal of venous filter from Inferior vena cava"
* $loinc#87094-9 "Guidance for reposition of venous filter in Inferior vena cava"
* $loinc#87095-6 "Guidance for percutaneous transluminal angioplasty of Visceral artery"
* $loinc#87096-4 "Guidance for placement of stent in Visceral artery"
* $loinc#87097-2 "Guidance for placement of peritoneovenous shunt in Chest and Abdomen"
* $loinc#87098-0 "Guidance for removal of peritoneovenous shunt from Chest and Abdomen"
* $loinc#87099-8 "Guidance for revision of peritoneovenous shunt of Chest and Abdomen"
* $loinc#87100-4 "Guidance for percutaneous transluminal angioplasty of Thoracic and abdominal aorta"
* $loinc#87101-2 "Guidance for percutaneous transluminal angioplasty of Brachiocephalic artery"
* $loinc#87102-0 "Guidance for initial day infusion of thrombolytic of Chest-- W thrombolytic via chest tube"
* $loinc#87103-8 "Guidance for infusion of thrombolytic of Chest-- W thrombolytic via CVC"
* $loinc#87104-6 "Guidance for injection of CV catheter of Chest"
* $loinc#87105-3 "Guidance for reposition of CV catheter in Chest"
* $loinc#87106-1 "Guidance for placement of CV catheter with port in Chest"
* $loinc#87107-9 "Guidance for removal of CV catheter with port from Chest"
* $loinc#87108-7 "Guidance for repair of CV catheter with port of Chest"
* $loinc#87109-5 "Guidance for placement of Swan-Ganz catheter in Chest"
* $loinc#87110-3 "Guidance for thoracentesis and insertion of tube of Chest"
* $loinc#87111-1 "Guidance for thoracentesis of Chest"
* $loinc#87112-9 "Guidance for exchange of tunneled CV catheter without port of Chest"
* $loinc#87113-7 "Guidance for placement of tunneled CV catheter without port in Chest"
* $loinc#87114-5 "Guidance for removal of tunneled CV catheter without port from Chest"
* $loinc#87115-2 "Guidance for repair of non-tunneled CV catheter without port of Chest"
* $loinc#87116-0 "Guidance for placement of chest tube in Chest"
* $loinc#87117-8 "Guidance for pericardiocentesis of Heart"
* $loinc#87118-6 "Guidance for placement of fiducial marker in Lung"
* $loinc#87119-4 "Guidance for microwave ablation of Lung"
* $loinc#87120-2 "Guidance for radiofrequency ablation of Lung"
* $loinc#87121-0 "Guidance for placement of tunneled catheter in Chest Pleura"
* $loinc#87122-8 "Guidance for kyphoplasty of Thoracic spine"
* $loinc#87123-6 "Guidance for myelography of Thoracic spine"
* $loinc#87124-4 "Guidance for vertebroplasty of Thoracic spine"
* $loinc#87125-1 "Guidance for nerve block of Thoracic spine intercostal nerve"
* $loinc#87126-9 "Guidance for removal of venous filter from Superior vena cava"
* $loinc#87127-7 "Guidance for reposition of venous filter in Superior vena cava"
* $loinc#87128-5 "Guidance for placement of venous filter in Superior vena cava"
* $loinc#87129-3 "Guidance for percutaneous transluminal angioplasty of Lower leg"
* $loinc#87130-1 "Guidance for laser ablation of Extremity vein"
* $loinc#87131-9 "Guidance for greater than 20 stab phlebectomy of Extremity vein"
* $loinc#87132-7 "Guidance for injection of Ankle"
* $loinc#87133-5 "Guidance for percutaneous transluminal angioplasty of Femoral artery and Popliteal artery"
* $loinc#87134-3 "Guidance for placement of stent in Femoral artery and Popliteal artery"
* $loinc#87135-0 "Guidance for injection of Hip"
* $loinc#87136-8 "Guidance for fluid aspiration of Knee"
* $loinc#87137-6 "Guidance for injection of Knee"
* $loinc#87138-4 "Guidance for additional laser ablation of Extremity vein"
* $loinc#87139-2 "Guidance for additional transluminal angioplasty of Lower leg"
* $loinc#87140-0 "Guidance for additional placement of stent of Lower leg vessel"
* $loinc#87141-8 "Guidance for placement of CV catheter with port in Upper extremity"
* $loinc#87142-6 "Guidance for exchange of CV catheter with port of Upper extremity"
* $loinc#87143-4 "Guidance for exchange of peripherally inserted central catheter of Upper extremity"
* $loinc#87144-2 "Guidance for placement of peripherally-inserted central venous catheter in Upper extremity"
* $loinc#87145-9 "Guidance for embolization of Brachial artery"
* $loinc#87146-7 "Guidance for injection of Shoulder"
* $loinc#87147-5 "Guidance for injection of Wrist"
* $loinc#87148-3 "Guidance for injection of thrombin for pseudoaneurysm"
* $loinc#87149-1 "Guidance for exchange of chest tube of Chest"
* $loinc#87150-9 "Guidance for percutaneous transluminal angioplasty of Iliac artery"
* $loinc#87151-7 "Guidance for placement of stent in Iliac artery"
* $loinc#87152-5 "Guidance for exchange of ureterostomy through ileal conduit of Ureter"
* $loinc#87153-3 "Guidance for for therapeutic puncture and drainage of Cervical spine"
* $loinc#87154-1 "Guidance for diagnostic puncture of Cervical spine"
* $loinc#87155-8 "Guidance for fine needle aspiration of Thyroid gland"
* $loinc#87156-6 "Guidance for percutaneous biopsy.core needle of Thyroid gland"
* $loinc#87157-4 "Guidance for injection of platelet rich plasma"
* $loinc#87158-2 "Guidance for injection of Tendon"
* $loinc#87159-0 "Guidance for injection of Temporomandibular joint"
* $loinc#87160-8 "Guidance for injection of Spine facet joint"
* $loinc#87161-6 "Guidance for injection of Spine epidural space"
* $loinc#87162-4 "Guidance for placement of needle"
* $loinc#87163-2 "Guidance for placement of endovascular device in Vein"
* $loinc#87164-0 "Guidance for secondary mechanical thrombectomy of Artery"
* $loinc#87165-7 "Guidance for placement of endograft in Iliac artery"
* $loinc#87166-5 "Guidance for percutaneous transluminal angioplasty of Vein"
* $loinc#87167-3 "Guidance for transcatheter biopsy"
* $loinc#87168-1 "Guidance for transcatheter placement of stent"
* $loinc#87169-9 "Guidance for initial mechanical thrombectomy of Artery"
* $loinc#87170-7 "Guidance for ligation of Lymphatic vessel"
* $loinc#87171-5 "Guidance for placement of clip"
* $loinc#87172-3 "Guidance for placement of clip-- preoperative"
* $loinc#87173-1 "Guidance for biopsy of Prostate"
* $loinc#87174-9 "Guidance for biopsy of Muscle"
* $loinc#87175-6 "Guidance for deep drainage of Pelvis"
* $loinc#87176-4 "Guidance for radiofrequency ablation of Bone"
* $loinc#87177-2 "Guidance for radiofrequency ablation of Chest Pleura"
* $loinc#87178-0 "Guidance for final day of infusion of thrombolytic of Vessel-- W thrombolytic via catheter"
* $loinc#87179-8 "Guidance for fine needle aspiration"
* $loinc#87180-6 "Guidance for dilation of Fallopian tube"
* $loinc#87181-4 "Guidance for embolization of Uterine artery"
* $loinc#87182-2 "Guidance for placement of wire"
* $loinc#87183-0 "Guidance for greater than 2 injections of trigger point of Muscle"
* $loinc#87184-8 "Guidance for percutaneous transluminal angioplasty of arterial anastomosis of Artery"
* $loinc#87185-5 "Guidance for sympathectomy of Nerve"
* $loinc#87186-3 "Guidance for mechanical thrombectomy of central venous catheter lumen obstruction"
* $loinc#87187-1 "Guidance for nerve block of Nerve root"
* $loinc#87188-9 "Guidance for exchange of nephroureteral stent of Kidney and Ureter and Urinary bladder"
* $loinc#87189-7 "Guidance for transurethral removal of nephroureteral stent of Kidney and Ureter and Urinary bladder"
* $loinc#87190-5 "Guidance for percutaneous placement of nephroureteral stent of Kidney and Ureter and Urinary bladder"
* $loinc#87191-3 "Guidance for removal of nephroureteral stent of Kidney and Ureter and Urinary bladder"
* $loinc#87192-1 "Guidance for thrombectomy"
* $loinc#87193-9 "Guidance for initial day infusion of thrombolytic of Artery-- W thrombolytic via catheter"
* $loinc#87194-7 "Guidance for initial mechanical thrombectomy of Vein"
* $loinc#87195-4 "Guidance for initial day infusion of thrombolytic of Vein-- W thrombolytic via catheter"
* $loinc#87196-2 "Guidance for infusion of non-thrombolytic of Vessel"
* $loinc#87197-0 "Guidance for retrieval of foreign body of Vessel"
* $loinc#87198-8 "Guidance for placement of drainage catheter for abscess"
* $loinc#87199-6 "Guidance for substance removal of central venous catheter pericatheter obstruction"
* $loinc#87200-2 "Guidance for placement of stent in Artery"
* $loinc#87201-0 "Guidance for treatment of AV fistula"
* $loinc#87202-8 "Guidance for venous sampling of Vein"
* $loinc#87203-6 "Guidance for transurethral exchange of nephroureteral stent of Kidney and Ureter and Urinary bladder"
* $loinc#87205-1 "Guidance for exchange of non-tunneled CV catheter of Chest"
* $loinc#87206-9 "Guidance for injection of Nerve"
* $loinc#87308-3 "Guidance for transhepatic removal of catheter of Biliary ducts"
* $loinc#87309-1 "Guidance for transhepatic placement of catheter of Biliary ducts"
* $loinc#87310-9 "Guidance for transhepatic exchange of catheter of Biliary ducts"
* $loinc#87311-7 "Guidance for embolization for tumor, ischemia or infarction of Vessel"
* $loinc#87312-5 "Guidance for percutaneous transluminal angioplasty for dialysis of Vein"
* $loinc#88242-3 "Guidance for infusion of non-thrombolytic of Head Arteries"
* $loinc#88243-1 "Guidance for removal of tunneled catheter from Chest Pleura"
* $loinc#88349-6 "Guidance-- during surgery"
* $loinc#88929-5 "Guidance for additional transluminal angioplasty of Vein"
* $loinc#88930-3 "Guidance for dilation of stricture and placement of stent of Biliary ducts-- W contrast IV"
* $loinc#88931-1 "Guidance for embolization for tumor of Hepatic artery-- W embolic agent IA"
* $loinc#88932-9 "Guidance for embolization for tumor of Spinal artery-- W embolic agent IA"
* $loinc#88933-7 "Guidance for embolization of Portal vein-- W embolic agent IV"
* $loinc#88934-5 "Guidance for embolization of Splenic artery-- W embolic agent IA"
* $loinc#88935-2 "Guidance for chemoembolization of Hepatic artery-- W chemotherapy IA+W embolic agent IA"
* $loinc#88936-0 "Guidance for injection of Hepatic artery-- W Tc-99m MAA IA"
* $loinc#88937-8 "Guidance for placement of stent in Biliary ducts"
* $loinc#88938-6 "Guidance for placement of stent in Ureter"
* $loinc#88939-4 "Guidance for radioembolization for tumor of Hepatic artery-- W Yttrium-90 IA"
* $loinc#88940-2 "Guidance for repair of aneurysm of Abdominal Aorta"
* $loinc#88941-0 "Guidance for repair of aneurysm of Thoracic Aorta"
* $loinc#88942-8 "Guidance for repair of endoleak of Artery"
* $loinc#88943-6 "Guidance for venous sampling of Adrenal vein"
