ValueSet: MyCoreRadiologyProcedureMagneticResonanceMyCore
Id: radiology-procedure-mr-my-core
Title: "MY Core Radiology Procedure - Magnetic resonance"
Description: "NATIONAL SELECTION. The magnetic resonance subset of the LOINC/RSNA Radiology Playbook. 876 codes. A modality-scoped pick list; the full catalogue is radiology-procedure-my-core."
* ^url = "https://standards.moh.gov.my/fhir/my-core/ValueSet/radiology-procedure-mr-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^publisher = "Data Team, Digital Health Division, Ministry of Health Malaysia"
* ^copyright = "This value set enumerates LOINC codes. LOINC is copyright Regenstrief Institute, Inc. and the LOINC Committee, and is available at no cost under the LOINC licence. RPID identifiers are from the RSNA Radiology Playbook."
* ^compose.inactive = false
* http://loinc.org#24533-2 "MRA Abdominal vessels W contrast IV"
* http://loinc.org#24538-1 "MR Ankle"
* http://loinc.org#24539-9 "MR Ankle WO and W contrast IV"
* http://loinc.org#24549-8 "MRA Upper extremity vessels W contrast IV"
* http://loinc.org#24556-3 "MR Abdomen"
* http://loinc.org#24557-1 "MR Abdomen WO and W contrast IV"
* http://loinc.org#24582-9 "MR Brachial plexus"
* http://loinc.org#24583-7 "MR Brachial plexus WO and W contrast IV"
* http://loinc.org#24584-5 "MRA Thoracic inlet vessels W contrast IV"
* http://loinc.org#24586-0 "MR Brain W anesthesia"
* http://loinc.org#24587-8 "MR Brain WO and W contrast IV"
* http://loinc.org#24588-6 "MR Brain WO and W contrast IV and W anesthesia"
* http://loinc.org#24589-4 "MR Brain W contrast IV"
* http://loinc.org#24590-2 "MR Brain"
* http://loinc.org#24593-6 "MRA Head vessels W contrast IV"
* http://loinc.org#24629-8 "MR Chest"
* http://loinc.org#24659-5 "MRA Chest vessels W contrast IV"
* http://loinc.org#24660-3 "MRA Thoracic Aorta"
* http://loinc.org#24674-4 "MR Elbow"
* http://loinc.org#24675-1 "MR Elbow WO and W contrast IV"
* http://loinc.org#24687-6 "MR Lower Extremity Joint"
* http://loinc.org#24688-4 "MR Upper extremity"
* http://loinc.org#24694-2 "MR Face WO and W contrast IV"
* http://loinc.org#24702-3 "MR Thigh"
* http://loinc.org#24703-1 "MR Thigh WO and W contrast IV"
* http://loinc.org#24705-6 "MR Finger"
* http://loinc.org#24707-2 "MR Foot"
* http://loinc.org#24710-6 "MR Forearm"
* http://loinc.org#24720-5 "MR Hand"
* http://loinc.org#24735-3 "MR Internal auditory canal and Posterior fossa"
* http://loinc.org#24740-3 "MR Internal auditory canal and Posterior fossa WO and W contrast IV"
* http://loinc.org#24748-6 "MR Heart"
* http://loinc.org#24802-1 "MR Knee"
* http://loinc.org#24803-9 "MR Knee WO and W contrast IV"
* http://loinc.org#24820-3 "MRA Lower leg vessels W contrast IV"
* http://loinc.org#24821-1 "MR Lower leg"
* http://loinc.org#24839-3 "MR Neck"
* http://loinc.org#24840-1 "MR Neck WO and W contrast IV"
* http://loinc.org#24841-9 "MR Neck W contrast IV"
* http://loinc.org#24844-3 "MRA Neck vessels W contrast IV"
* http://loinc.org#24851-8 "MR Orbit - bilateral WO and W contrast IV"
* http://loinc.org#24852-6 "MR Orbit - bilateral W contrast IV"
* http://loinc.org#24867-4 "MR Pelvis"
* http://loinc.org#24872-4 "MR Pelvis and Hip"
* http://loinc.org#24873-2 "MRA Pelvis vessels W contrast IV"
* http://loinc.org#24879-9 "MR Pituitary and Sella turcica WO and W contrast IV"
* http://loinc.org#24880-7 "MR Pituitary and Sella turcica"
* http://loinc.org#24905-2 "MR Shoulder"
* http://loinc.org#24906-0 "MR Shoulder WO and W contrast IV"
* http://loinc.org#24914-4 "MR Sinuses"
* http://loinc.org#24915-1 "MR Sinuses W contrast IV"
* http://loinc.org#24935-9 "MR Cervical spine"
* http://loinc.org#24936-7 "MR Cervical spine W anesthesia"
* http://loinc.org#24937-5 "MR Cervical spine WO and W contrast IV"
* http://loinc.org#24938-3 "MR Cervical spine W contrast IV"
* http://loinc.org#24967-2 "MR Lumbar spine WO and W contrast IV"
* http://loinc.org#24968-0 "MR Lumbar spine"
* http://loinc.org#24977-1 "MR Lumbar spine W anesthesia"
* http://loinc.org#24980-5 "MR Thoracic spine"
* http://loinc.org#24981-3 "MR Thoracic spine WO and W contrast IV"
* http://loinc.org#24982-1 "MR Thoracic spine W contrast IV"
* http://loinc.org#24999-5 "MR Temporomandibular joint"
* http://loinc.org#25003-5 "MRA Thigh vessels W contrast IV"
* http://loinc.org#25033-2 "MR Wrist"
* http://loinc.org#25035-7 "MR Wrist WO and W contrast IV"
* http://loinc.org#25056-3 "MR Unspecified body region"
* http://loinc.org#25057-1 "MR Unspecified body region W conscious sedation"
* http://loinc.org#25058-9 "MRA Unspecified body region W contrast IV"
* http://loinc.org#26181-8 "MRA Thoracic inlet vessels - bilateral W contrast IV"
* http://loinc.org#26182-6 "MRA Thoracic inlet vessels - left W contrast IV"
* http://loinc.org#26183-4 "MRA Thoracic inlet vessels - right W contrast IV"
* http://loinc.org#26187-5 "MR Ankle - bilateral WO and W contrast IV"
* http://loinc.org#26188-3 "MR Ankle - left WO and W contrast IV"
* http://loinc.org#26189-1 "MR Ankle - right WO and W contrast IV"
* http://loinc.org#26190-9 "MR Brachial plexus - bilateral WO and W contrast IV"
* http://loinc.org#26191-7 "MR Brachial plexus - left WO and W contrast IV"
* http://loinc.org#26192-5 "MR Brachial plexus - right WO and W contrast IV"
* http://loinc.org#26193-3 "MR Elbow - bilateral WO and W contrast IV"
* http://loinc.org#26194-1 "MR Elbow - left WO and W contrast IV"
* http://loinc.org#26195-8 "MR Elbow - right WO and W contrast IV"
* http://loinc.org#26196-6 "MR Thigh - bilateral WO and W contrast IV"
* http://loinc.org#26197-4 "MR Thigh - left WO and W contrast IV"
* http://loinc.org#26198-2 "MR Thigh - right WO and W contrast IV"
* http://loinc.org#26199-0 "MR Knee - bilateral WO and W contrast IV"
* http://loinc.org#26200-6 "MR Knee - left WO and W contrast IV"
* http://loinc.org#26201-4 "MR Knee - right WO and W contrast IV"
* http://loinc.org#26202-2 "MR Shoulder - bilateral WO and W contrast IV"
* http://loinc.org#26203-0 "MR Shoulder - left WO and W contrast IV"
* http://loinc.org#26204-8 "MR Shoulder - right WO and W contrast IV"
* http://loinc.org#26205-5 "MR Wrist - bilateral WO and W contrast IV"
* http://loinc.org#26206-3 "MR Wrist - left WO and W contrast IV"
* http://loinc.org#26207-1 "MR Wrist - right WO and W contrast IV"
* http://loinc.org#26208-9 "MR Ankle - bilateral"
* http://loinc.org#26209-7 "MR Ankle - left"
* http://loinc.org#26210-5 "MR Ankle - right"
* http://loinc.org#26211-3 "MR Brachial plexus - bilateral"
* http://loinc.org#26212-1 "MR Brachial plexus - left"
* http://loinc.org#26213-9 "MR Brachial plexus - right"
* http://loinc.org#26220-4 "MR Elbow - bilateral"
* http://loinc.org#26221-2 "MR Elbow - left"
* http://loinc.org#26222-0 "MR Elbow - right"
* http://loinc.org#26227-9 "MR Lower extremity joint - bilateral"
* http://loinc.org#26228-7 "MR Lower extremity joint - left"
* http://loinc.org#26229-5 "MR Lower extremity joint - right"
* http://loinc.org#26232-9 "MR Upper extremity - bilateral"
* http://loinc.org#26233-7 "MR Upper extremity - left"
* http://loinc.org#26234-5 "MR Upper extremity - right"
* http://loinc.org#26235-2 "MR Thigh - bilateral"
* http://loinc.org#26236-0 "MR Thigh - left"
* http://loinc.org#26237-8 "MR Thigh - right"
* http://loinc.org#26238-6 "MR Finger - bilateral"
* http://loinc.org#26239-4 "MR Finger - left"
* http://loinc.org#26240-2 "MR Finger - right"
* http://loinc.org#26241-0 "MR Foot - bilateral"
* http://loinc.org#26242-8 "MR Foot - left"
* http://loinc.org#26243-6 "MR Foot - right"
* http://loinc.org#26244-4 "MR Forearm - bilateral"
* http://loinc.org#26245-1 "MR Forearm - left"
* http://loinc.org#26246-9 "MR Forearm - right"
* http://loinc.org#26247-7 "MR Hand - bilateral"
* http://loinc.org#26248-5 "MR Hand - left"
* http://loinc.org#26249-3 "MR Hand - right"
* http://loinc.org#26256-8 "MR Knee - bilateral"
* http://loinc.org#26257-6 "MR Knee - left"
* http://loinc.org#26258-4 "MR Knee - right"
* http://loinc.org#26259-2 "MR Pelvis and Hip - bilateral"
* http://loinc.org#26260-0 "MR Pelvis and Hip - left"
* http://loinc.org#26261-8 "MR Pelvis and Hip - right"
* http://loinc.org#26266-7 "MR Shoulder - bilateral"
* http://loinc.org#26268-3 "MR Shoulder - left"
* http://loinc.org#26270-9 "MR Shoulder - right"
* http://loinc.org#26277-4 "MR Wrist - bilateral"
* http://loinc.org#26279-0 "MR Wrist - left"
* http://loinc.org#26281-6 "MR Wrist - right"
* http://loinc.org#28576-7 "MR Joint"
* http://loinc.org#30654-8 "MR Brachial plexus WO contrast"
* http://loinc.org#30655-5 "MR Cerebral cisterns"
* http://loinc.org#30656-3 "MR Guidance for stereotactic localization of Brain-- W contrast IV"
* http://loinc.org#30657-1 "MR Brain WO contrast"
* http://loinc.org#30658-9 "MR Internal auditory canal WO contrast"
* http://loinc.org#30659-7 "MR Internal auditory canal WO and W contrast IV"
* http://loinc.org#30660-5 "MR Neck WO contrast"
* http://loinc.org#30661-3 "MR Orbit - bilateral WO contrast"
* http://loinc.org#30662-1 "MR Sinuses WO contrast"
* http://loinc.org#30663-9 "MR Sinuses WO and W contrast IV"
* http://loinc.org#30664-7 "MR Guidance for radiation treatment of Unspecified body region-- W contrast IV"
* http://loinc.org#30665-4 "MR Guidance for radiation treatment of Unspecified body region-- WO contrast"
* http://loinc.org#30666-2 "MR Pituitary and Sella turcica WO contrast"
* http://loinc.org#30667-0 "MR Cervical spine WO contrast"
* http://loinc.org#30668-8 "MR Abdomen WO contrast"
* http://loinc.org#30669-6 "MR Liver WO contrast"
* http://loinc.org#30670-4 "MR Liver WO and W contrast IV"
* http://loinc.org#30671-2 "MR Pelvis and Hip WO contrast"
* http://loinc.org#30672-0 "MR Pelvis and Hip WO and W contrast IV"
* http://loinc.org#30673-8 "MR Pelvis WO contrast"
* http://loinc.org#30674-6 "MR Pelvis WO and W contrast IV"
* http://loinc.org#30675-3 "MR Prostate"
* http://loinc.org#30678-7 "MR Lumbar spine W contrast IV"
* http://loinc.org#30679-5 "MR Lumbar spine WO contrast"
* http://loinc.org#30680-3 "MR Ankle WO contrast"
* http://loinc.org#30681-1 "MR Foot WO contrast"
* http://loinc.org#30682-9 "MR Foot WO and W contrast IV"
* http://loinc.org#30683-7 "MR Forearm WO contrast"
* http://loinc.org#30684-5 "MR Forearm WO and W contrast IV"
* http://loinc.org#30685-2 "MR Hand WO contrast"
* http://loinc.org#30686-0 "MR Hand WO and W contrast IV"
* http://loinc.org#30687-8 "MR Hip WO contrast"
* http://loinc.org#30688-6 "MR Hip WO and W contrast IV"
* http://loinc.org#30689-4 "MR Upper arm WO contrast"
* http://loinc.org#30690-2 "MR Upper arm WO and W contrast IV"
* http://loinc.org#30691-0 "MR Knee WO contrast"
* http://loinc.org#30692-8 "MR Lower extremity"
* http://loinc.org#30693-6 "MR Shoulder WO contrast"
* http://loinc.org#30794-2 "MR Breast"
* http://loinc.org#30795-9 "MR Breast - bilateral"
* http://loinc.org#30796-7 "MR Elbow WO contrast"
* http://loinc.org#30800-7 "MR Guidance for stereotactic localization of Brain-- WO contrast"
* http://loinc.org#30854-4 "MR Cervical and thoracic and lumbar spine WO contrast"
* http://loinc.org#30855-1 "MR Cervical and thoracic and lumbar spine WO and W contrast IV"
* http://loinc.org#30856-9 "MRA Head vessels"
* http://loinc.org#30857-7 "MR Nerves cranial"
* http://loinc.org#30858-5 "MRA Head veins"
* http://loinc.org#30859-3 "MRA Carotid vessels and Neck vessels"
* http://loinc.org#30860-1 "MR Nasopharynx"
* http://loinc.org#30861-9 "MRA Aortic arch and Neck vessels"
* http://loinc.org#30862-7 "MRA Chest vessels"
* http://loinc.org#30864-3 "MRA Abdominal veins and IVC"
* http://loinc.org#30865-0 "MRA Celiac vessels and Superior mesenteric Vessels"
* http://loinc.org#30866-8 "MR Lumbosacral plexus"
* http://loinc.org#30867-6 "MRA Pelvis vessels"
* http://loinc.org#30868-4 "MRA Renal vessels"
* http://loinc.org#30869-2 "MR Lower leg WO contrast"
* http://loinc.org#30870-0 "MR Lower leg WO and W contrast IV"
* http://loinc.org#30871-8 "MRA Femoral vessels"
* http://loinc.org#30872-6 "MRA Foot vessels"
* http://loinc.org#30873-4 "MRA Forearm vessels"
* http://loinc.org#30874-2 "MRA Lower extremity vessels"
* http://loinc.org#30875-9 "MR Upper extremity.joint"
* http://loinc.org#30876-7 "MRA Extremity veins"
* http://loinc.org#30887-4 "MRA Renal vessels W contrast IV"
* http://loinc.org#30888-2 "MRA Tibioperoneal vessels"
* http://loinc.org#35946-3 "MRA Thoracic and abdominal aorta"
* http://loinc.org#35947-1 "MR Thoracic and abdominal aorta"
* http://loinc.org#35949-7 "MR Abdominal Aorta"
* http://loinc.org#35950-5 "MR Thoracic Aorta"
* http://loinc.org#35951-3 "MRA Aortic arch"
* http://loinc.org#35953-9 "MR Face"
* http://loinc.org#35954-7 "MR Breast - left"
* http://loinc.org#35955-4 "MR Breast - right"
* http://loinc.org#35956-2 "MR Internal auditory canal"
* http://loinc.org#35961-2 "MR Clavicle"
* http://loinc.org#35974-5 "MRA Lower extremity vessels - bilateral"
* http://loinc.org#35975-2 "MR Lower extremity - bilateral"
* http://loinc.org#35978-6 "MR Lower extremity - left"
* http://loinc.org#35980-2 "MR Lower extremity - right"
* http://loinc.org#35990-1 "MR Fetal"
* http://loinc.org#36008-1 "MR Wrist and Hand"
* http://loinc.org#36009-9 "MRA Heart"
* http://loinc.org#36013-1 "MR Hip"
* http://loinc.org#36017-2 "MR Hip - bilateral"
* http://loinc.org#36020-6 "MR Hip - left"
* http://loinc.org#36022-2 "MR Hip - right"
* http://loinc.org#36025-5 "MR Upper arm"
* http://loinc.org#36028-9 "MR Upper arm - left"
* http://loinc.org#36030-5 "MR Upper arm - right"
* http://loinc.org#36031-3 "MR Sacroiliac Joint"
* http://loinc.org#36033-9 "MR Kidney"
* http://loinc.org#36034-7 "MR Kidney - bilateral"
* http://loinc.org#36035-4 "MR Kidney - left"
* http://loinc.org#36036-2 "MR Kidney - right"
* http://loinc.org#36045-3 "MR Larynx"
* http://loinc.org#36046-1 "MR Liver"
* http://loinc.org#36052-9 "MR Pancreas"
* http://loinc.org#36053-7 "MR Parathyroid gland"
* http://loinc.org#36056-0 "MR Posterior fossa"
* http://loinc.org#36059-4 "MR Sacrum"
* http://loinc.org#36060-2 "MR Sacrum and Coccyx"
* http://loinc.org#36061-0 "MR Scapula"
* http://loinc.org#36067-7 "MR Spine"
* http://loinc.org#36070-1 "MR Spleen"
* http://loinc.org#36072-7 "MR Sternum"
* http://loinc.org#36073-5 "MR Scrotum and testicle"
* http://loinc.org#36075-0 "MR Lower leg - left"
* http://loinc.org#36076-8 "MR Lower leg - right"
* http://loinc.org#36077-6 "MRA Portal vein"
* http://loinc.org#36078-4 "MRA Renal vein"
* http://loinc.org#36079-2 "MRA Lower extremity veins"
* http://loinc.org#36080-0 "MRA Upper extremity veins"
* http://loinc.org#36081-8 "MRA Vena cava"
* http://loinc.org#36082-6 "MRA Inferior vena cava"
* http://loinc.org#36083-4 "MR Inferior vena cava"
* http://loinc.org#36084-2 "MRA Upper extremity vessels"
* http://loinc.org#36085-9 "MRA Neck vessels"
* http://loinc.org#36088-3 "MR Internal auditory canal limited"
* http://loinc.org#36091-7 "MR Heart limited"
* http://loinc.org#36093-3 "MR Lower Extremity Joint limited"
* http://loinc.org#36094-1 "MR Upper extremity.joint limited"
* http://loinc.org#36096-6 "MR Brain limited W contrast IV"
* http://loinc.org#36100-6 "MR Lumbar spine limited W contrast IV"
* http://loinc.org#36101-4 "MR Thoracic spine limited W contrast IV"
* http://loinc.org#36105-5 "MR Brain limited WO contrast"
* http://loinc.org#36107-1 "MR Lower extremity joint - left limited WO contrast"
* http://loinc.org#36111-3 "MR Lumbar spine limited WO contrast"
* http://loinc.org#36112-1 "MR Thoracic spine limited WO contrast"
* http://loinc.org#36113-9 "MR Kidney W contrast IV"
* http://loinc.org#36114-7 "MR Breast - bilateral dynamic W contrast IV"
* http://loinc.org#36115-4 "MR Ankle Arthrogram"
* http://loinc.org#36116-2 "MR Ankle - left Arthrogram"
* http://loinc.org#36117-0 "MR Ankle - right Arthrogram"
* http://loinc.org#36118-8 "MR Elbow - left Arthrogram"
* http://loinc.org#36119-6 "MR Elbow - right Arthrogram"
* http://loinc.org#36120-4 "MR Hip Arthrogram"
* http://loinc.org#36121-2 "MR Hip - left Arthrogram"
* http://loinc.org#36122-0 "MR Hip - right Arthrogram"
* http://loinc.org#36125-3 "MR Knee Arthrogram"
* http://loinc.org#36126-1 "MR Knee - left Arthrogram"
* http://loinc.org#36127-9 "MR Knee - right Arthrogram"
* http://loinc.org#36129-5 "MR Shoulder Arthrogram"
* http://loinc.org#36130-3 "MR Shoulder - left Arthrogram"
* http://loinc.org#36132-9 "MR Shoulder - right Arthrogram"
* http://loinc.org#36134-5 "MR Abdomen W contrast IV"
* http://loinc.org#36136-0 "MR Ankle W contrast IV"
* http://loinc.org#36138-6 "MR Ankle - left W contrast IV"
* http://loinc.org#36140-2 "MR Ankle - right W contrast IV"
* http://loinc.org#36148-5 "MR Face W contrast IV"
* http://loinc.org#36149-3 "MR Breast W contrast IV"
* http://loinc.org#36150-1 "MR Breast - bilateral W contrast IV"
* http://loinc.org#36151-9 "MR Breast - left W contrast IV"
* http://loinc.org#36152-7 "MR Breast - right W contrast IV"
* http://loinc.org#36155-0 "MR Internal auditory canal W contrast IV"
* http://loinc.org#36156-8 "MR Chest W contrast IV"
* http://loinc.org#36158-4 "MR Elbow W contrast IV"
* http://loinc.org#36160-0 "MR Elbow - left W contrast IV"
* http://loinc.org#36162-6 "MR Elbow - right W contrast IV"
* http://loinc.org#36163-4 "MR Lower extremity - bilateral W contrast IV"
* http://loinc.org#36165-9 "MR Lower extremity - left W contrast IV"
* http://loinc.org#36167-5 "MR Lower extremity - right W contrast IV"
* http://loinc.org#36171-7 "MR Upper extremity - right W contrast IV"
* http://loinc.org#36173-3 "MR Thigh W contrast IV"
* http://loinc.org#36175-8 "MR Thigh - left W contrast IV"
* http://loinc.org#36177-4 "MR Thigh - right W contrast IV"
* http://loinc.org#36179-0 "MR Foot W contrast IV"
* http://loinc.org#36180-8 "MR Foot - bilateral W contrast IV"
* http://loinc.org#36182-4 "MR Foot - left W contrast IV"
* http://loinc.org#36184-0 "MR Foot - right W contrast IV"
* http://loinc.org#36186-5 "MR Forearm W contrast IV"
* http://loinc.org#36188-1 "MR Forearm - left W contrast IV"
* http://loinc.org#36190-7 "MR Forearm - right W contrast IV"
* http://loinc.org#36192-3 "MR Hand W contrast IV"
* http://loinc.org#36194-9 "MR Hand - left W contrast IV"
* http://loinc.org#36196-4 "MR Hand - right W contrast IV"
* http://loinc.org#36197-2 "MR Heart W contrast IV"
* http://loinc.org#36199-8 "MR Hip W contrast IV"
* http://loinc.org#36202-0 "MR Hip - bilateral W contrast IV"
* http://loinc.org#36204-6 "MR Hip - left W contrast IV"
* http://loinc.org#36206-1 "MR Hip - right W contrast IV"
* http://loinc.org#36208-7 "MR Upper arm W contrast IV"
* http://loinc.org#36210-3 "MR Upper arm - left W contrast IV"
* http://loinc.org#36212-9 "MR Upper arm - right W contrast IV"
* http://loinc.org#36213-7 "MR Lower Extremity Joint W contrast IV"
* http://loinc.org#36214-5 "MR Lower extremity joint - left W contrast IV"
* http://loinc.org#36215-2 "MR Lower extremity joint - right W contrast IV"
* http://loinc.org#36216-0 "MR Upper extremity.joint W contrast IV"
* http://loinc.org#36218-6 "MR Sacroiliac Joint W contrast IV"
* http://loinc.org#36219-4 "MR Kidney - bilateral W contrast IV"
* http://loinc.org#36220-2 "MR Kidney - left W contrast IV"
* http://loinc.org#36221-0 "MR Kidney - right W contrast IV"
* http://loinc.org#36223-6 "MR Knee W contrast IV"
* http://loinc.org#36224-4 "MR Knee - bilateral W contrast IV"
* http://loinc.org#36226-9 "MR Knee - left W contrast IV"
* http://loinc.org#36228-5 "MR Knee - right W contrast IV"
* http://loinc.org#36230-1 "MR Larynx W contrast IV"
* http://loinc.org#36231-9 "MR Liver W contrast IV"
* http://loinc.org#36233-5 "MR Nasopharynx W contrast IV"
* http://loinc.org#36236-8 "MR Pancreas W contrast IV"
* http://loinc.org#36237-6 "MR Pelvis W contrast IV"
* http://loinc.org#36238-4 "MR Pituitary and Sella turcica W contrast IV"
* http://loinc.org#36239-2 "MR Brachial plexus W contrast IV"
* http://loinc.org#36240-0 "MR Brachial plexus - left W contrast IV"
* http://loinc.org#36241-8 "MR Brachial plexus - right W contrast IV"
* http://loinc.org#36243-4 "MR Posterior fossa W contrast IV"
* http://loinc.org#36244-2 "MR Prostate W contrast IV"
* http://loinc.org#36246-7 "MR Sacrum W contrast IV"
* http://loinc.org#36247-5 "MR Sacrum and Coccyx W contrast IV"
* http://loinc.org#36248-3 "MR Scapula - left W contrast IV"
* http://loinc.org#36249-1 "MR Scapula - right W contrast IV"
* http://loinc.org#36251-7 "MR Shoulder W contrast IV"
* http://loinc.org#36254-1 "MR Shoulder - right W contrast IV"
* http://loinc.org#36256-6 "MR Spine W contrast IV"
* http://loinc.org#36259-0 "MR Lower leg W contrast IV"
* http://loinc.org#36261-6 "MR Lower leg - left W contrast IV"
* http://loinc.org#36263-2 "MR Lower leg - right W contrast IV"
* http://loinc.org#36265-7 "MR Uterus W contrast IV"
* http://loinc.org#36272-3 "MRA Abdominal Aorta WO and W contrast IV"
* http://loinc.org#36273-1 "MR Abdominal Aorta WO and W contrast IV"
* http://loinc.org#36274-9 "MRA Thoracic Aorta WO and W contrast IV"
* http://loinc.org#36275-6 "MRA Renal artery WO and W contrast IV"
* http://loinc.org#36276-4 "MR Breast WO and W contrast IV"
* http://loinc.org#36277-2 "MR Breast - bilateral WO and W contrast IV"
* http://loinc.org#36278-0 "MR Breast - left WO and W contrast IV"
* http://loinc.org#36279-8 "MR Breast - right WO and W contrast IV"
* http://loinc.org#36283-0 "MR Chest WO and W contrast IV"
* http://loinc.org#36284-8 "MR Chest and Abdomen WO and W contrast IV"
* http://loinc.org#36289-7 "MR Lower extremity - bilateral WO and W contrast IV"
* http://loinc.org#36291-3 "MR Lower extremity - left WO and W contrast IV"
* http://loinc.org#36333-3 "MR Lower extremity - right WO and W contrast IV"
* http://loinc.org#36337-4 "MR Upper extremity - right WO and W contrast IV"
* http://loinc.org#36342-4 "MR Foot - bilateral WO and W contrast IV"
* http://loinc.org#36344-0 "MR Foot - left WO and W contrast IV"
* http://loinc.org#36346-5 "MR Foot - right WO and W contrast IV"
* http://loinc.org#36349-9 "MR Forearm - left WO and W contrast IV"
* http://loinc.org#36351-5 "MR Forearm - right WO and W contrast IV"
* http://loinc.org#36354-9 "MR Hand - left WO and W contrast IV"
* http://loinc.org#36356-4 "MR Hand - right WO and W contrast IV"
* http://loinc.org#36357-2 "MR Heart WO and W contrast IV"
* http://loinc.org#36361-4 "MR Hip - bilateral WO and W contrast IV"
* http://loinc.org#36363-0 "MR Hip - left WO and W contrast IV"
* http://loinc.org#36365-5 "MR Hip - right WO and W contrast IV"
* http://loinc.org#36368-9 "MR Upper arm - left WO and W contrast IV"
* http://loinc.org#36370-5 "MR Upper arm - right WO and W contrast IV"
* http://loinc.org#36371-3 "MR Lower Extremity Joint WO and W contrast IV"
* http://loinc.org#36372-1 "MR Lower extremity joint - left WO and W contrast IV"
* http://loinc.org#36373-9 "MR Lower extremity joint - right WO and W contrast IV"
* http://loinc.org#36374-7 "MR Upper extremity.joint WO and W contrast IV"
* http://loinc.org#36376-2 "MR Sacroiliac Joint WO and W contrast IV"
* http://loinc.org#36378-8 "MR Kidney - bilateral WO and W contrast IV"
* http://loinc.org#36382-0 "MR Larynx WO and W contrast IV"
* http://loinc.org#36384-6 "MR Nasopharynx WO and W contrast IV"
* http://loinc.org#36385-3 "MR Pancreas WO and W contrast IV"
* http://loinc.org#36388-7 "MR Posterior fossa WO and W contrast IV"
* http://loinc.org#36389-5 "MR Prostate WO and W contrast IV"
* http://loinc.org#36391-1 "MR Sacrum WO and W contrast IV"
* http://loinc.org#36392-9 "MR Sacrum and Coccyx WO and W contrast IV"
* http://loinc.org#36393-7 "MR Scapula - left WO and W contrast IV"
* http://loinc.org#36394-5 "MR Scapula - right WO and W contrast IV"
* http://loinc.org#36400-0 "MR Spine WO and W contrast IV"
* http://loinc.org#36404-2 "MR Spleen WO and W contrast IV"
* http://loinc.org#36406-7 "MR Scrotum and testicle WO and W contrast IV"
* http://loinc.org#36407-5 "MR Thyroid gland WO and W contrast IV"
* http://loinc.org#36410-9 "MR Lower leg - left WO and W contrast IV"
* http://loinc.org#36412-5 "MR Lower leg - right WO and W contrast IV"
* http://loinc.org#36413-3 "MR Uterus WO and W contrast IV"
* http://loinc.org#36414-1 "MRA Portal vein WO and W contrast IV"
* http://loinc.org#36415-8 "MRA Renal vein WO and W contrast IV"
* http://loinc.org#36416-6 "MRA Lower extremity veins WO and W contrast IV"
* http://loinc.org#36417-4 "MRA Upper extremity veins WO and W contrast IV"
* http://loinc.org#36418-2 "MR Inferior vena cava WO and W contrast IV"
* http://loinc.org#36419-0 "MR Superior vena cava WO and W contrast IV"
* http://loinc.org#36420-8 "MRA Chest vessels WO and W contrast IV"
* http://loinc.org#36422-4 "MRA Upper extremity vessels WO and W contrast IV"
* http://loinc.org#36423-2 "MRA Neck vessels WO and W contrast IV"
* http://loinc.org#36427-3 "MR Ankle - left WO contrast"
* http://loinc.org#36429-9 "MR Ankle - right WO contrast"
* http://loinc.org#36432-3 "MRA Abdominal Aorta WO contrast"
* http://loinc.org#36433-1 "MRA Thoracic Aorta WO contrast"
* http://loinc.org#36435-6 "MR Face WO contrast"
* http://loinc.org#36436-4 "MR Breast WO contrast"
* http://loinc.org#36437-2 "MR Breast - bilateral WO contrast"
* http://loinc.org#36438-0 "MR Breast - left WO contrast"
* http://loinc.org#36439-8 "MR Breast - right WO contrast"
* http://loinc.org#36442-2 "MR Chest WO contrast"
* http://loinc.org#36446-3 "MR Elbow - left WO contrast"
* http://loinc.org#36448-9 "MR Elbow - right WO contrast"
* http://loinc.org#36450-5 "MRA Lower extremity vessels - bilateral WO contrast"
* http://loinc.org#36451-3 "MR Lower extremity - bilateral WO contrast"
* http://loinc.org#36453-9 "MR Lower extremity - left WO contrast"
* http://loinc.org#36455-4 "MR Lower extremity - right WO contrast"
* http://loinc.org#36459-6 "MR Upper extremity - right WO contrast"
* http://loinc.org#36461-2 "MR Thigh WO contrast"
* http://loinc.org#36463-8 "MR Thigh - left WO contrast"
* http://loinc.org#36465-3 "MR Thigh - right WO contrast"
* http://loinc.org#36467-9 "MR Foot - bilateral WO contrast"
* http://loinc.org#36469-5 "MR Foot - left WO contrast"
* http://loinc.org#36471-1 "MR Foot - right WO contrast"
* http://loinc.org#36474-5 "MR Forearm - left WO contrast"
* http://loinc.org#36476-0 "MR Forearm - right WO contrast"
* http://loinc.org#36479-4 "MR Hand - left WO contrast"
* http://loinc.org#36481-0 "MR Hand - right WO contrast"
* http://loinc.org#36482-8 "MR Heart WO contrast"
* http://loinc.org#36486-9 "MR Hip - bilateral WO contrast"
* http://loinc.org#36488-5 "MR Hip - left WO contrast"
* http://loinc.org#36490-1 "MR Hip - right WO contrast"
* http://loinc.org#36493-5 "MR Upper arm - left WO contrast"
* http://loinc.org#36495-0 "MR Upper arm - right WO contrast"
* http://loinc.org#36496-8 "MR Acromioclavicular Joint WO contrast"
* http://loinc.org#36497-6 "MR Lower Extremity Joint WO contrast"
* http://loinc.org#36498-4 "MR Lower extremity joint - left WO contrast"
* http://loinc.org#36499-2 "MR Lower extremity joint - right WO contrast"
* http://loinc.org#36500-7 "MR Upper extremity.joint WO contrast"
* http://loinc.org#36502-3 "MR Sacroiliac Joint WO contrast"
* http://loinc.org#36504-9 "MR Kidney - bilateral WO contrast"
* http://loinc.org#36506-4 "MR Knee - bilateral WO contrast"
* http://loinc.org#36508-0 "MR Knee - left WO contrast"
* http://loinc.org#36510-6 "MR Knee - right WO contrast"
* http://loinc.org#36513-0 "MR Nasopharynx WO contrast"
* http://loinc.org#36515-5 "MR Pancreas WO contrast"
* http://loinc.org#36516-3 "MR Brachial plexus - right WO contrast"
* http://loinc.org#36518-9 "MR Posterior fossa WO contrast"
* http://loinc.org#36519-7 "MR Prostate WO contrast"
* http://loinc.org#36521-3 "MR Sacrum WO contrast"
* http://loinc.org#36522-1 "MR Sacrum and Coccyx WO contrast"
* http://loinc.org#36523-9 "MR Scapula - left WO contrast"
* http://loinc.org#36525-4 "MR Shoulder - bilateral WO contrast"
* http://loinc.org#36528-8 "MR Shoulder - right WO contrast"
* http://loinc.org#36531-2 "MR Spine WO contrast"
* http://loinc.org#36532-0 "MR Thoracic spine WO contrast"
* http://loinc.org#36533-8 "MR Spleen WO contrast"
* http://loinc.org#36535-3 "MR Scrotum and testicle WO contrast"
* http://loinc.org#36536-1 "MR Thyroid gland WO contrast"
* http://loinc.org#36539-5 "MR Lower leg - left WO contrast"
* http://loinc.org#36541-1 "MR Lower leg - right WO contrast"
* http://loinc.org#36542-9 "MR Uterus WO contrast"
* http://loinc.org#36543-7 "MRA Portal vein WO contrast"
* http://loinc.org#36544-5 "MRA Renal vein WO contrast"
* http://loinc.org#36545-2 "MR Inferior vena cava WO contrast"
* http://loinc.org#36546-0 "MR Superior vena cava WO contrast"
* http://loinc.org#36547-8 "MRA Chest vessels WO contrast"
* http://loinc.org#36548-6 "MRA Upper extremity vessels WO contrast"
* http://loinc.org#36549-4 "MRA Neck vessels WO contrast"
* http://loinc.org#36774-8 "MR Upper extremity joint - left"
* http://loinc.org#36775-5 "MR Upper extremity joint - right"
* http://loinc.org#36777-1 "MR Orbit"
* http://loinc.org#36778-9 "MR Orbit - right"
* http://loinc.org#36779-7 "MR Ovary"
* http://loinc.org#36780-5 "MR Toe"
* http://loinc.org#36781-3 "MRA Abdominal veins"
* http://loinc.org#36782-1 "MRA Subclavian artery"
* http://loinc.org#36783-9 "MRA Veins"
* http://loinc.org#36784-7 "MRA Lower extremity veins - left"
* http://loinc.org#36785-4 "MRA Lower extremity veins - right"
* http://loinc.org#36786-2 "MRA Upper extremity veins - left"
* http://loinc.org#36787-0 "MRA Upper extremity veins - right"
* http://loinc.org#36788-8 "MRA Neck veins"
* http://loinc.org#36789-6 "MRA Pelvis veins"
* http://loinc.org#36790-4 "MRA Inferior vena cava + tributaries"
* http://loinc.org#36791-2 "MRA Abdominal vessels"
* http://loinc.org#36792-0 "MRA Adrenal vessels"
* http://loinc.org#36794-6 "MRA Extremity vessels"
* http://loinc.org#36795-3 "MRA Lower extremity vessels - left"
* http://loinc.org#36796-1 "MRA Lower extremity vessels - right"
* http://loinc.org#36797-9 "MRA Upper extremity vessels - left"
* http://loinc.org#36798-7 "MRA Upper extremity vessels - right"
* http://loinc.org#36799-5 "MRA Knee vessels"
* http://loinc.org#36800-1 "MRA Knee vessels - left"
* http://loinc.org#36801-9 "MRA Knee vessels - right"
* http://loinc.org#36802-7 "MRA Orbit vessels"
* http://loinc.org#36803-5 "MRA Pulmonary vessels"
* http://loinc.org#36804-3 "MRA Renal vessels - bilateral"
* http://loinc.org#36805-0 "MRA Shoulder vessels"
* http://loinc.org#36806-8 "MRA Shoulder vessels - left"
* http://loinc.org#36807-6 "MRA Shoulder vessels - right"
* http://loinc.org#36808-4 "MRA Head vessels limited"
* http://loinc.org#36812-6 "MR Joint Arthrogram"
* http://loinc.org#36817-5 "MR Upper extremity joint - bilateral W contrast IV"
* http://loinc.org#36818-3 "MR Upper extremity joint - left W contrast IV"
* http://loinc.org#36819-1 "MR Upper extremity joint - right W contrast IV"
* http://loinc.org#36820-9 "MR Orbit W contrast IV"
* http://loinc.org#36821-7 "MR Orbit - left W contrast IV"
* http://loinc.org#36822-5 "MR Orbit - right W contrast IV"
* http://loinc.org#36823-3 "MR Ovary W contrast IV"
* http://loinc.org#36826-6 "MRA Head veins W contrast IV"
* http://loinc.org#36827-4 "MRA Neck veins W contrast IV"
* http://loinc.org#36832-4 "MRA Orbit vessels W contrast IV"
* http://loinc.org#36840-7 "MR Upper extremity joint - left WO and W contrast IV"
* http://loinc.org#36841-5 "MR Upper extremity joint - right WO and W contrast IV"
* http://loinc.org#36842-3 "MR Orbit WO and W contrast IV"
* http://loinc.org#36843-1 "MR Orbit - left WO and W contrast IV"
* http://loinc.org#36844-9 "MR Orbit - right WO and W contrast IV"
* http://loinc.org#36845-6 "MR Ovary WO and W contrast IV"
* http://loinc.org#36846-4 "MRA Abdominal veins WO and W contrast IV"
* http://loinc.org#36847-2 "MRA Head veins WO and W contrast IV"
* http://loinc.org#36848-0 "MRA Chest veins WO and W contrast IV"
* http://loinc.org#36849-8 "MRA Lower extremity veins - left WO and W contrast IV"
* http://loinc.org#36850-6 "MRA Lower extremity veins - right WO and W contrast IV"
* http://loinc.org#36851-4 "MRA Upper extremity veins - left WO and W contrast IV"
* http://loinc.org#36852-2 "MRA Upper extremity veins - right WO and W contrast IV"
* http://loinc.org#36853-0 "MRA Neck veins WO and W contrast IV"
* http://loinc.org#36854-8 "MRA Pelvis veins WO and W contrast IV"
* http://loinc.org#36855-5 "MRA Abdominal vessels WO and W contrast IV"
* http://loinc.org#36857-1 "MRA Head vessels WO and W contrast IV"
* http://loinc.org#36858-9 "MRA Lower extremity vessels - left WO and W contrast IV"
* http://loinc.org#36859-7 "MRA Lower extremity vessels - right WO and W contrast IV"
* http://loinc.org#36860-5 "MRA Upper extremity vessels - left WO and W contrast IV"
* http://loinc.org#36861-3 "MRA Upper extremity vessels - right WO and W contrast IV"
* http://loinc.org#36862-1 "MRA Knee vessels - right WO and W contrast IV"
* http://loinc.org#36863-9 "MRA Pelvis vessels WO and W contrast IV"
* http://loinc.org#36864-7 "MRA Shoulder vessels - left WO and W contrast IV"
* http://loinc.org#36865-4 "MRA Shoulder vessels - right WO and W contrast IV"
* http://loinc.org#36869-6 "MR Upper extremity joint - left WO contrast"
* http://loinc.org#36870-4 "MR Upper extremity joint - right WO contrast"
* http://loinc.org#36871-2 "MR Joint WO contrast"
* http://loinc.org#36872-0 "MR Orbit WO contrast"
* http://loinc.org#36873-8 "MR Orbit - left WO contrast"
* http://loinc.org#36874-6 "MR Orbit - right WO contrast"
* http://loinc.org#36875-3 "MR Ovary WO contrast"
* http://loinc.org#36876-1 "MRA Head veins WO contrast"
* http://loinc.org#36877-9 "MRA Neck veins WO contrast"
* http://loinc.org#36878-7 "MRA Abdominal vessels WO contrast"
* http://loinc.org#36879-5 "MRA Ankle vessels WO contrast"
* http://loinc.org#36881-1 "MRA Head vessels WO contrast"
* http://loinc.org#36882-9 "MRA Lower extremity vessels - left WO contrast"
* http://loinc.org#36883-7 "MRA Pelvis vessels WO contrast"
* http://loinc.org#36931-4 "MR Adrenal gland"
* http://loinc.org#36933-0 "MR Salivary gland"
* http://loinc.org#36936-3 "MR Guidance for stereotactic biopsy of Brain"
* http://loinc.org#36942-1 "MR Chest and Abdomen W contrast IV"
* http://loinc.org#36944-7 "MR Biliary ducts and Pancreatic duct WO and W contrast IV"
* http://loinc.org#36951-2 "MR Adrenal gland WO and W contrast IV"
* http://loinc.org#36954-6 "MR Adrenal gland WO contrast"
* http://loinc.org#36956-1 "MR Orbit and Face WO contrast"
* http://loinc.org#37215-1 "MR Brain and Larynx W contrast IV"
* http://loinc.org#37217-7 "MR Brain stem and Cranial nerves"
* http://loinc.org#37218-5 "MR Brain.temporal"
* http://loinc.org#37219-3 "MR Biliary ducts"
* http://loinc.org#37220-1 "MR Biliary ducts and Pancreatic duct"
* http://loinc.org#37222-7 "MR Ankle and Foot"
* http://loinc.org#37224-3 "MR Parotid gland"
* http://loinc.org#37228-4 "MR Temporomandibular joint - bilateral"
* http://loinc.org#37230-0 "MR Temporomandibular joint - left"
* http://loinc.org#37231-8 "MR Temporomandibular joint - right"
* http://loinc.org#37234-2 "MR Mediastinum"
* http://loinc.org#37235-9 "MRA Circle of Willis"
* http://loinc.org#37239-1 "MR Brain and Internal auditory canal W contrast IV"
* http://loinc.org#37241-7 "MR Parotid gland W contrast IV"
* http://loinc.org#37244-1 "MR Temporomandibular joint W contrast IV"
* http://loinc.org#37245-8 "MR Temporomandibular joint - bilateral W contrast IV"
* http://loinc.org#37247-4 "MR Temporomandibular joint - left W contrast IV"
* http://loinc.org#37249-0 "MR Temporomandibular joint - right W contrast IV"
* http://loinc.org#37253-2 "MR Soft tissue W contrast IV"
* http://loinc.org#37254-0 "MRA Circle of Willis W contrast IV"
* http://loinc.org#37265-6 "MR Parotid gland WO and W contrast IV"
* http://loinc.org#37268-0 "MR Temporomandibular joint WO and W contrast IV"
* http://loinc.org#37269-8 "MR Temporomandibular joint - bilateral WO and W contrast IV"
* http://loinc.org#37270-6 "MR Temporomandibular joint - left WO and W contrast IV"
* http://loinc.org#37271-4 "MR Temporomandibular joint - right WO and W contrast IV"
* http://loinc.org#37272-2 "MR Mediastinum WO and W contrast IV"
* http://loinc.org#37277-1 "MRA Spinal veins WO and W contrast IV"
* http://loinc.org#37278-9 "MR Brain and Internal auditory canal WO contrast"
* http://loinc.org#37279-7 "MR Brain and Larynx WO contrast"
* http://loinc.org#37281-3 "MR Parotid gland WO contrast"
* http://loinc.org#37284-7 "MR Temporomandibular joint WO contrast"
* http://loinc.org#37285-4 "MR Temporomandibular joint - bilateral WO contrast"
* http://loinc.org#37286-2 "MR Temporomandibular joint - left WO contrast"
* http://loinc.org#37287-0 "MR Temporomandibular joint - right WO contrast"
* http://loinc.org#37293-8 "MR Soft tissue WO contrast"
* http://loinc.org#37434-8 "MR Heart cine for function"
* http://loinc.org#37435-5 "MR Temporomandibular joint cine"
* http://loinc.org#37437-1 "MR Breast dynamic W contrast IV"
* http://loinc.org#37442-1 "MR spectroscopy Brain"
* http://loinc.org#37443-9 "MR spectroscopy Unspecified body region"
* http://loinc.org#37444-7 "MR Wrist Arthrogram"
* http://loinc.org#37445-4 "MR Wrist - left Arthrogram"
* http://loinc.org#37446-2 "MR Wrist - right Arthrogram"
* http://loinc.org#37448-8 "MR Wrist W contrast IV"
* http://loinc.org#37449-6 "MR Wrist - bilateral W contrast IV"
* http://loinc.org#37451-2 "MR Wrist - left W contrast IV"
* http://loinc.org#37453-8 "MR Wrist - right W contrast IV"
* http://loinc.org#37460-3 "MR Wrist WO contrast"
* http://loinc.org#37462-9 "MR Wrist - bilateral WO contrast"
* http://loinc.org#37464-5 "MR Wrist - left WO contrast"
* http://loinc.org#37466-0 "MR Wrist - right WO contrast"
* http://loinc.org#37497-5 "MRA Spine vessels"
* http://loinc.org#37500-6 "MRA Spine vessels W contrast IV"
* http://loinc.org#37501-4 "MRA Cervical spine vessels W contrast IV"
* http://loinc.org#37502-2 "MRA Lumbar spine vessels W contrast IV"
* http://loinc.org#37503-0 "MRA Thoracic spine vessels W contrast IV"
* http://loinc.org#37505-5 "MRA Spine vessels WO and W contrast IV"
* http://loinc.org#37506-3 "MRA Cervical spine vessels WO and W contrast IV"
* http://loinc.org#37507-1 "MRA Lumbar spine vessels WO and W contrast IV"
* http://loinc.org#37508-9 "MRA Thoracic spine vessels WO and W contrast IV"
* http://loinc.org#37510-5 "MRA Spine vessels WO contrast"
* http://loinc.org#37511-3 "MRA Cervical spine vessels WO contrast"
* http://loinc.org#37512-1 "MRA Thoracic spine vessels WO contrast"
* http://loinc.org#37994-1 "MRA Lumbar spine vessels WO contrast"
* http://loinc.org#38057-6 "MR Breast - left for implant"
* http://loinc.org#38058-4 "MR Breast - right for implant"
* http://loinc.org#38061-8 "MR Spine Cervical and Spine Thoracic and Spine Lumbar and Sacrum W contrast IV"
* http://loinc.org#38062-6 "MR Breast - right for implant WO and W contrast IV"
* http://loinc.org#38064-2 "MR Breast - left for implant WO contrast"
* http://loinc.org#38769-6 "MR Lower extremity joint - right limited WO contrast"
* http://loinc.org#38770-4 "MR Scapula - right WO contrast"
* http://loinc.org#38773-8 "MRA Lower extremity vessels - right WO contrast"
* http://loinc.org#38817-3 "MR Breast - right for implant WO contrast"
* http://loinc.org#38829-8 "MR Upper extremity - left W contrast IV"
* http://loinc.org#38830-6 "MR Shoulder - left W contrast IV"
* http://loinc.org#38831-4 "MR Upper extremity - left WO and W contrast IV"
* http://loinc.org#38832-2 "MR Upper extremity - left WO contrast"
* http://loinc.org#38833-0 "MR Brachial plexus - left WO contrast"
* http://loinc.org#38834-8 "MR Shoulder - left WO contrast"
* http://loinc.org#38836-3 "MR Orbit - left"
* http://loinc.org#38837-1 "MRA Knee vessels - left WO and W contrast IV"
* http://loinc.org#38870-2 "MR Breast - left for implant WO and W contrast IV"
* http://loinc.org#39028-6 "MR Guidance for needle localization of Unspecified body region"
* http://loinc.org#39029-4 "MR Orbit and Face WO and W contrast IV"
* http://loinc.org#39033-6 "MR Upper extremity WO contrast"
* http://loinc.org#39034-4 "MR Upper extremity WO and W contrast IV"
* http://loinc.org#39037-7 "MR Upper extremity W contrast IV"
* http://loinc.org#39038-5 "MR Orbit and Face W contrast IV"
* http://loinc.org#39140-9 "MR Heart cine for blood flow velocity mapping"
* http://loinc.org#39141-7 "MR Bone marrow"
* http://loinc.org#39291-0 "MR Lower extremity WO and W contrast IV"
* http://loinc.org#39292-8 "MR Lower extremity WO contrast"
* http://loinc.org#39293-6 "MR Lower extremity W contrast IV"
* http://loinc.org#42270-9 "MR Cervical spine W flexion and W extension"
* http://loinc.org#42298-0 "MR Unspecified body region WO and W contrast IV"
* http://loinc.org#42299-8 "MR Clavicle WO and W contrast IV"
* http://loinc.org#42300-4 "MR Thyroid gland"
* http://loinc.org#42301-2 "MR Uterus"
* http://loinc.org#42302-0 "MR Clavicle WO contrast"
* http://loinc.org#42303-8 "MR Orbit and Face"
* http://loinc.org#42304-6 "MRA Head vessels and Neck vessels"
* http://loinc.org#42385-5 "MR Brain and Pituitary and Sella turcica"
* http://loinc.org#42386-3 "MR Brain cine for CSF flow"
* http://loinc.org#42387-1 "MR Unspecified body region cine for CSF flow"
* http://loinc.org#42388-9 "MR Prostate Endorectal"
* http://loinc.org#42389-7 "MR Pelvis Endorectal"
* http://loinc.org#42390-5 "MR Endovaginal"
* http://loinc.org#42391-3 "MR Brain and Pituitary and Sella turcica W contrast IV"
* http://loinc.org#42392-1 "MR Brain and Pituitary and Sella turcica WO and W contrast IV"
* http://loinc.org#42393-9 "MR Brain and Pituitary and Sella turcica WO contrast"
* http://loinc.org#42693-2 "MR Urinary bladder and Urethra cine"
* http://loinc.org#42694-0 "MR Clavicle W contrast IV"
* http://loinc.org#42695-7 "MR Lower leg - bilateral W contrast IV"
* http://loinc.org#42696-5 "MR Lower leg - bilateral"
* http://loinc.org#42697-3 "MR Lower leg - bilateral WO and W contrast IV"
* http://loinc.org#42698-1 "MR Cervical and thoracic and lumbar spine"
* http://loinc.org#43448-0 "MR Liver WO and W ferumoxides IV"
* http://loinc.org#43449-8 "MR Ankle - right dynamic W contrast IV"
* http://loinc.org#43450-6 "MR Elbow - left dynamic W contrast IV"
* http://loinc.org#43451-4 "MR Elbow - right dynamic W contrast IV"
* http://loinc.org#43452-2 "MR Knee - left dynamic W contrast IV"
* http://loinc.org#43453-0 "MR Knee - right dynamic W contrast IV"
* http://loinc.org#43454-8 "MR Pulmonary system"
* http://loinc.org#43455-5 "MR Oropharynx"
* http://loinc.org#43456-3 "MR Cervical and thoracic spine WO and W contrast IV"
* http://loinc.org#43457-1 "MR Cervical and thoracic spine"
* http://loinc.org#43458-9 "MRA Orbit vessels WO and W contrast IV"
* http://loinc.org#43504-0 "MR Axilla - left W contrast IV"
* http://loinc.org#43505-7 "MR Axilla - right W contrast IV"
* http://loinc.org#43506-5 "MR Ovary - bilateral"
* http://loinc.org#43507-3 "MR Thymus gland"
* http://loinc.org#43508-1 "MR Axilla - left"
* http://loinc.org#43509-9 "MR Axilla - left WO and W contrast IV"
* http://loinc.org#43510-7 "MR Axilla - right"
* http://loinc.org#43511-5 "MR Axilla - right WO and W contrast IV"
* http://loinc.org#43512-3 "MRA Lower leg vessels - bilateral W contrast IV"
* http://loinc.org#43513-1 "MRA Lower leg vessels - left"
* http://loinc.org#43514-9 "MRA Thigh vessels - left WO contrast"
* http://loinc.org#43515-6 "MRA Thigh vessels - right WO contrast"
* http://loinc.org#43516-4 "MRA Wrist vessels - left WO contrast"
* http://loinc.org#43517-2 "MRA Wrist vessels - right WO contrast"
* http://loinc.org#43528-9 "MR Breast - unilateral WO and W contrast IV"
* http://loinc.org#43530-5 "MR Orbit and Face and Neck"
* http://loinc.org#43555-2 "MR Ankle - left dynamic W contrast IV"
* http://loinc.org#43556-0 "MRA Lower leg vessels - right"
* http://loinc.org#43769-9 "MR Brain and Internal auditory canal WO and W contrast IV"
* http://loinc.org#43772-3 "MR Brain and Internal auditory canal"
* http://loinc.org#43773-1 "MR Kidney WO contrast"
* http://loinc.org#43775-6 "MR Kidney WO and W contrast IV"
* http://loinc.org#44122-0 "MR Guidance for stereotactic localization of Brain-- WO and W contrast IV"
* http://loinc.org#44123-8 "MR Biliary ducts and Pancreatic duct WO contrast"
* http://loinc.org#44124-6 "MR Adrenal gland W contrast IV"
* http://loinc.org#44125-3 "MR Biliary ducts and Pancreatic duct W contrast IV"
* http://loinc.org#44126-1 "MR Heart cine for blood flow velocity mapping W contrast IV"
* http://loinc.org#44127-9 "MR Heart limited cine for function"
* http://loinc.org#44128-7 "MRA Lower extremity vessels WO and W contrast IV"
* http://loinc.org#44129-5 "MRA Lower extremity vessels WO contrast"
* http://loinc.org#44130-3 "MRA Aortic arch WO contrast"
* http://loinc.org#44131-1 "MRA Thoracic and abdominal aorta WO and W contrast IV"
* http://loinc.org#44132-9 "MRA Thoracic and abdominal aorta WO contrast"
* http://loinc.org#44133-7 "MRA Renal vessels WO contrast"
* http://loinc.org#44134-5 "MRA Renal vessels WO and W contrast IV"
* http://loinc.org#44135-2 "MRA Lower extremity vessels - bilateral W contrast IV"
* http://loinc.org#44230-1 "MRA Superior mesenteric vessels WO contrast"
* http://loinc.org#44231-9 "MRA Superior mesenteric vessels WO and W contrast IV"
* http://loinc.org#46299-4 "MR Breast - unilateral"
* http://loinc.org#46310-9 "MR Orbit and Face and Neck WO and W contrast IV"
* http://loinc.org#46319-0 "MR Elbow Arthrogram"
* http://loinc.org#46321-6 "MR Orbit and Face and Neck W contrast IV"
* http://loinc.org#46323-2 "MR Breast - unilateral W contrast IV"
* http://loinc.org#46324-0 "MRA Lower extremity vessels W contrast IV"
* http://loinc.org#46332-3 "MR Orbit and Face and Neck WO contrast"
* http://loinc.org#46333-1 "MR Breast - unilateral WO contrast"
* http://loinc.org#46358-8 "MR Whole body"
* http://loinc.org#46359-6 "MRA Superior mesenteric vessels"
* http://loinc.org#46360-4 "MRA Aortic arch WO and W contrast IV"
* http://loinc.org#48436-0 "MR Lumbar spine W contrast IT"
* http://loinc.org#48439-4 "MR Thoracic spine W contrast IT"
* http://loinc.org#48440-2 "MR Skull base W contrast IV"
* http://loinc.org#48441-0 "MR Thoracic spine WO and W contrast IT"
* http://loinc.org#48444-4 "MR Brain.temporal W contrast IV"
* http://loinc.org#48445-1 "MR Larynx WO contrast"
* http://loinc.org#48447-7 "MR Cervical spine W contrast IT"
* http://loinc.org#48450-1 "MR Cervical spine WO and W contrast IT"
* http://loinc.org#48452-7 "MR Lumbar spine WO and W contrast IT"
* http://loinc.org#48453-5 "MR Brain.temporal WO contrast"
* http://loinc.org#48454-3 "MR Clavicle - right WO and W contrast IV"
* http://loinc.org#48455-0 "MR Clavicle - left WO and W contrast IV"
* http://loinc.org#48456-8 "MR Clavicle - right W contrast IV"
* http://loinc.org#48457-6 "MR Clavicle - left W contrast IV"
* http://loinc.org#48458-4 "MR Clavicle - right WO contrast"
* http://loinc.org#48459-2 "MR Clavicle - left WO contrast"
* http://loinc.org#48460-0 "MR Unspecified body region limited"
* http://loinc.org#48461-8 "MR Neck limited"
* http://loinc.org#48687-8 "MR Skull base WO contrast"
* http://loinc.org#48694-4 "MR Brain.temporal WO and W contrast IV"
* http://loinc.org#49507-7 "MR Unspecified body region W contrast IV"
* http://loinc.org#49565-5 "MRA Thoracic spine vessels"
* http://loinc.org#58740-2 "MRCP Abdomen WO contrast"
* http://loinc.org#58748-5 "Functional MR Brain"
* http://loinc.org#58749-3 "MR Heart W stress and WO and W contrast IV"
* http://loinc.org#58750-1 "MR Heart W stress"
* http://loinc.org#69161-8 "MRA Circle of Willis WO and W contrast IV"
* http://loinc.org#69162-6 "MRA Pulmonary artery - bilateral W contrast IA"
* http://loinc.org#69163-4 "MR Ankle - bilateral W contrast IV"
* http://loinc.org#69164-2 "MR Ankle - bilateral WO contrast"
* http://loinc.org#69165-9 "MR Breast - bilateral for implant"
* http://loinc.org#69166-7 "MR Breast - bilateral for implant WO and W contrast IV"
* http://loinc.org#69167-5 "MR Breast - bilateral for implant W contrast IV"
* http://loinc.org#69168-3 "MR Breast - bilateral for implant WO contrast"
* http://loinc.org#69169-1 "MR Guidance for biopsy of Breast - bilateral"
* http://loinc.org#69170-9 "MR Elbow - bilateral W contrast IV"
* http://loinc.org#69171-7 "MR Elbow - bilateral WO contrast"
* http://loinc.org#69172-5 "MR Femur - bilateral W contrast IV"
* http://loinc.org#69173-3 "MR Femur - bilateral WO contrast"
* http://loinc.org#69174-1 "MR Forearm - bilateral WO and W contrast IV"
* http://loinc.org#69175-8 "MR Forearm - bilateral W contrast IV"
* http://loinc.org#69176-6 "MR Forearm - bilateral WO contrast"
* http://loinc.org#69177-4 "MR Hand - bilateral WO and W contrast IV"
* http://loinc.org#69178-2 "MR Hand - bilateral W contrast IV"
* http://loinc.org#69179-0 "MR Hand - bilateral WO contrast"
* http://loinc.org#69180-8 "MR Upper arm - bilateral"
* http://loinc.org#69181-6 "MR Upper arm - bilateral WO and W contrast IV"
* http://loinc.org#69182-4 "MR Upper arm - bilateral W contrast IV"
* http://loinc.org#69183-2 "MR Upper arm - bilateral WO contrast"
* http://loinc.org#69184-0 "MR Shoulder - bilateral W contrast IV"
* http://loinc.org#69185-7 "MR Lower leg - bilateral WO contrast"
* http://loinc.org#69186-5 "MR Upper extremity - bilateral WO and W contrast IV"
* http://loinc.org#69187-3 "MR Upper extremity - bilateral W contrast IV"
* http://loinc.org#69188-1 "MR Upper extremity - bilateral WO contrast"
* http://loinc.org#69189-9 "MR Breast for implant WO and W contrast IV"
* http://loinc.org#69190-7 "MR Breast for implant W contrast IV"
* http://loinc.org#69191-5 "MR Breast for implant WO contrast"
* http://loinc.org#69192-3 "MR Guidance for aspiration of cyst of Breast"
* http://loinc.org#69193-1 "MR Extremity"
* http://loinc.org#69194-9 "MR Finger WO and W contrast IV"
* http://loinc.org#69195-6 "MR Finger W contrast IV"
* http://loinc.org#69196-4 "MR Finger WO contrast"
* http://loinc.org#69197-2 "MR Guidance for biopsy of Liver"
* http://loinc.org#69198-0 "MR Guidance for biopsy of Muscle"
* http://loinc.org#69199-8 "MR Guidance for biopsy of Pancreas"
* http://loinc.org#69200-4 "MR Guidance for biopsy of Chest Pleura"
* http://loinc.org#69201-2 "MR Guidance for biopsy of Salivary gland"
* http://loinc.org#69202-0 "MR Guidance for biopsy of Thyroid gland"
* http://loinc.org#69203-8 "MR Guidance for biopsy of Breast - left"
* http://loinc.org#69204-6 "MR Finger - left WO and W contrast IV"
* http://loinc.org#69205-3 "MR Finger - left W contrast IV"
* http://loinc.org#69206-1 "MR Finger - left WO contrast"
* http://loinc.org#69207-9 "MR Hip - left Arthrogram WO and W contrast"
* http://loinc.org#69208-7 "MR Shoulder - left Arthrogram WO and W contrast"
* http://loinc.org#69209-5 "MR Wrist - left and Hand - left"
* http://loinc.org#69210-3 "MR Lower Extremity Joint Arthrogram"
* http://loinc.org#69211-1 "MR Nasal bones"
* http://loinc.org#69212-9 "MR Pelvis limited"
* http://loinc.org#69213-7 "MR Guidance for biopsy of Breast - right"
* http://loinc.org#69214-5 "MR Finger - right WO and W contrast IV"
* http://loinc.org#69215-2 "MR Finger - right W contrast IV"
* http://loinc.org#69216-0 "MR Finger - right WO contrast"
* http://loinc.org#69217-8 "MR Hip - right Arthrogram WO and W contrast"
* http://loinc.org#69218-6 "MR Shoulder - right Arthrogram WO and W contrast"
* http://loinc.org#69219-4 "MR Wrist - right and Hand - right"
* http://loinc.org#69220-2 "MR Skull base WO and W contrast IV"
* http://loinc.org#69221-0 "MR Scrotum and testicle W contrast IV"
* http://loinc.org#69222-8 "MR Vena cava"
* http://loinc.org#69223-6 "MR Unspecified body region WO contrast"
* http://loinc.org#72238-9 "MR Toes - right WO and W contrast IV"
* http://loinc.org#72239-7 "MR Toes - right WO contrast"
* http://loinc.org#72240-5 "MR Toes - right W contrast IV"
* http://loinc.org#72241-3 "MR Toes - left WO and W contrast IV"
* http://loinc.org#72242-1 "MR Toes - left WO contrast"
* http://loinc.org#72243-9 "MR Toes - left W contrast IV"
* http://loinc.org#72244-7 "MR Pelvis Endorectal WO and W contrast IV"
* http://loinc.org#72245-4 "MR Pelvis Defecography W contrast PR"
* http://loinc.org#72246-2 "MR Abdomen and Pelvis W contrast PO and WO and W contrast IV"
* http://loinc.org#72247-0 "MR Abdomen and Pelvis W contrast PO and WO contrast IV"
* http://loinc.org#72248-8 "MRCP Abdomen WO and W contrast IV"
* http://loinc.org#80495-5 "MR Mediastinum WO contrast"
* http://loinc.org#80496-3 "MR Unspecified body region 3D post processing"
* http://loinc.org#80497-1 "MR Guidance for needle localization of Breast - right"
* http://loinc.org#80498-9 "MR Guidance for needle localization of Breast - left"
* http://loinc.org#80499-7 "MR Whole body WO and W contrast IV"
* http://loinc.org#80500-2 "MR Heart W stress and WO contrast"
* http://loinc.org#80501-0 "MR Small bowel W contrast PO and WO contrast IV"
* http://loinc.org#80502-8 "MRA Abdominal Aorta and Bilateral Runoff Vessels WO and W contrast IV"
* http://loinc.org#80503-6 "MR Small bowel W contrast PO and WO and W contrast IV"
* http://loinc.org#80504-4 "MR Guidance for biopsy of Unspecified body region"
* http://loinc.org#80505-1 "MR Brain for new diagnosis tumor WO and W contrast IV"
* http://loinc.org#80506-9 "MR Brain for low grade tumor WO and W contrast IV"
* http://loinc.org#80507-7 "MR Brain for high grade tumor WO and W contrast IV"
* http://loinc.org#80508-5 "MR Upper extremity.joint Arthrogram"
* http://loinc.org#80509-3 "MR Guidance for placement of clip in Unspecified body region"
* http://loinc.org#80510-1 "MR Brain for metastasis WO and W contrast IV"
* http://loinc.org#80511-9 "MR Brain for postoperative"
* http://loinc.org#80512-7 "MR Bone marrow WO contrast"
* http://loinc.org#80513-5 "MR Bone marrow W contrast IV"
* http://loinc.org#80514-3 "MR Bone marrow WO and W contrast IV"
* http://loinc.org#80583-8 "Functional MR Brain for motor function"
* http://loinc.org#80584-6 "MR Urethra Endovaginal WO contrast"
* http://loinc.org#80585-3 "MR Pelvis Endorectal W contrast IV"
* http://loinc.org#82123-1 "MR Guidance for radiation treatment of Unspecified body region"
* http://loinc.org#82128-0 "MR Brain and Face WO contrast"
* http://loinc.org#82129-8 "MR Brain and Face WO and W contrast IV"
* http://loinc.org#82130-6 "MR Face and Neck WO contrast"
* http://loinc.org#82131-4 "MR Face and Neck WO and W contrast IV"
* http://loinc.org#85041-2 "MR Unspecified body region 3D printed model"
* http://loinc.org#89284-4 "MR Cervical and thoracic spine W contrast IV"
