ValueSet: MyCoreRadiologyProcedureFluoroscopyAndAngiographyMyCore
Id: radiology-procedure-rf-my-core
Title: "MY Core Radiology Procedure - Fluoroscopy and angiography"
Description: "NATIONAL SELECTION. The fluoroscopy and angiography subset of the LOINC/RSNA Radiology Playbook. 691 codes. A modality-scoped pick list; the full catalogue is radiology-procedure-my-core."
* ^url = "https://standards.moh.gov.my/fhir/my-core/ValueSet/radiology-procedure-rf-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^publisher = "Data Team, Digital Health Division, Ministry of Health Malaysia"
* ^copyright = "This value set enumerates LOINC codes. LOINC is copyright Regenstrief Institute, Inc. and the LOINC Committee, and is available at no cost under the LOINC licence. RPID identifiers are from the RSNA Radiology Playbook."
* ^compose.inactive = false
* $loinc#24543-1 "RFA Guidance for angioplasty of Thoracic and abdominal aorta-- W contrast IA"
* $loinc#24550-6 "RFA Upper extremity veins Views W contrast IV"
* $loinc#24551-4 "RFA AV fistula Views W contrast IA"
* $loinc#24552-2 "RF Stent Views W contrast intra stent"
* $loinc#24553-0 "RFA Guidance for embolectomy of Vessel intracranial-- W contrast IV"
* $loinc#24554-8 "RFA Guidance for embolization of Artery-- W contrast IA"
* $loinc#24555-5 "RFA Guidance for placement of stent in Artery"
* $loinc#24568-8 "RFA Guidance for atherectomy of AV fistula-- W contrast IV"
* $loinc#24569-6 "RFA AV shunt Views W contrast IV"
* $loinc#24570-4 "RF Guidance for removal of calculus from Biliary duct common-- W contrast retrograde intra biliary"
* $loinc#24574-6 "RF Biliary ducts and Gallbladder Views during surgery W contrast biliary duct"
* $loinc#24575-3 "RF Biliary ducts and Gallbladder Views W contrast percutaneous transhepatic"
* $loinc#24576-1 "RFA Urinary bladder arteries Views W contrast IA"
* $loinc#24580-3 "RFA Guidance for angioplasty of Brachiocephalic artery-- W contrast IA"
* $loinc#24581-1 "RFA Subclavian artery and Brachial artery Views W contrast IA"
* $loinc#24614-0 "RFA Guidance for angioplasty of Carotid artery extracranial-- W contrast IA"
* $loinc#24615-7 "RFA Guidance for angioplasty of Carotid artery.intracranial-- W contrast IA"
* $loinc#24617-3 "RFA Carotid arteries Views W contrast IA"
* $loinc#24620-7 "RF Catheter Views for patency check W contrast via catheter"
* $loinc#24621-5 "RF Guidance for percutaneous drainage of Unspecified body region"
* $loinc#24622-3 "RFA Celiac artery Views W contrast IA"
* $loinc#24624-9 "RFA Guidance for change of CV catheter in Vein-- W contrast IV"
* $loinc#24625-6 "RFA Guidance for placement of CV catheter in Vein-- W contrast IV"
* $loinc#24626-4 "RFA Guidance for reposition of CV catheter in Vein-- W contrast IV"
* $loinc#24631-4 "RF Unspecified body region Views for central venous catheter placement check"
* $loinc#24655-3 "RF Chest Image intensifier during surgery"
* $loinc#24656-1 "RF Chest Single view during surgery"
* $loinc#24658-7 "RFA Thoracic and abdominal aorta Views W contrast IA"
* $loinc#24661-1 "RF Pleural space Views W contrast intra pleural space"
* $loinc#24666-0 "RF Colon Views W air and barium contrast PR"
* $loinc#24667-8 "RF Colon Views W contrast PR"
* $loinc#24668-6 "RF Colon Single view for transit Post solid contrast"
* $loinc#24669-4 "RF Colon Views W water soluble contrast PR"
* $loinc#24671-0 "RF Guidance for aspiration of cyst of Unspecified body region"
* $loinc#24678-5 "RF Esophagus Views W contrast PO"
* $loinc#24679-3 "RF Esophagus Views W gastrografin PO"
* $loinc#24680-1 "RF Guidance for dilation of Esophagus"
* $loinc#24681-9 "RF videography Hypopharynx and Esophagus Views"
* $loinc#24682-7 "RF videography Hypopharynx and Esophagus Views W liquid and paste contrast PO during swallowing"
* $loinc#24684-3 "RFA Guidance for embolectomy of Extracranial vessels-- W contrast IA"
* $loinc#24685-0 "RFA Peripheral veins Views W contrast IV"
* $loinc#24698-3 "RFA Guidance for angioplasty of Femoral artery-- W contrast IA"
* $loinc#24699-1 "RFA Femoral artery Runoff W contrast IA"
* $loinc#24715-5 "RF Gastrointestinal tract upper Single view W contrast PO"
* $loinc#24716-3 "RF Guidance for placement of decompression tube in Gastrointestinal tract"
* $loinc#24718-9 "RF Guidance for transjugular biopsy of Liver-- W contrast IV"
* $loinc#24752-8 "RF videography Heart Views"
* $loinc#24755-1 "RFA Guidance for atherectomy of Vein-- W contrast IV"
* $loinc#24756-9 "RFA Guidance for placement of stent in Vein"
* $loinc#24764-3 "RF Hip Arthrogram"
* $loinc#24766-8 "RFA Guidance for angioplasty of Iliac artery-- W contrast IA"
* $loinc#24771-8 "RF Guidance for fluid aspiration of Joint space"
* $loinc#24779-1 "RF Guidance for percutaneous placement of nephrostomy tube of Kidney - bilateral-- W contrast via tube"
* $loinc#24780-9 "RF Kidney - bilateral Views W contrast via nephrostomy tube"
* $loinc#24781-7 "RF Guidance for exchange of nephrostomy tube of Kidney - bilateral-- W contrast"
* $loinc#24782-5 "RF Guidance for percutaneous placement of nephroureteral stent of Kidney - bilateral-- W contrast via stent"
* $loinc#24783-3 "RF Kidney - bilateral Views for urodynamics"
* $loinc#24800-5 "RF Knee Arthrogram"
* $loinc#24827-8 "RFA Lymphatic vessels Views W contrast intra lymphatic"
* $loinc#24832-8 "RFA Guidance for angioplasty of Mesenteric artery-- W contrast IA"
* $loinc#24833-6 "RFA Mesenteric artery Views W contrast IA"
* $loinc#24845-0 "RF Neck Views W contrast intra larynx"
* $loinc#24855-9 "RF videography Oropharynx Views"
* $loinc#24860-9 "RFA Pancreatic artery Views W contrast IA"
* $loinc#24862-5 "RFA Iliac artery Internal Views W contrast IA"
* $loinc#24874-0 "RFA Peripheral arteries Views W contrast IA"
* $loinc#24882-3 "RFA Guidance for percutaneous transluminal angioplasty of Popliteal artery-- W contrast IA"
* $loinc#24887-2 "RFA Guidance for embolectomy of Pulmonary arteries-- W contrast IA"
* $loinc#24893-0 "RF Rectum Single view post contrast PR during defecation"
* $loinc#24894-8 "RF Rectum and Urinary bladder Views W contrast PR and intra bladder during defecation and voiding"
* $loinc#24902-9 "RF Salivary gland Views W contrast intra salivary duct"
* $loinc#24910-2 "RF Shoulder Arthrogram"
* $loinc#24911-0 "RF Shunt Views"
* $loinc#24912-8 "RF Sinus tract Views W contrast intra sinus tract"
* $loinc#24923-5 "RF Small bowel Views W positive contrast via enteroclysis tube"
* $loinc#24924-3 "RF Small bowel Views W contrast PO"
* $loinc#24925-0 "RFA Spinal artery Views W contrast IA"
* $loinc#24927-6 "RF Spine Views W contrast intradisc"
* $loinc#24931-8 "RF Guidance for injection of Spine facet joint"
* $loinc#24947-4 "RF Cervical spine Views W contrast IT"
* $loinc#24973-0 "RF Guidance for fluid aspiration of Spine.lumbar space"
* $loinc#24974-8 "RF Lumbar spine Views W contrast IT"
* $loinc#24985-4 "RF Thoracic spine Views W contrast IT"
* $loinc#24991-2 "RFA Splenic vein and Portal vein Views W contrast IA"
* $loinc#24992-0 "RFA Splenic artery Views W contrast IA"
* $loinc#24995-3 "RF Guidance for placement of tube in Stomach"
* $loinc#24996-1 "RF Guidance for percutaneous replacement of gastrostomy of Stomach"
* $loinc#24998-7 "RF Placement check of gastrostomy tube W contrast via GI tube"
* $loinc#25005-0 "RFA Three vessels Views W contrast"
* $loinc#25014-2 "RFA Two vessels Views W contrast"
* $loinc#25016-7 "RF Urethra Views W contrast intra urethra"
* $loinc#25017-5 "RF Urinary bladder and Urethra Views W contrast intra bladder"
* $loinc#25020-9 "RF Urinary bladder and Urethra Views W contrast retrograde via urethra"
* $loinc#25022-5 "RF Uterus and Fallopian tubes Views W contrast IU"
* $loinc#25023-3 "RFA Vein Views W contrast IV"
* $loinc#25024-1 "RFA Guidance for placement of peripherally-inserted central venous catheter in Vein"
* $loinc#25025-8 "RFA Vena cava Views W contrast IV"
* $loinc#25026-6 "RFA Guidance for placement of venous filter in Inferior vena cava-- W contrast IV"
* $loinc#25028-2 "RFA Guidance for placement of catheter for infusion of thrombolytic in Vessel-- W contrast intravascular"
* $loinc#25029-0 "RFA Guidance for placement of catheter for vasoconstrictor infusion in Vessels"
* $loinc#25030-8 "RFA Abdominal arteries Views W contrast IA"
* $loinc#25034-0 "RF Wrist Arthrogram"
* $loinc#25063-9 "RFA Vessel Single view W contrast IA"
* $loinc#25064-7 "RFA Vessel Views for angioplasty W contrast IA"
* $loinc#25065-4 "RF 15 minutes"
* $loinc#25066-2 "RF 30 minutes"
* $loinc#25067-0 "RF 45 minutes"
* $loinc#25068-8 "RF 1 hour"
* $loinc#25069-6 "RF Guidance for biopsy of Unspecified body region"
* $loinc#25070-4 "RF Unspecified body region Views during surgery"
* $loinc#25073-8 "RFA Guidance for removal of foreign body from Vessel"
* $loinc#25076-1 "RFA Hepatic artery Views W contrast IA"
* $loinc#25077-9 "RFA Guidance for placement of catheter in Hepatic artery-- W contrast IA"
* $loinc#25078-7 "RF Guidance for placement of stent in Intrahepatic portal system"
* $loinc#25079-5 "RFA Renal arteries Views W contrast IA"
* $loinc#25080-3 "RFA Renal vein - bilateral Views for renin sampling W contrast IV"
* $loinc#25081-1 "RFA Guidance for angioplasty of Renal vessel-- W contrast IA"
* $loinc#26064-6 "RFA Vein - bilateral Views W contrast IV"
* $loinc#26065-3 "RFA Vein - left Views W contrast IV"
* $loinc#26066-1 "RFA Vein - right Views W contrast IV"
* $loinc#26067-9 "RF Salivary gland - bilateral Views W contrast intra salivary duct"
* $loinc#26068-7 "RF Salivary gland - left Views W contrast intra salivary duct"
* $loinc#26069-5 "RF Salivary gland - right Views W contrast intra salivary duct"
* $loinc#26070-3 "RF Hip - bilateral Arthrogram"
* $loinc#26071-1 "RF Hip - left Arthrogram"
* $loinc#26072-9 "RF Hip - right Arthrogram"
* $loinc#26073-7 "RF Knee - bilateral Arthrogram"
* $loinc#26074-5 "RF Knee - left Arthrogram"
* $loinc#26075-2 "RF Knee - right Arthrogram"
* $loinc#26076-0 "RF Shoulder - bilateral Arthrogram"
* $loinc#26077-8 "RF Shoulder - left Arthrogram"
* $loinc#26078-6 "RF Shoulder - right Arthrogram"
* $loinc#26079-4 "RFA Carotid arteries - bilateral Views W contrast IA"
* $loinc#26080-2 "RFA Carotid arteries - left Views W contrast IA"
* $loinc#26081-0 "RFA Carotid arteries -right Views W contrast IA"
* $loinc#26082-8 "RFA Spinal artery - bilateral Views W contrast IA"
* $loinc#26083-6 "RFA Spinal artery - left Views W contrast IA"
* $loinc#26084-4 "RFA Spinal artery - right Views W contrast IA"
* $loinc#26178-4 "RFA Femoral artery - bilateral Runoff W contrast IA"
* $loinc#26179-2 "RFA Femoral artery - left Runoff W contrast IA"
* $loinc#26180-0 "RFA Femoral artery - right Runoff W contrast IA"
* $loinc#26295-6 "RFA Guidance for reposition of CV catheter in Vein - bilateral-- W contrast IV"
* $loinc#26296-4 "RFA Guidance for reposition of CV catheter in Vein - left-- W contrast IV"
* $loinc#26297-2 "RFA Guidance for reposition of CV catheter in Vein - right-- W contrast IV"
* $loinc#26298-0 "RFA Guidance for atherectomy of Vein - bilateral-- W contrast IV"
* $loinc#26299-8 "RFA Guidance for atherectomy of Vein - left-- W contrast IV"
* $loinc#26300-4 "RFA Guidance for atherectomy of Vein - right-- W contrast IV"
* $loinc#26301-2 "RFA Guidance for placement of stent in Vein - bilateral"
* $loinc#26302-0 "RFA Guidance for placement of stent in Vein - left"
* $loinc#26303-8 "RFA Guidance for placement of stent in Vein - right"
* $loinc#26304-6 "RFA Guidance for placement of peripherally-inserted central venous catheter in Vein - bilateral"
* $loinc#26305-3 "RFA Guidance for placement of peripherally-inserted central venous catheter in Vein - left"
* $loinc#26306-1 "RFA Guidance for placement of peripherally-inserted central venous catheter in Vein - right"
* $loinc#26310-3 "RFA Guidance for placement of CV catheter in Vein - bilateral-- W contrast IV"
* $loinc#26311-1 "RFA Guidance for placement of CV catheter in Vein - left-- W contrast IV"
* $loinc#26312-9 "RFA Guidance for placement of CV catheter in Vein - right-- W contrast IV"
* $loinc#26322-8 "RF Guidance for injection of Spine facet joint - bilateral"
* $loinc#26323-6 "RF Guidance for injection of Spine facet joint - left"
* $loinc#26324-4 "RF Guidance for injection of Spine facet joint - right"
* $loinc#26331-9 "RFA Guidance for change of CV catheter in Vein - bilateral-- W contrast IV"
* $loinc#26332-7 "RFA Guidance for change of CV catheter in Vein - left-- W contrast IV"
* $loinc#26333-5 "RFA Guidance for change of CV catheter in Vein - right-- W contrast IV"
* $loinc#26370-7 "RFA Guidance for angioplasty of Iliac artery - bilateral-- W contrast IA"
* $loinc#26371-5 "RFA Guidance for angioplasty of Iliac artery - left-- W contrast IA"
* $loinc#26372-3 "RFA Guidance for angioplasty of Iliac artery - right-- W contrast IA"
* $loinc#30628-2 "RF Guidance for removal of foreign body of Unspecified body region"
* $loinc#30629-0 "RF Guidance for procedure of Unspecified body region"
* $loinc#30630-8 "RF videography Cerebral cisterns Views W contrast"
* $loinc#30631-6 "RF Chest Views"
* $loinc#30632-4 "RF Diaphragm for motion"
* $loinc#30633-2 "RF Esophagus Views W barium contrast PO"
* $loinc#30634-0 "RF Guidance for biopsy of Lung"
* $loinc#30636-5 "RF Colon Views for reduction W contrast PR"
* $loinc#30637-3 "RF Guidance for placement of tube in Gastrointestinal tract"
* $loinc#30638-1 "RF Guidance for injection of Hip"
* $loinc#30639-9 "RFA Vessel Single view W contrast"
* $loinc#30640-7 "RFA Guidance for angioplasty of Vein-- W contrast IV"
* $loinc#30641-5 "RFA Guidance for Additional angioplasty of Vein-- W contrast IV"
* $loinc#30642-3 "RF Unspecified body region Single view"
* $loinc#30645-6 "RFA Superior vena cava Views W contrast IV"
* $loinc#30646-4 "RF Guidance for change of tube in Sinus tract-- W contrast"
* $loinc#30647-2 "RF Biliary ducts and Gallbladder Views W contrast via T-tube"
* $loinc#30648-0 "RFA Peripheral artery Views for angioplasty W contrast IA"
* $loinc#30649-8 "RFA Guidance for Additional angioplasty of Peripheral artery-- W contrast IA"
* $loinc#30650-6 "RF Unspecified body region Views for shunt"
* $loinc#30808-0 "RF Cervical and thoracic and lumbar spine Views W contrast IT"
* $loinc#30809-8 "RF Upper gastrointestinal tract and Small bowel Single view W contrast PO"
* $loinc#30810-6 "RF Lacrimal duct Views W contrast intra lacrimal duct"
* $loinc#30811-4 "RF Posterior fossa Views W contrast IT"
* $loinc#30812-2 "RF Guidance for injection of Spine Cervical Facet Joint"
* $loinc#30814-8 "RF Guidance for injection of Spine Thoracic Facet Joint"
* $loinc#30815-5 "RF Guidance for endoscopy of Biliary ducts and Pancreatic duct-- W contrast retrograde"
* $loinc#30816-3 "RFA Peritoneum Views W contrast percutaneous intraperitoneal"
* $loinc#30817-1 "RF Guidance for injection of Spine Lumbar Facet Joint"
* $loinc#30818-9 "RF Guidance for placement of catheter in Fallopian tubes-- transcervical"
* $loinc#30819-7 "RFA Epidural veins Views W contrast IV"
* $loinc#30820-5 "RFA Carotid artery.external - bilateral Views W contrast IA"
* $loinc#30821-3 "RFA Carotid artery.external Views W contrast IA"
* $loinc#30822-1 "RFA Head artery - bilateral and Neck artery - bilateral Views W contrast IA"
* $loinc#30823-9 "RFA Head artery and Neck artery Views W contrast IA"
* $loinc#30824-7 "RFA Intercranial vessel and Neck Vessel Views W contrast"
* $loinc#30825-4 "RFA Orbit veins Views W contrast IV"
* $loinc#30828-8 "RFA Brachial artery Views W contrast IA"
* $loinc#30829-6 "RFA Internal thoracic artery Views W contrast IA"
* $loinc#30830-4 "RFA Pulmonary artery - bilateral Views W contrast IA"
* $loinc#30831-2 "RFA Adrenal artery - bilateral Views W contrast IA"
* $loinc#30832-0 "RFA Adrenal artery Views W contrast IA"
* $loinc#30833-8 "RFA Pelvis arteries Views W contrast IA"
* $loinc#30834-6 "RFA Renal artery - bilateral Views W contrast IA"
* $loinc#30836-1 "RFA Guidance for angioplasty of Visceral artery-- W contrast IA"
* $loinc#30837-9 "RFA Abdominal Aorta Views W contrast IA"
* $loinc#30838-7 "RFA Aorta and Femoral artery - bilateral Runoff W contrast IA"
* $loinc#30839-5 "RFA Abdominal lymphatic vessels Views W contrast intra lymphatic"
* $loinc#30840-3 "RFA Abdominal lymphatic vessels - bilateral Views W contrast intra lymphatic"
* $loinc#30841-1 "RFA Portal vein Views W contrast transhepatic"
* $loinc#30842-9 "RFA Portal vein Views for hemodynamics W contrast transhepatic"
* $loinc#30843-7 "RFA Adrenal vein Views W contrast IV"
* $loinc#30844-5 "RFA Adrenal vein - bilateral Views W contrast IV"
* $loinc#30845-2 "RFA Inferior vena cava Views W contrast IV"
* $loinc#30846-0 "RFA Renal vein - bilateral Views W contrast IV"
* $loinc#30847-8 "RFA Renal vein Views W contrast IV"
* $loinc#30848-6 "RFA Extremity arteries Views W contrast IA"
* $loinc#30849-4 "RFA Extremity arteries - bilateral Views W contrast IA"
* $loinc#30850-2 "RFA Extremity lymphatic vessels Views W contrast intra lymphatic"
* $loinc#30851-0 "RFA Extremity lymphatic vessels - bilateral Views W contrast intra lymphatic"
* $loinc#30852-8 "RFA XXX>Peripheral veins - bilateral Views W contrast IV"
* $loinc#30892-4 "RF Guidance for placement of catheter in Biliary ducts and Pancreatic duct-- W contrast retrograde"
* $loinc#35881-2 "RFA Guidance for angioplasty of Extremity artery-- W contrast IA"
* $loinc#35882-0 "RFA Guidance for angioplasty of Inferior vena cava-- W contrast IV"
* $loinc#35883-8 "RFA Guidance for atherectomy of Thoracic and abdominal aorta-- W contrast IA"
* $loinc#35885-3 "RF Guidance for drainage of abscess of Unspecified body region"
* $loinc#35888-7 "RF Guidance for fluid aspiration of Hip"
* $loinc#35889-5 "RF Guidance for bronchoscopy of Chest"
* $loinc#35890-3 "RF Guidance for biopsy of Abdomen"
* $loinc#35894-5 "RF Guidance for biopsy of Chest"
* $loinc#35899-4 "RF Guidance for biopsy of Kidney"
* $loinc#35900-0 "RF Guidance for percutaneous biopsy of Liver"
* $loinc#35902-6 "RF Guidance for biopsy of Pancreas"
* $loinc#35907-5 "RF Guidance for biopsy of Spleen"
* $loinc#35912-5 "RF Guidance for placement of catheter in Unspecified body region"
* $loinc#35925-7 "RF Guidance for endoscopy of Stomach"
* $loinc#35926-5 "RF Guidance for gastrostomy of Stomach"
* $loinc#35927-3 "RF Guidance for injection of Sacroiliac Joint"
* $loinc#35936-4 "RF Guidance for percutaneous vertebroplasty of Spine"
* $loinc#36640-1 "RF Cervical spine Views"
* $loinc#36760-7 "RFA Guidance for angioplasty of AV shunt-- W contrast"
* $loinc#36761-5 "RF Guidance for balloon dilatation of Biliary ducts-- W contrast"
* $loinc#36762-3 "RFA Guidance for angioplasty of Extremity vessel-- W contrast"
* $loinc#36763-1 "RFA Guidance for angioplasty of Femoral artery and Popliteal artery-- W contrast IA"
* $loinc#36764-9 "RFA Guidance for atherectomy of Femoral vessel and Popliteal artery-- W contrast"
* $loinc#36765-6 "RFA Guidance for atherectomy of Vessel-- W contrast"
* $loinc#36766-4 "RFA Guidance for atherectomy of Coronary arteries-- W contrast IA"
* $loinc#36771-4 "RF Guidance for injection of Joint"
* $loinc#37063-5 "RF Unspecified body region Views for foreign body"
* $loinc#37173-2 "RFA Cerebral artery Views W contrast IA"
* $loinc#37174-0 "RFA Coronary arteries Views W contrast IA"
* $loinc#37175-7 "RFA Femoral artery Views W contrast IA"
* $loinc#37176-5 "RFA Femoral artery and Popliteal artery Views W contrast IA"
* $loinc#37177-3 "RFA Iliac artery - bilateral Views W contrast IA"
* $loinc#37178-1 "RFA Iliac artery - left Views W contrast IA"
* $loinc#37179-9 "RFA Inferior mesenteric artery Views W contrast IA"
* $loinc#37180-7 "RFA Superior mesenteric artery Views W contrast IA"
* $loinc#37181-5 "RFA Popliteal artery - left Views W contrast IA"
* $loinc#37182-3 "RFA Pulmonary arteries - left Views W contrast IA"
* $loinc#37183-1 "RF Ankle Arthrogram"
* $loinc#37184-9 "RF Ankle - bilateral Arthrogram"
* $loinc#37185-6 "RF Ankle - left Arthrogram"
* $loinc#37186-4 "RF Elbow Arthrogram"
* $loinc#37187-2 "RF Elbow - bilateral Arthrogram"
* $loinc#37188-0 "RF Elbow - left Arthrogram"
* $loinc#37189-8 "RF Sacroiliac joint - bilateral Arthrogram"
* $loinc#37190-6 "RF Sacroiliac joint - left Arthrogram"
* $loinc#37191-4 "RF Joint Arthrogram"
* $loinc#37192-2 "RF Cervical spine Views W contrast intradisc"
* $loinc#37193-0 "RF Lumbar spine Views W contrast intradisc"
* $loinc#37195-5 "RFA Cerebral vein Views W contrast IV"
* $loinc#37196-3 "RFA Lower extremity veins - left Views W contrast IV"
* $loinc#37199-7 "RF Chest Views W contrast PO"
* $loinc#37364-7 "RFA Aorta and Femoral artery - left Runoff W contrast IA"
* $loinc#37379-5 "RFA Aortic arch and Upper Extremity artery Views W contrast IA"
* $loinc#37380-3 "RFA Aortic arch and Brachial artery Views W contrast IA"
* $loinc#37381-1 "RFA Carotid artery Views W contrast IA"
* $loinc#37382-9 "RFA Aortic arch and Subclavian artery Views W contrast IA"
* $loinc#37383-7 "RFA Aortic arch and Subclavian artery - left Views W contrast IA"
* $loinc#37384-5 "RFA Vertebral artery Views W contrast IA"
* $loinc#37385-2 "RFA Aortic arch and Vertebral artery - left Views W contrast IA"
* $loinc#37386-0 "RFA Aortic arch and Vertebral artery - right Views W contrast IA"
* $loinc#37387-8 "RFA Adrenal artery - left Views W contrast IA"
* $loinc#37388-6 "RFA Brachial artery - bilateral Views W contrast IA"
* $loinc#37389-4 "RFA Bronchial artery Views W contrast IA"
* $loinc#37390-2 "RFA Carotid artery.external - left Views W contrast IA"
* $loinc#37391-0 "RFA Carotid arteries and Vertebral artery Views W contrast IA"
* $loinc#37392-8 "RFA Carotid arteries and Vertebral artery - bilateral Views W contrast IA"
* $loinc#37393-6 "RFA Carotid arteries and Vertebral artery - left Views W contrast IA"
* $loinc#37394-4 "RFA Celiac artery and Superior mesenteric artery and Inferior mesenteric artery Views W contrast IA"
* $loinc#37395-1 "RFA Extremity arteries - left Views W contrast IA"
* $loinc#37396-9 "RFA Upper extremity arteries - bilateral Views W contrast IA"
* $loinc#37397-7 "RFA Gastric artery Views W contrast IA"
* $loinc#37398-5 "RFA Gastric artery - left Views W contrast IA"
* $loinc#37399-3 "RFA Gastroduodenal artery Views W contrast IA"
* $loinc#37401-7 "RFA Internal maxillary artery Views W contrast IA"
* $loinc#37402-5 "RFA Superior mesenteric artery and Inferior mesenteric artery Views W contrast IA"
* $loinc#37403-3 "RFA Celiac artery and Gastric artery - left and Superior mesenteric artery Views W contrast IA"
* $loinc#37404-1 "RFA Internal pudendal artery Views W contrast IA"
* $loinc#37405-8 "RFA Subclavian artery - bilateral Views W contrast IA"
* $loinc#37406-6 "RFA Subclavian artery - left Views W contrast IA"
* $loinc#37407-4 "RFA Vertebral artery - bilateral Views W contrast IA"
* $loinc#37409-0 "RF Temporomandibular joint - bilateral Arthrogram"
* $loinc#37410-8 "RF Temporomandibular joint - left Arthrogram"
* $loinc#37411-6 "RFA Azygos vein Views W contrast IV"
* $loinc#37412-4 "RFA Extremity veins - bilateral Views W contrast IV"
* $loinc#37413-2 "RFA Extremity veins - left Views W contrast IV"
* $loinc#37414-0 "RFA Lower extremity veins - bilateral Views W contrast IV"
* $loinc#37415-7 "RFA Upper extremity veins - bilateral Views W contrast IV"
* $loinc#37416-5 "RFA Femoral vein Views W contrast IV"
* $loinc#37419-9 "RFA Intraosseous veins Views W contrast IV"
* $loinc#37421-5 "RFA Inferior mesenteric vein Views W contrast IV"
* $loinc#37422-3 "RFA Orbit veins - left Views W contrast IV"
* $loinc#37423-1 "RFA Renal vein - left Views W contrast IV"
* $loinc#37426-4 "RFA Guidance for angioplasty of Lower extremity vein-- W contrast IV"
* $loinc#37427-2 "RF Guidance for injection of Spine"
* $loinc#37487-6 "RFA Lower extremity arteries Views W contrast IA"
* $loinc#37488-4 "RFA Upper extremity arteries - left Views W contrast IA"
* $loinc#37489-2 "RFA Tibioperoneal arteries Views W contrast IA"
* $loinc#37490-0 "RFA Vertebral artery - left Views W contrast IA"
* $loinc#37494-2 "RF Guidance for injection of Tendon"
* $loinc#37565-9 "RF Unspecified body region Views W barium contrast via fistula"
* $loinc#37566-7 "RF Unspecified body region Views W contrast via catheter"
* $loinc#37567-5 "RF Colon Views W contrast via colostomy"
* $loinc#37568-3 "RF Unspecified body region Views W contrast via fistula"
* $loinc#37569-1 "RF Urinary bladder Views W contrast via suprapubic tube"
* $loinc#37570-9 "RF Wrist - bilateral Arthrogram"
* $loinc#37571-7 "RF Wrist - left Arthrogram"
* $loinc#37572-5 "RF Spine Views W contrast IT"
* $loinc#37574-1 "RFA Lower extremity vessels Views W contrast IV"
* $loinc#37576-6 "RF Unspecified body region Views W gastrografin via fistula"
* $loinc#37585-7 "RF Jejunum Views W contrast"
* $loinc#37586-5 "RF Penis Views W contrast intra corpus cavernosum"
* $loinc#37587-3 "RFA Aortic arch and Carotid artery - bilateral and Vertebral artery - bilateral Views W contrast IA"
* $loinc#37588-1 "RFA Common carotid artery - bilateral Views W contrast IA"
* $loinc#37589-9 "RFA Common carotid artery - left Views W contrast IA"
* $loinc#37590-7 "RFA Common carotid artery - right Views W contrast IA"
* $loinc#37591-5 "RFA Aortic arch and External carotid artery - bilateral Views W contrast IA"
* $loinc#37592-3 "RFA Aortic arch and External carotid artery - left Views W contrast IA"
* $loinc#37593-1 "RFA Aortic arch and External carotid artery - right Views W contrast IA"
* $loinc#37594-9 "RFA Carotid artery and Vertebral artery Views W contrast IA"
* $loinc#37595-6 "RFA Coronary arteries Views for graft W contrast IA"
* $loinc#37596-4 "RFA Abdominal and pelvic lymphatic vessels - left Views W contrast intra lymphatic"
* $loinc#37597-2 "RFA Abdominal and pelvic lymphatic vessels Views W contrast intra lymphatic"
* $loinc#37598-0 "RFA Abdominal and pelvic lymphatic vessels - bilateral Views W contrast intra lymphatic"
* $loinc#37599-8 "RFA Extremity lymphatic vessels - left Views W contrast intra lymphatic"
* $loinc#37600-4 "RFA Lymphatic vessels - left Views W contrast intra lymphatic"
* $loinc#37601-2 "RFA Pelvic lymphatic vessels - bilateral Views W contrast intra lymphatic"
* $loinc#37602-0 "RFA Adrenal vein - left Views W contrast IV"
* $loinc#37615-2 "RFA Pelvis vessels Views W contrast"
* $loinc#37640-0 "RFA Renal vessels Views W contrast"
* $loinc#37641-8 "RF Wrist - right Arthrogram"
* $loinc#37647-5 "RF Sacroiliac Joint Arthrogram"
* $loinc#37739-0 "RFA Iliac artery - right Views W contrast IA"
* $loinc#37765-5 "RFA Lower extremity vessels - right Views W contrast"
* $loinc#37767-1 "RFA Lower extremity veins - right Views W contrast IV"
* $loinc#37778-8 "RFA Popliteal artery - right Views W contrast IA"
* $loinc#37779-6 "RFA Right pulmonary arteries Views W contrast IA"
* $loinc#37785-3 "RF Sacroiliac joint - right Arthrogram"
* $loinc#37818-2 "RF Temporomandibular joint - right Arthrogram"
* $loinc#37824-0 "RFA Upper extremity veins - right Views W contrast IV"
* $loinc#37886-9 "RFA Subclavian artery Views W contrast IA"
* $loinc#37887-7 "RF Guidance for fluid aspiration of Pleural space"
* $loinc#37901-6 "RF Temporomandibular joint Arthrogram"
* $loinc#37935-4 "RFA Pelvis arteries and Lower extremity arteries - bilateral Views W contrast IA"
* $loinc#37936-2 "RFA Peripheral vessels Views W contrast"
* $loinc#37939-6 "RFA Adrenal artery - right Views W contrast IA"
* $loinc#37940-4 "RFA Adrenal vein - right Views W contrast IV"
* $loinc#37941-2 "RFA Ankle arteries - right Views W contrast IA"
* $loinc#37942-0 "RF Ankle - right Arthrogram"
* $loinc#37943-8 "RFA Carotid arteries and Vertebral artery - right Views W contrast IA"
* $loinc#37944-6 "RFA Carotid artery and Cerebral artery - right Views W contrast IA"
* $loinc#37945-3 "RFA Carotid artery.cervical - right Views W contrast IA"
* $loinc#37947-9 "RF Elbow - right Arthrogram"
* $loinc#37948-7 "RFA Carotid artery.external - right Views W contrast IA"
* $loinc#37949-5 "RFA Extremity arteries - right Views W contrast IA"
* $loinc#37950-3 "RFA Extremity veins - right Views W contrast IV"
* $loinc#37952-9 "RFA Carotid artery.internal - right Views W contrast IA"
* $loinc#37953-7 "RFA Carotid artery and Cerebral artery internal - right Views W contrast IA"
* $loinc#37958-6 "RFA Orbit veins - right Views W contrast IV"
* $loinc#37959-4 "RFA Renal vein - right Views W contrast IV"
* $loinc#37966-9 "RFA Subclavian artery - right Views W contrast IA"
* $loinc#37967-7 "RFA Upper extremity arteries - right Views W contrast IA"
* $loinc#37968-5 "RFA Vertebral artery - right Views W contrast IA"
* $loinc#37969-3 "RFA Sinus vein Views W contrast IV"
* $loinc#37970-1 "RFA Splenic vein Views W contrast IV"
* $loinc#37971-9 "RFA Subclavian vein Views W contrast IV"
* $loinc#37972-7 "RFA Superior mesenteric vein Views W contrast IV"
* $loinc#37973-5 "RF Testicular vessels Views W contrast"
* $loinc#37976-8 "RFA Upper extremity vessels Views W contrast"
* $loinc#37977-6 "RFA Upper extremity arteries Views W contrast IA"
* $loinc#37979-2 "RFA Uterine artery Views W contrast IA"
* $loinc#37980-0 "RFA Vertebral vessels Views W contrast"
* $loinc#37981-8 "RFA Visceral vessels Views W contrast"
* $loinc#38092-3 "RF Urinary bladder Views W chain and contrast intra bladder"
* $loinc#38094-9 "RF Spinal cavity Views W contrast"
* $loinc#38097-2 "RF Parotid gland - left Views W contrast intra salivary duct"
* $loinc#38098-0 "RF Lacrimal duct - bilateral Views W contrast intra lacrimal duct"
* $loinc#38099-8 "RF Lacrimal duct - left Views W contrast intra lacrimal duct"
* $loinc#38100-4 "RF Urinary bladder and Urethra Views W contrast antegrade"
* $loinc#38103-8 "RF Spine Cervical and Spine Lumbar Views W contrast IT"
* $loinc#38104-6 "RF Spine epidural space Views W contrast IT"
* $loinc#38112-9 "RF Kidney - right Views W contrast via nephrostomy tube"
* $loinc#38116-0 "RF Parotid gland Views W contrast intra salivary duct"
* $loinc#38119-4 "RFA Thoracic artery Views W contrast IA"
* $loinc#38120-2 "RF Thoracic spine Limited Views W contrast IT"
* $loinc#38125-1 "RF Cervical and thoracic and lumbar spine Limited Views W contrast IT"
* $loinc#38153-3 "RF Submandibular gland Views W contrast intra salivary duct"
* $loinc#38154-1 "RF Guidance for superficial biopsy of Bone"
* $loinc#38799-3 "RFA Aorta and Femoral artery - right Runoff W contrast IA"
* $loinc#38800-9 "RFA Aortic arch and Subclavian artery - right Views W contrast IA"
* $loinc#38801-7 "RFA Gastric artery right Views W contrast IA"
* $loinc#38811-6 "RFA Abdominal and pelvic lymphatic vessels - right Views W contrast intra lymphatic"
* $loinc#38812-4 "RFA Extremity lymphatic vessels - right Views W contrast intra lymphatic"
* $loinc#38813-2 "RFA Lymphatic vessels - right Views W contrast intra lymphatic"
* $loinc#38826-4 "RF Parotid gland - right Views W contrast intra salivary duct"
* $loinc#38827-2 "RF Lacrimal duct - right Views W contrast intra lacrimal duct"
* $loinc#38853-8 "RFA Lower extremity vessels - left Views W contrast"
* $loinc#38859-5 "RFA Upper extremity veins - left Views W contrast IV"
* $loinc#38861-1 "RFA Ankle arteries - left Views W contrast IA"
* $loinc#38862-9 "RFA Carotid artery and Cerebral artery - left Views W contrast IA"
* $loinc#38863-7 "RFA Carotid artery.cervical - left Views W contrast IA"
* $loinc#38864-5 "RFA Carotid artery.internal - left Views W contrast IA"
* $loinc#38865-2 "RFA Carotid artery and Cerebral artery internal - left Views W contrast IA"
* $loinc#38872-8 "RF Kidney - left Views W contrast via nephrostomy tube"
* $loinc#39027-8 "RF Guidance for needle localization of Unspecified body region"
* $loinc#39047-6 "RF Hip Single view during surgery"
* $loinc#39055-9 "RFA Extremity veins Views W contrast IV"
* $loinc#39057-5 "RFA Pulmonary arteries Views W contrast IA"
* $loinc#39093-0 "RFA Hepatic veins Views W contrast IV"
* $loinc#39094-8 "RFA Carotid artery.cervical Views W contrast IA"
* $loinc#39095-5 "RFA Carotid artery and Cerebral artery Views W contrast IA"
* $loinc#39096-3 "RFA Hepatic veins Views for hemodynamics W contrast IV"
* $loinc#39097-1 "RFA Carotid artery - bilateral and Cerebral artery - bilateral Views W contrast IA"
* $loinc#39098-9 "RFA Carotid artery.cervical.bilateral Views W contrast IA"
* $loinc#39138-3 "RFA Guidance for vascular access of Vessel"
* $loinc#39144-1 "RF Gastrointestinal tract upper Single view W air contrast PO"
* $loinc#39151-6 "RF Vas deferens Views W contrast intra vas deferens"
* $loinc#39349-6 "RF Kidney - bilateral Views W contrast retrograde"
* $loinc#39361-1 "RF Guidance for drainage of abscess of Liver"
* $loinc#39362-9 "RF Guidance for placement of tube in Chest"
* $loinc#39363-7 "RFA AV fistula Views W contrast retrograde"
* $loinc#39510-3 "RFA Pelvic lymphatic vessels Views W contrast intra lymphatic"
* $loinc#41795-6 "RF Upper gastrointestinal tract and Small bowel Single view W air contrast PO"
* $loinc#41797-2 "RF Colon Limited Views W air and barium contrast PR"
* $loinc#41799-8 "RF Guidance for placement of tube in Liver"
* $loinc#41800-4 "RF Guidance for drainage of Pharynx"
* $loinc#41801-2 "RFA Guidance for placement of catheter in Portal vein-- W contrast IV"
* $loinc#41802-0 "RF Guidance for biopsy of Prostate"
* $loinc#41803-8 "RF Guidance for biopsy of Breast"
* $loinc#42012-5 "RF Gastrointestinal tract upper Views W water soluble contrast PO"
* $loinc#42014-1 "RF Urinary bladder and Urethra Views W contrast"
* $loinc#42017-4 "RF Guidance for percutaneous replacement of cholecystostomy of Abdomen"
* $loinc#42018-2 "RFA Guidance for percutaneous transluminal angioplasty of Vein-- W contrast IA"
* $loinc#42156-0 "RFA Vessels Views W contrast IA"
* $loinc#42157-8 "RFA Extremity vessels Views W contrast IV"
* $loinc#42334-3 "RFA Guidance for injection of Internal thoracic artery - left"
* $loinc#42335-0 "RF Cervical spine Limited Views W contrast IT"
* $loinc#42421-8 "RF Guidance for percutaneous drainage of abscess of Unspecified body region"
* $loinc#42422-6 "RF Guidance for percutaneous drainage of abscess of Breast"
* $loinc#42423-4 "RF Guidance for percutaneous drainage of abscess of Chest"
* $loinc#42459-8 "RF Gastrointestinal tract upper Views W contrast PO"
* $loinc#42460-6 "RF Submandibular gland - left Views W contrast intra salivary duct"
* $loinc#42469-7 "RF Gastrointestinal tract upper and Small bowel and Gallbladder Single view W contrast PO"
* $loinc#42470-5 "RF Gastrointestinal tract upper and Gallbladder Single view W contrast PO"
* $loinc#42681-7 "RF Colon Views W gastrografin PR"
* $loinc#42684-1 "RF Gastrointestinal tract upper Views W gastrografin PO"
* $loinc#42702-1 "RF Greater than 1 hour"
* $loinc#42703-9 "RF Less than 1 hour"
* $loinc#43471-2 "RF 2 hour"
* $loinc#43472-0 "RF 90 minutes"
* $loinc#43473-8 "RF Guidance for endoscopy of Biliary ducts and Pancreatic duct-- 2H post contrast retrograde intrabiliary"
* $loinc#43474-6 "RF Guidance for endoscopy of Biliary ducts and Pancreatic duct-- 15m post contrast retrograde intrabiliary"
* $loinc#43475-3 "RF Guidance for endoscopy of Biliary ducts and Pancreatic duct-- 30M post contrast retrograde intrabiliary"
* $loinc#43476-1 "RF Guidance for endoscopy of Biliary ducts and Pancreatic duct-- 45M post contrast retrograde intrabiliary"
* $loinc#43477-9 "RF Guidance for endoscopy of Biliary ducts and Pancreatic duct-- 1H post contrast retrograde intrabiliary"
* $loinc#43478-7 "RF Guidance for endoscopy of Biliary ducts and Pancreatic duct-- 1.5 hours post contrast retrograde intrabiliary"
* $loinc#43479-5 "RFA Abdominal Aorta Runoff W contrast IA"
* $loinc#43536-2 "RF videography Lumbar spine Views"
* $loinc#43537-0 "RF Guidance for drainage of Unspecified body region"
* $loinc#43538-8 "RF videography Cervical spine Views"
* $loinc#43554-5 "RFA Vessels - left Views W contrast IV"
* $loinc#43558-6 "RF Guidance for change of dialysis catheter in Unspecified body region-- W contrast IV"
* $loinc#43559-4 "RF Urinary bladder and Urethra Views W contrast intra bladder during voiding"
* $loinc#43574-3 "RF Upper gastrointestinal tract and Small bowel Views W barium contrast PO"
* $loinc#43761-6 "RFA Guidance for thrombectomy of Vein - bilateral-- W contrast IV"
* $loinc#43762-4 "RFA Guidance for thrombectomy of Vein - left-- W contrast IV"
* $loinc#43763-2 "RFA Guidance for thrombectomy of Vein-- W contrast IV"
* $loinc#43764-0 "RFA Guidance for thrombectomy of Vein - right-- W contrast IV"
* $loinc#43782-2 "RFA Iliac artery Views W contrast IA"
* $loinc#43783-0 "RFA Renal vein Views for renin sampling W contrast IV"
* $loinc#43788-9 "RF Tube Views for patency W contrast via tube"
* $loinc#43792-1 "RFA Guidance for angioplasty of Tibioperoneal arteries - right-- W contrast IA"
* $loinc#43793-9 "RFA Guidance for angioplasty of Tibioperoneal arteries-- W contrast IA"
* $loinc#43794-7 "RFA Guidance for angioplasty of Tibioperoneal arteries - bilateral-- W contrast IA"
* $loinc#43795-4 "RFA Guidance for angioplasty of Tibioperoneal arteries - left-- W contrast IA"
* $loinc#44213-7 "RF Guidance for endoscopy of Pancreatic duct-- W contrast retrograde"
* $loinc#44214-5 "RF Guidance for endoscopy of Biliary ducts-- W contrast retrograde"
* $loinc#44215-2 "RF Guidance for fine needle aspiration of Unspecified body region"
* $loinc#44216-0 "RF Guidance for fine needle aspiration of Thyroid gland"
* $loinc#44217-8 "RF Guidance for fine needle aspiration of Kidney"
* $loinc#44218-6 "RF Guidance for fine needle aspiration of Pancreas"
* $loinc#44219-4 "RFA Guidance for fine needle aspiration of Lymph node"
* $loinc#44220-2 "RF Guidance for fine needle aspiration of Liver"
* $loinc#44221-0 "RF Guidance for deep aspiration.fine needle of Tissue"
* $loinc#44222-8 "RF Guidance for procedure of Joint space"
* $loinc#44223-6 "RF Guidance for percutaneous drainage of abscess of Ovary"
* $loinc#44224-4 "RF Guidance for placement of tube in Unspecified body region"
* $loinc#44225-1 "RF Guidance for biopsy of Liver-- W contrast IV"
* $loinc#44226-9 "RF Colon Views for reduction W barium contrast PR"
* $loinc#44227-7 "RF Colon Views W barium contrast PR"
* $loinc#44240-0 "RFA Peripheral arteries - bilateral Views W contrast IA"
* $loinc#46294-5 "RF Guidance for percutaneous replacement of drainage tube of Stomach"
* $loinc#46341-4 "RF Abdomen Views"
* $loinc#46357-0 "RF Colon Views W air contrast PR"
* $loinc#46372-9 "RF Guidance for percutaneous drainage of Biliary ducts"
* $loinc#46376-0 "RF Kidney - bilateral Views W contrast antegrade"
* $loinc#46392-7 "RF Guidance for injection of Sinuses"
* $loinc#47986-5 "RFA Lower extremity arteries - left Views W contrast IA"
* $loinc#47987-3 "RFA Lower extremity arteries - right Views W contrast IA"
* $loinc#48435-2 "RF Guidance for injection of Salivary gland - bilateral"
* $loinc#48464-2 "RF Trachea Views"
* $loinc#48465-9 "RF Larynx Views"
* $loinc#48696-9 "RF Submandibular gland - right Views W contrast intra salivary duct"
* $loinc#48698-5 "RF Submandibular gland - bilateral Views W contrast intra salivary duct"
* $loinc#49511-9 "RFA Femoral artery Runoff WO and W contrast IA"
* $loinc#49512-7 "RF Unspecified body region Views"
* $loinc#51391-1 "RFA Guidance for placement of TIPS of Portal vein and Hepatic vein"
* $loinc#58746-9 "RFA AV fistula Views W contrast IV"
* $loinc#62446-0 "RFA Renal artery - left Views W contrast IA"
* $loinc#62447-8 "RFA Renal artery - right Views W contrast IA"
* $loinc#62448-6 "RFA Head artery - left and Neck artery - left Views W contrast IA"
* $loinc#62449-4 "RFA Head artery - right and Neck artery - right Views W contrast IA"
* $loinc#62450-2 "RF Guidance for placement of catheter in Peritoneum"
* $loinc#62491-6 "RFA Guidance for placement of prosthesis in Iliac artery - left-- W contrast IA"
* $loinc#62492-4 "RFA Guidance for placement of prosthesis in Iliac artery - right-- W contrast IA"
* $loinc#64140-7 "RFA Renal vessels - left Views W contrast"
* $loinc#64141-5 "RFA Renal vessels - right Views W contrast"
* $loinc#64995-4 "RFA Internal thoracic artery - left Views W contrast IA"
* $loinc#64998-8 "RF Guidance for placement of catheter in Fallopian tube - left-- transcervical"
* $loinc#64999-6 "RF Guidance for placement of catheter in Fallopian tube - right-- transcervical"
* $loinc#65000-2 "RFA Internal thoracic artery - right Views W contrast IA"
* $loinc#65797-3 "RFA Guidance for placement of stent in Artery - left"
* $loinc#65798-1 "RFA Guidance for placement of stent in Artery - right"
* $loinc#65799-9 "RF Kidney - bilateral Single view for cyst"
* $loinc#65800-5 "RF Kidney - left Single view for cyst"
* $loinc#65801-3 "RF Kidney - right Single view for cyst"
* $loinc#69054-5 "RFA Aortic arch Views W contrast IA"
* $loinc#69066-9 "RFA Abdominal vessels Views W contrast IV"
* $loinc#69067-7 "RFA Guidance for angioplasty of Unspecified body region-- W contrast"
* $loinc#69073-5 "RF Guidance for core needle biopsy of Unspecified body region"
* $loinc#69074-3 "RF Guidance for biopsy of Pelvis"
* $loinc#69075-0 "RF Guidance for biopsy of Salivary gland"
* $loinc#69076-8 "RF guidance for percutaneous biopsy of Bone"
* $loinc#69077-6 "RFA Brachiocephalic artery Views W contrast IA"
* $loinc#69078-4 "RF Guidance for drainage of Chest"
* $loinc#69120-4 "RF Guidance for drainage of abscess of Neck"
* $loinc#69121-2 "RF Guidance for aspiration of cyst of Ovary"
* $loinc#69122-0 "RF Guidance for drainage of abscess of Pancreas"
* $loinc#69123-8 "RF Guidance for drainage of abscess of Pleural space"
* $loinc#69124-6 "RF Guidance for superficial aspiration.fine needle of Tissue"
* $loinc#69127-9 "RF Guidance for biopsy of Chest Pleura"
* $loinc#69129-5 "RF Guidance for biopsy of Thyroid gland"
* $loinc#69133-7 "RF Guidance for drainage of Hip"
* $loinc#69134-5 "RFA Guidance for placement of stent in Iliac artery"
* $loinc#69135-2 "RFA Guidance for atherectomy of Iliac artery-- W contrast"
* $loinc#69226-9 "RF Guidance for biopsy of Muscle"
* $loinc#69241-8 "RF Guidance for percutaneous drainage of abscess of Abdomen"
* $loinc#69242-6 "RF Guidance for percutaneous drainage of abscess of Appendix"
* $loinc#69243-4 "RF Guidance for percutaneous drainage of abscess of Lung"
* $loinc#69244-2 "RF Guidance for percutaneous drainage of abscess of Pelvis"
* $loinc#69248-3 "RFA Guidance for percutaneous transluminal angioplasty of Renal artery-- W contrast IA"
* $loinc#69249-1 "RFA Popliteal artery Views W contrast IA"
* $loinc#69250-9 "RFA Portal vein Views W contrast IV"
* $loinc#69252-5 "RFA Guidance for percutaneous transluminal angioplasty of Pulmonary arteries-- W contrast IA"
* $loinc#69253-3 "RFA Guidance for atherectomy of Renal vessels-- W contrast"
* $loinc#69272-3 "RF Small bowel Views W contrast via ileostomy"
* $loinc#69301-0 "RFA Guidance for percutaneous transluminal angioplasty of Upper extremity vein-- W contrast IV"
* $loinc#69306-9 "RF Guidance for aspiration of cyst of Bone"
* $loinc#70918-8 "RF Guidance for injection of Cervical spine"
* $loinc#70919-6 "RF Guidance for injection of Lumbar spine"
* $loinc#70920-4 "RF Guidance for injection of Thoracic spine"
* $loinc#70923-8 "RF Guidance for percutaneous vertebroplasty of Cervical spine"
* $loinc#70924-6 "RF Guidance for percutaneous vertebroplasty of Lumbar spine"
* $loinc#70925-3 "RF Guidance for percutaneous vertebroplasty of Thoracic spine"
* $loinc#70933-7 "RF Thoracic spine Views W contrast intradisc"
* $loinc#72538-2 "RFA Guidance for removal of peripherally-inserted central venous catheter of Vein"
* $loinc#72539-0 "RF Guidance for denervation of Peripheral nerve"
* $loinc#72540-8 "RF Guidance for denervation of Spine facet joint"
* $loinc#72541-6 "RF Guidance for denervation of Spine Cervical Facet Joint"
* $loinc#72542-4 "RF Guidance for denervation of Spine Lumbar Facet Joint"
* $loinc#72543-2 "RF Guidance for denervation of Thoracic spine intercostal nerve"
* $loinc#72544-0 "RF Guidance for percutaneous device removal of nephrostomy tube of Kidney - bilateral-- W contrast"
* $loinc#72545-7 "RF Guidance for percutaneous replacement of drainage tube of Biliary ducts and Gallbladder"
* $loinc#72546-5 "RFA Guidance for removal of CV catheter lumen obstruction of Vein"
* $loinc#72547-3 "RFA Guidance for removal of CV catheter pericatheter obstruction of Vein"
* $loinc#72548-1 "RFA Guidance for removal of CV catheter of Vein-- W contrast IV"
* $loinc#72549-9 "RF Guidance for removal of tunneled CV catheter from Vein"
* $loinc#72550-7 "RFA Guidance for repair of CV catheter with port or pump of Vein"
* $loinc#72551-5 "RFA Guidance for repair of CV catheter without port or pump of Vein"
* $loinc#72552-3 "RF Guidance for kyphoplasty of Lumbar spine"
* $loinc#72553-1 "RF Guidance for kyphoplasty of Thoracic spine"
* $loinc#72554-9 "RF Guidance for trigger point injection of Muscle"
* $loinc#75669-2 "RF Guidance for biopsy of Bone marrow"
* $loinc#75670-0 "RF Spine.lumbar epidural space Views W contrast epidural"
* $loinc#75747-6 "RF Guidance for drainage of abscess of Pleural space - bilateral"
* $loinc#75749-2 "RF Guidance for fluid aspiration of Intervertebral disc"
* $loinc#75750-0 "RF Guidance for biopsy of Intervertebral disc"
* $loinc#75751-8 "RF Guidance for drainage of abscess of Pleural space - left"
* $loinc#75816-9 "RF Spine.thoracic epidural space Views W contrast epidural"
* $loinc#75817-7 "RF Guidance for drainage of abscess of Pleural space - right"
* $loinc#75853-2 "RF Vagina Views W contrast VG"
* $loinc#86372-0 "RF Kidney and Ureter and Urinary bladder Views W contrast IV"
* $loinc#86373-8 "RF AV fistula Views W contrast via additional puncture"
* $loinc#86374-6 "RFA Pedal lymphatic vessels - bilateral Views W contrast intra lymphatic"
* $loinc#86375-3 "RFA Pedal lymphatic vessels - unilateral Views W contrast intra lymphatic"
* $loinc#86376-1 "RF Biliary ducts Views W contrast via existing catheter"
* $loinc#86377-9 "RF Guidance for advancement of feeding tube of Gastrointestinal tract"
* $loinc#86378-7 "RF Gastrointestinal tract Views for fistula"
* $loinc#86379-5 "RF Small bowel Views for loop diversion"
* $loinc#86380-3 "RF Kidney and Ureter and Urinary bladder Views for fistula"
* $loinc#86381-1 "RF Colon Screening W air and barium contrast PR"
* $loinc#86382-9 "RF Biliary ducts Limited Views during surgery"
* $loinc#86383-7 "RF Biliary ducts Views W contrast IV"
* $loinc#86384-5 "RF Gallbladder Views W contrast and fatty meal PO"
* $loinc#86385-2 "RF Gallbladder Views W contrast PO"
* $loinc#86386-0 "RF Gastrointestinal tract upper Views W barium contrast PO"
* $loinc#86387-8 "RF Kidney and Ureter and Urinary bladder Views W contrast antegrade"
* $loinc#86388-6 "RF Kidney and Ureter and Urinary bladder Views W contrast retrograde"
* $loinc#86389-4 "RF Kidney and Ureter and Urinary bladder Views during surgery W contrast retrograde"
* $loinc#86390-2 "RF Kidney and Ureter and Urinary bladder Views W contrast via nephrostomy tube"
* $loinc#86391-0 "RF AV fistula Views W contrast via existing catheter"
* $loinc#86392-8 "RF Kidney and Ureter and Urinary bladder Limited Views W contrast IV"
* $loinc#86393-6 "RF Kidney - bilateral and Ureter - bilateral and Urinary bladder Views W contrast retrograde"
* $loinc#86394-4 "RFA Thoracic Aorta Views W contrast IA"
* $loinc#86395-1 "RF videography Hypopharynx and Esophagus Views for swallowing function W speech and W barium contrast PO"
* $loinc#86396-9 "RFA Extremity veins - unilateral Views W contrast IV"
* $loinc#86397-7 "RF Guidance for aspiration and placement of suprapubic catheter of Urinary bladder"
* $loinc#86398-5 "RF Cerebral cisterns Views W contrast IT"
* $loinc#86399-3 "RF Guidance for Views and Guidance for injection of non-vascular shunt of Unspecified body region"
* $loinc#86400-9 "RF Guidance for placement of needle in Unspecified body region"
* $loinc#86401-7 "RF Urinary bladder Views W contrast intra bladder"
* $loinc#86402-5 "RF Shoulder Arthrogram limited"
* $loinc#86403-3 "RF Guidance for placement of catheter in Fallopian tube"
* $loinc#86404-1 "RF Guidance for fluid aspiration of Urinary bladder"
* $loinc#86405-8 "RF Guidance for exchange of tube of Unspecified body region"
* $loinc#86406-6 "RF Unspecified body region Less than 1 hour Views during surgery"
* $loinc#86407-4 "RF Guidance of Unspecified body region"
* $loinc#86408-2 "RF Pelvis Views for urinary pouch"
* $loinc#86409-0 "RF Rectum Views for rectal dysfunction W barium contrast PR"
* $loinc#86410-8 "RF Pharynx and Cervical esophagus Views W barium contrast PO"
* $loinc#86411-6 "RF Posterior fossa - bilateral Views W contrast IT"
* $loinc#86412-4 "RFA Pedal lymphatic vessels Views W contrast intra lymphatic"
* $loinc#86413-2 "RF Guidance for placement of long feeding tube in Gastrointestinal tract"
* $loinc#86414-0 "RFA Renal arteries - unilateral Views W contrast IA"
* $loinc#86415-7 "RFA Renal vein - unilateral Views W contrast IV"
* $loinc#86417-3 "RFA Cerebral arteries Bilateral Views W contrast IA"
* $loinc#86418-1 "RFA Pulmonary arteries - unilateral Views W contrast IA"
* $loinc#86419-9 "RFA Visceral arteries Views W contrast IA"
* $loinc#86420-7 "RF Gastrointestinal tract upper Views W air contrast PO and W barium contrast PO"
* $loinc#86425-6 "RF Guidance for manometry of Kidney"
* $loinc#86426-4 "RFA Jugular vein - unilateral Views W contrast IV"
* $loinc#86427-2 "RF Upper gastrointestinal tract and Small bowel Views W air contrast PO and W barium contrast PO"
* $loinc#86428-0 "RFA Extremity arteries - unilateral Views W contrast IA"
* $loinc#86429-8 "RFA Cerebral arteries - unilateral Views W contrast IA"
* $loinc#86430-6 "RF Posterior fossa - unilateral Views W contrast IT"
* $loinc#86431-4 "RFA Cerebral arteries - bilateral and Cervical arteries - bilateral Views W contrast IA"
* $loinc#86432-2 "RFA Cerebral arteries - unilateral and Cervical arteries - unilateral Views W contrast IA"
* $loinc#86433-0 "RFA Lumbar spine intercostal arteries Views W contrast IA"
* $loinc#86434-8 "RFA Carotid arteries - unilateral Views W contrast IA"
* $loinc#86435-5 "RFA Jugular vein - bilateral Views W contrast IV"
* $loinc#86436-3 "RF Guidance for treatment of Fistula-- W contrast intra fistula"
* $loinc#86437-1 "RF Fistula Diagnostic W contrast intra fistula"
* $loinc#86438-9 "RF Guidance for check of feeding tube of Gastrointestinal tract upper"
* $loinc#86439-7 "RF Cerebral sinuses Views W contrast IV"
* $loinc#86440-5 "RF Seminal vesicle Views W contrast intra seminal vesicle"
* $loinc#86441-3 "RF Guidance for manometry of Kidney and Ureter and Urinary bladder"
* $loinc#86442-1 "RFA Vertebral artery - unilateral Views W contrast IA"
* $loinc#86443-9 "RF Ureter Views W contrast intra ureter"
* $loinc#86460-3 "RFA Spine vessel Views"
* $loinc#86461-1 "RFA Adrenal vessel Views"
* $loinc#86464-5 "RFA Guidance for repair of aneurysm or dissection of Infrarenal aorta"
* $loinc#88831-3 "RF Kidney - right and Ureter Views W contrast retrograde intra ureter"
* $loinc#88832-1 "RF Kidney - left and Ureter Views W contrast retrograde intra ureter"
* $loinc#88833-9 "RF Kidney - bilateral and Ureter Views W contrast retrograde intra ureter"
* $loinc#88834-7 "RF Guidance for dilation of nephrostomy tract, ureter, or urethra"
