ValueSet: MyCoreRadiologyProcedureNuclearMedicineAndPetMyCore
Id: radiology-procedure-nm-my-core
Title: "MY Core Radiology Procedure - Nuclear medicine and PET"
Description: "NATIONAL SELECTION. The nuclear medicine and pet subset of the LOINC/RSNA Radiology Playbook. 521 codes. A modality-scoped pick list; the full catalogue is radiology-procedure-my-core."
* ^url = "https://standards.moh.gov.my/fhir/my-core/ValueSet/radiology-procedure-nm-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^publisher = "Data Team, Digital Health Division, Ministry of Health Malaysia"
* ^copyright = "This value set enumerates LOINC codes. LOINC is copyright Regenstrief Institute, Inc. and the LOINC Committee, and is available at no cost under the LOINC licence. RPID identifiers are from the RSNA Radiology Playbook."
* ^compose.inactive = false
* http://loinc.org#24571-2 "NM Biliary ducts and Gallbladder Views for patency of biliary structures and ejection fraction W sincalide and W radionuclide IV"
* http://loinc.org#24572-0 "NM Biliary ducts and Gallbladder Views for patency of biliary structures W Tc-99m IV"
* http://loinc.org#24578-7 "SPECT Bones"
* http://loinc.org#24591-0 "NM Brain Brain death protocol Views W Tc-99m HMPAO IV"
* http://loinc.org#24663-7 "NM Cerebral cisterns Views W radionuclide IT"
* http://loinc.org#24683-5 "NM Esophagus+Stomach Views W Tc-99m SC PO"
* http://loinc.org#24714-8 "NM Gastrointestinal tract Views for gastrointestinal bleeding W Tc-99m tagged RBC IV"
* http://loinc.org#24730-4 "NM Brain Views"
* http://loinc.org#24750-2 "NM Heart Views at rest and W Tl-201 IV"
* http://loinc.org#24751-0 "NM Parathyroid gland Views W TI-201 subtraction Tc-99m IV"
* http://loinc.org#24770-0 "NM Joint Views W In-111 intrajoint"
* http://loinc.org#24773-4 "NM Kidney Views W radionuclide transplant scan"
* http://loinc.org#24776-7 "NM Kidney Views"
* http://loinc.org#24804-7 "NM Knee Views"
* http://loinc.org#24817-9 "SPECT Liver W Tc-99m IV"
* http://loinc.org#24824-5 "NM Lung Portable Views"
* http://loinc.org#24826-0 "NM Lymphatic vessels Views W radionuclide intra lymphatic"
* http://loinc.org#24831-0 "NM Small bowel Views for Meckel's diverticulum W Tc-99m M04 IV"
* http://loinc.org#24876-5 "NM Head to Pelvis Views for shunt patency W Tc-99m DTPA IT"
* http://loinc.org#24888-0 "NM Pulmonary system Ventilation and Perfusion W Xe-133 IH and W Tc-99m MAA IV"
* http://loinc.org#24997-9 "NM Stomach Views for gastric emptying solid phase W Tc-99m SC PO"
* http://loinc.org#25001-9 "NM Scrotum and testicle Views W Tc-99m pertechnetate IV"
* http://loinc.org#25007-6 "NM Thyroid gland Views W I-131 IV"
* http://loinc.org#25008-4 "NM Thyroid gland Views and Views uptake W I-131 IV"
* http://loinc.org#25018-3 "NM Urinary bladder Views"
* http://loinc.org#25031-6 "NM Bone Views"
* http://loinc.org#25032-4 "NM Bone Views W In-111 tagged WBC IV"
* http://loinc.org#26088-5 "NM Knee - bilateral Views"
* http://loinc.org#26089-3 "NM Knee - left Views"
* http://loinc.org#26090-1 "NM Knee - right Views"
* http://loinc.org#26091-9 "NM Scrotum and Testicle - bilateral Views W Tc-99m pertechnetate IV"
* http://loinc.org#26092-7 "NM Scrotum and Testicle - left Views W Tc-99m pertechnetate IV"
* http://loinc.org#26093-5 "NM Scrotum and Testicle - right Views W Tc-99m pertechnetate IV"
* http://loinc.org#30694-4 "NM Thyroid gland and uptake single view"
* http://loinc.org#30695-1 "NM Thyroid gland Views"
* http://loinc.org#30696-9 "NM Scrotum and testicle Views"
* http://loinc.org#30697-7 "NM Pulmonary system Ventilation and Perfusion"
* http://loinc.org#30877-5 "NM Kidney+Renal vessels Views"
* http://loinc.org#39619-2 "NM Pulmonary system Views"
* http://loinc.org#39620-0 "NM Guidance for abscess localization limited of Unspecified body region"
* http://loinc.org#39621-8 "SPECT Guidance for abscess localization of Unspecified body region"
* http://loinc.org#39622-6 "SPECT Guidance for abscess localization of Whole body"
* http://loinc.org#39623-4 "NM Guidance for abscess localization of Whole body"
* http://loinc.org#39624-2 "NM Adrenal gland Views W I-131 NP59 IV"
* http://loinc.org#39625-9 "NM Artery Views W Tc-99m DTPA IA"
* http://loinc.org#39626-7 "NM Vein - bilateral Views"
* http://loinc.org#39627-5 "NM Bone Limited Views"
* http://loinc.org#39628-3 "SPECT Small bowel for Meckel's diverticulum"
* http://loinc.org#39629-1 "NM Small bowel Views for Meckel's diverticulum"
* http://loinc.org#39630-9 "NM Brain Views W Tc-99m HMPAO IV"
* http://loinc.org#39631-7 "SPECT Brain W Tc-99m HMPAO IV"
* http://loinc.org#39632-5 "SPECT Brain"
* http://loinc.org#39634-1 "NM Brain Limited Views"
* http://loinc.org#39635-8 "NM Brain Views W Tl-201 IV"
* http://loinc.org#39636-6 "NM Brain Views for blood flow"
* http://loinc.org#39637-4 "SPECT Brain for blood flow"
* http://loinc.org#39638-2 "SPECT Brain W I-123 IV"
* http://loinc.org#39639-0 "SPECT Brain W Tl-201 IV"
* http://loinc.org#39640-8 "SPECT Brain W Tc-99m DTPA IV"
* http://loinc.org#39641-6 "SPECT Brain W Tc-99m glucoheptonate IV"
* http://loinc.org#39642-4 "NM Brain Views W Tc-99m glucoheptonate IV"
* http://loinc.org#39643-2 "NM Brain veins Views"
* http://loinc.org#39644-0 "SPECT Breast"
* http://loinc.org#39645-7 "NM Breast Limited Views"
* http://loinc.org#39646-5 "NM Breast Views"
* http://loinc.org#39647-3 "SPECT Heart W Tc-99m Tetrofosmin IV"
* http://loinc.org#39648-1 "SPECT Heart W dipyridamole IV"
* http://loinc.org#39649-9 "SPECT Heart"
* http://loinc.org#39650-7 "NM Heart Views"
* http://loinc.org#39651-5 "NM Heart Views W adenosine and W Tl-201 IV"
* http://loinc.org#39652-3 "NM Heart Views W dobutamine and W Tl-201 IV"
* http://loinc.org#39653-1 "NM Heart Views for infarct"
* http://loinc.org#39654-9 "SPECT Heart for infarct W Tc-99m PYP IV"
* http://loinc.org#39655-6 "SPECT Heart for infarct W Tc-99m Sestamibi IV"
* http://loinc.org#39656-4 "SPECT Heart for infarct"
* http://loinc.org#39657-2 "NM Heart Views for infarct W Tc-99m PYP IV"
* http://loinc.org#39658-0 "SPECT Heart at rest and W radionuclide IV"
* http://loinc.org#39660-6 "NM Heart Views at rest and W dipyridamole and W radionuclide IV"
* http://loinc.org#39661-4 "NM Heart Views at rest and W dobutamine and W radionuclide IV"
* http://loinc.org#39662-2 "SPECT Heart at rest and W stress and W Tc-99m Sestamibi IV"
* http://loinc.org#39663-0 "NM Heart Views at rest and W stress and W radionuclide IV"
* http://loinc.org#39664-8 "NM Heart Views for shunt detection W Tc-99m MAA IV"
* http://loinc.org#39665-5 "NM Heart Views for shunt detection"
* http://loinc.org#39666-3 "NM Heart Views W stress and W 201 Th IV"
* http://loinc.org#39667-1 "NM Heart Views W stress and W radionuclide IV"
* http://loinc.org#39668-9 "SPECT Heart W stress and W radionuclide IV"
* http://loinc.org#39669-7 "NM Whole body Views W Tc-99m Arcitumomab IV"
* http://loinc.org#39670-5 "NM Lacrimal duct Views W radionuclide intra lacrimal duct"
* http://loinc.org#39671-3 "NM Rectum Views W radionuclide PO"
* http://loinc.org#39672-1 "NM Esophagus Views for motility W radionuclide PO"
* http://loinc.org#39673-9 "NM Esophagus Views for reflux W radionuclide PO"
* http://loinc.org#39674-7 "NM Gallbladder Views W Tc-99m DISIDA IV"
* http://loinc.org#39675-4 "SPECT Whole body for infection W Ga-67 IV"
* http://loinc.org#39677-0 "NM Unspecified body region Views for infection W Ga-67 IV"
* http://loinc.org#39678-8 "SPECT Whole body for tumor W Ga-67 IV"
* http://loinc.org#39679-6 "NM Unspecified body region Views for tumor W Ga-67 IV"
* http://loinc.org#39680-4 "SPECT Whole body W Ga-67 IV"
* http://loinc.org#39681-2 "SPECT Unspecified body region limited W Ga-67 IV"
* http://loinc.org#39682-0 "SPECT Unspecified body region W Ga-67 IV"
* http://loinc.org#39683-8 "NM Whole body Views W Ga-67 IV"
* http://loinc.org#39684-6 "SPECT Unspecified body region for abscess W Ga-67 IV"
* http://loinc.org#39685-3 "NM Unspecified body region Views for abscess W Ga-67 IV"
* http://loinc.org#39686-1 "NM Whole body Views for lymphoma W Ga-67 IV"
* http://loinc.org#39687-9 "NM Unspecified body region Limited Views W Ga-67 IV"
* http://loinc.org#39688-7 "NM Unspecified body region Views W Ga-67 IV"
* http://loinc.org#39689-5 "NM Gastrointestinal tract Views W Tc-99m SC IV"
* http://loinc.org#39690-3 "NM Liver Views W Tc-99m tagged RBC IV"
* http://loinc.org#39691-1 "SPECT Liver W Tc-99m tagged RBC IV"
* http://loinc.org#39692-9 "SPECT Liver"
* http://loinc.org#39693-7 "NM Liver Views"
* http://loinc.org#39694-5 "NM Views for transplanted liver"
* http://loinc.org#39695-2 "NM Lung Limited Views"
* http://loinc.org#39696-0 "NM Lung Views W depreotide IV"
* http://loinc.org#39697-8 "NM Lung Perfusion"
* http://loinc.org#39698-6 "NM Whole body Views W I-131 MIBG IV"
* http://loinc.org#39699-4 "NM Heart Perfusion at rest and W Tc-99m Sestamibi IV"
* http://loinc.org#39700-0 "SPECT Heart perfusion W adenosine and W radionuclide IV"
* http://loinc.org#39701-8 "NM Heart Perfusion W adenosine and W radionuclide IV"
* http://loinc.org#39702-6 "NM Heart Perfusion W dobutamine and W Tc-99m Sestamibi IV"
* http://loinc.org#39703-4 "NM Heart Perfusion W dobutamine IV"
* http://loinc.org#39704-2 "NM Heart Perfusion W Tc-99m Sestamibi IV"
* http://loinc.org#39705-9 "NM Heart Perfusion W dipyridamole and W Tc-99m Sestamibi IV"
* http://loinc.org#39707-5 "NM Heart Perfusion W dipyridamole and W Tl-201 IV"
* http://loinc.org#39708-3 "NM Heart Perfusion W dipyridamole IV"
* http://loinc.org#39709-1 "NM Heart Perfusion W dipyridamole and W Tc-99m IV"
* http://loinc.org#39710-9 "SPECT Heart perfusion W Tc-99m Sestamibi IV"
* http://loinc.org#39711-7 "SPECT Heart perfusion W Tl-201 IV"
* http://loinc.org#39712-5 "SPECT Heart perfusion"
* http://loinc.org#39713-3 "NM Heart Perfusion W Tl-201 IV and W Tc-99m Tetrofosmin IV"
* http://loinc.org#39714-1 "NM Heart Perfusion W Tl-201 IV"
* http://loinc.org#39715-8 "NM Heart Perfusion W stress and W Tl-201 IV"
* http://loinc.org#39716-6 "NM Heart Perfusion"
* http://loinc.org#39718-2 "SPECT Heart perfusion at rest and W radionuclide IV"
* http://loinc.org#39719-0 "NM Heart Perfusion at rest and W adenosine and W radionuclide IV"
* http://loinc.org#39720-8 "NM Heart Perfusion at rest and W dipyridamole and W Tc-99m Sestamibi IV"
* http://loinc.org#39722-4 "NM Heart Perfusion at rest and W dipyridamole and W radionuclide IV"
* http://loinc.org#39723-2 "SPECT Heart perfusion at rest and W stress and W Tl-201 IV"
* http://loinc.org#39724-0 "SPECT Heart perfusion at rest and W stress and W radionuclide IV"
* http://loinc.org#39725-7 "SPECT Heart perfusion at rest and W adenosine and W Tl-201 IV"
* http://loinc.org#39726-5 "NM Heart Perfusion at rest and W stress and W radionuclide IV"
* http://loinc.org#39727-3 "NM Heart Perfusion at rest and W stress and W Tc-99m Sestamibi IV"
* http://loinc.org#39728-1 "NM Heart Perfusion at rest and W radionuclide IV"
* http://loinc.org#39729-9 "SPECT Heart perfusion at rest and W Tl-201 IV"
* http://loinc.org#39730-7 "NM Heart Perfusion W stress and W radionuclide IV"
* http://loinc.org#39731-5 "NM Heart Perfusion W adenosine and W Tc-99m Sestamibi IV"
* http://loinc.org#39732-3 "NM Heart Perfusion W stress and W Tc-99m Sestamibi IV"
* http://loinc.org#39733-1 "NM Heart Perfusion W dobutamine and W Tl-201 IV"
* http://loinc.org#39734-9 "SPECT Heart perfusion W stress and W radionuclide IV"
* http://loinc.org#39735-6 "NM Heart Perfusion W adenosine and W Tl-201 IV"
* http://loinc.org#39736-4 "SPECT Heart perfusion W stress and W Tc-99m Sestamibi IV"
* http://loinc.org#39737-2 "NM Neck Views"
* http://loinc.org#39738-0 "NM Abdomen Views W In-111 Satumomab IV"
* http://loinc.org#39739-8 "NM Pancreas Views"
* http://loinc.org#39740-6 "SPECT Parathyroid gland"
* http://loinc.org#39741-4 "NM Parathyroid gland Delayed Views"
* http://loinc.org#39742-2 "NM Parathyroid gland Views"
* http://loinc.org#39743-0 "SPECT Prostate W Tc-99m capromab pendatide IV"
* http://loinc.org#39744-8 "NM Prostate Views W Tc-99m capromab pendatide IV"
* http://loinc.org#39745-5 "NM Kidney Views W Tc-99m DTPA IV"
* http://loinc.org#39746-3 "NM Kidney Views W Tc-99m Mertiatide IV"
* http://loinc.org#39747-1 "NM Salivary gland Views"
* http://loinc.org#39748-9 "SPECT Whole body for tumor W Tc-99m Sestamibi IV"
* http://loinc.org#39749-7 "NM Whole body Views for tumor W Tc-99m Sestamibi IV"
* http://loinc.org#39750-5 "NM Unspecified body region Views for tumor W Tc-99m Sestamibi IV"
* http://loinc.org#39751-3 "NM Spleen Views"
* http://loinc.org#39752-1 "NM Spleen Views W radionuclide tagged heat damaged RBC IV"
* http://loinc.org#39753-9 "NM Scrotum and testicle Views W Tc-99m DTPA IV"
* http://loinc.org#39754-7 "NM Thyroid gland Limited Views W I-131 IV"
* http://loinc.org#39755-4 "SPECT Thyroid gland W I-131 IV"
* http://loinc.org#39756-2 "NM Thyroid gland Views W Tc-99m Sestamibi IV"
* http://loinc.org#39757-0 "NM Thyroid gland Views W Tc-99m IV"
* http://loinc.org#39758-8 "NM Guidance for localization of tumor of Breast"
* http://loinc.org#39759-6 "SPECT Guidance limited for localization of tumor"
* http://loinc.org#39760-4 "NM Guidance limited for localization of tumor"
* http://loinc.org#39761-2 "NM Guidance limited for localization of tumor-- W Tc-99m Sestamibi IV"
* http://loinc.org#39762-0 "SPECT Guidance for localization of tumor of Whole body"
* http://loinc.org#39763-8 "NM Guidance for localization of tumor of Whole body"
* http://loinc.org#39764-6 "NM Vein Views W Tc-99m SC IV"
* http://loinc.org#39765-3 "NM Vein Views W Tc-99m DTPA IV"
* http://loinc.org#39766-1 "NM Vein Views W Tc-99m HDP IV"
* http://loinc.org#39767-9 "NM Stomach Views for gastric emptying liquid phase W radionuclide PO"
* http://loinc.org#39768-7 "NM Stomach Views for gastric emptying W Tc-99m SC PO"
* http://loinc.org#39769-5 "NM Stomach Views for gastric emptying W radionuclide PO"
* http://loinc.org#39770-3 "SPECT Gastrointestinal tract"
* http://loinc.org#39811-5 "SPECT Unspecified body region for abscess"
* http://loinc.org#39812-3 "NM Bone Views W Tc-99m HMPAO IV"
* http://loinc.org#39813-1 "SPECT Bone limited"
* http://loinc.org#39816-4 "SPECT Whole body Bone"
* http://loinc.org#39818-0 "NM Whole body Bone Views"
* http://loinc.org#39819-8 "NM Bone Delayed Views"
* http://loinc.org#39820-6 "NM Bone Views W Sm-153 IV"
* http://loinc.org#39821-4 "SPECT Bone marrow limited"
* http://loinc.org#39822-2 "NM Bone marrow Limited Views"
* http://loinc.org#39823-0 "SPECT Bone marrow"
* http://loinc.org#39824-8 "NM Bone marrow Views"
* http://loinc.org#39825-5 "SPECT Whole body Bone marrow"
* http://loinc.org#39826-3 "NM Whole body Bone marrow Views"
* http://loinc.org#39827-1 "NM Whole body Views for endocrine tumor W I-131 MIBG IV"
* http://loinc.org#39828-9 "NM Whole body Views for endocrine tumor W In-111 pentetreotide IV"
* http://loinc.org#39829-7 "NM Whole body Views for tumor W Ga-67 IV"
* http://loinc.org#39830-5 "NM Whole body Views for infection W Ga-67 IV"
* http://loinc.org#39831-3 "NM Unspecified body region Limited Views for tumor W Ga-67 IV"
* http://loinc.org#39834-7 "NM Lung Ventilation W Tc-99m DTPA aerosol IH"
* http://loinc.org#39837-0 "NM Lung Ventilation"
* http://loinc.org#39838-8 "SPECT Lung ventilation and perfusion"
* http://loinc.org#39839-6 "SPECT Whole body W I-131 MIBG IV"
* http://loinc.org#39840-4 "NM Whole body Delayed Views W I-131 MIBG IV"
* http://loinc.org#39841-2 "NM Unspecified body region Views W I-131 MIBG IV"
* http://loinc.org#39842-0 "NM Whole body Delayed Views W In-111 Satumomab IV"
* http://loinc.org#39843-8 "NM Unspecified body region Limited Views W In-111 Satumomab IV"
* http://loinc.org#39844-6 "SPECT Whole body W In-111 Satumomab IV"
* http://loinc.org#39845-3 "NM Whole body Views W In-111 Satumomab IV"
* http://loinc.org#39846-1 "NM Unspecified body region Views W In-111 Satumomab IV"
* http://loinc.org#39847-9 "NM Parotid gland Views for blood flow"
* http://loinc.org#39848-7 "NM Head to Pelvis Views for shunt patency W In-111 IT"
* http://loinc.org#39849-5 "NM Head to Pelvis Views for shunt patency W radionuclide IT"
* http://loinc.org#39850-3 "NM Kidney - bilateral Views W I-131 IV"
* http://loinc.org#39851-1 "SPECT Kidney - bilateral W Tc-99m Mertiatide IV"
* http://loinc.org#39852-9 "SPECT Kidney - bilateral"
* http://loinc.org#39856-0 "NM Thyroid gland Views for blood flow"
* http://loinc.org#39857-8 "NM Adrenal gland Views W I-131 MIBG IV"
* http://loinc.org#39858-6 "NM Bone Views for blood flow"
* http://loinc.org#39859-4 "NM Brain Delayed Views"
* http://loinc.org#39860-2 "NM Heart Blood pool W stress and W radionuclide IV"
* http://loinc.org#39861-0 "NM Heart Blood pool"
* http://loinc.org#39862-8 "SPECT Heart blood pool at rest and W radionuclide IV"
* http://loinc.org#39863-6 "NM Heart First pass at rest and W stress and W radionuclide IV"
* http://loinc.org#39864-4 "NM Heart First pass"
* http://loinc.org#39865-1 "NM Left ventricle First pass"
* http://loinc.org#39866-9 "NM Heart First pass at rest and W Tc-99m Sestamibi IV"
* http://loinc.org#39867-7 "NM Heart First pass at rest and W radionuclide IV"
* http://loinc.org#39868-5 "NM Heart First pass W stress and W Tc-99m Sestamibi IV"
* http://loinc.org#39869-3 "NM Heart First pass W stress and W radionuclide IV"
* http://loinc.org#39870-1 "NM Heart Views for blood flow W Tc-99m pertechnetate IV"
* http://loinc.org#39871-9 "NM Heart Views for blood flow"
* http://loinc.org#39872-7 "SPECT Heart wall motion"
* http://loinc.org#39873-5 "NM Heart Wall motion"
* http://loinc.org#39874-3 "NM Cerebral cisterns Delayed Views W radionuclide IT"
* http://loinc.org#39875-0 "NM Whole body Delayed Views W Ga-67 IV"
* http://loinc.org#39876-8 "SPECT Liver and Spleen"
* http://loinc.org#39877-6 "NM Liver and Spleen Views"
* http://loinc.org#39879-2 "SPECT Bone"
* http://loinc.org#39880-0 "NM Bone 2 Phase Views"
* http://loinc.org#39881-8 "SPECT Whole body Bone 3 phase"
* http://loinc.org#39882-6 "NM Whole body Bone 3 Phase Views"
* http://loinc.org#39883-4 "NM Bone 3 Phase Views"
* http://loinc.org#39884-2 "NM Bone Blood pool"
* http://loinc.org#39885-9 "NM Heart First pass and Ventricular volume"
* http://loinc.org#39886-7 "NM Heart First pass and Wall motion at rest and W radionuclide IV"
* http://loinc.org#39887-5 "NM Heart First pass and Ejection fraction at rest and W radionuclide IV"
* http://loinc.org#39888-3 "NM Heart First pass and Wall motion W stress and W radionuclide IV"
* http://loinc.org#39889-1 "NM Heart First pass and Ejection fraction"
* http://loinc.org#39890-9 "NM Heart First pass and Wall motion"
* http://loinc.org#39891-7 "NM Heart Views for infarct and first pass W Tc-99m PYP IV"
* http://loinc.org#39892-5 "NM Heart Views for infarct and first pass"
* http://loinc.org#39893-3 "NM Heart Views for blood flow and shunt detection"
* http://loinc.org#39895-8 "NM Gallbladder Views for ejection fraction W Tc-99m DISIDA IV"
* http://loinc.org#39897-4 "NM Lung and Liver Views"
* http://loinc.org#39898-2 "SPECT Lung ventilation"
* http://loinc.org#39899-0 "NM Salivary gland Views for blood flow"
* http://loinc.org#39901-4 "NM Bone 3 Phase Views multiple areas"
* http://loinc.org#39902-2 "NM Bone 3 Phase Views single area"
* http://loinc.org#39904-8 "NM Bone Multiple area Views"
* http://loinc.org#39905-5 "SPECT Bone multiple areas"
* http://loinc.org#39906-3 "SPECT Bone marrow multiple areas"
* http://loinc.org#39907-1 "NM Bone marrow Multiple area Views"
* http://loinc.org#39908-9 "NM Heart First pass and Wall motion and Ventricular volume W stress and W radionuclide IV"
* http://loinc.org#39909-7 "NM Heart First pass and Wall motion and Ventricular volume and Ejection fraction W stress and W radionuclide IV"
* http://loinc.org#39910-5 "NM Heart First pass and Wall motion and Ejection fraction"
* http://loinc.org#39912-1 "NM Heart First pass and Wall motion and Ventricular volume and Ejection fraction"
* http://loinc.org#39913-9 "SPECT Heart gated and ejection fraction"
* http://loinc.org#39914-7 "NM Heart Gated W Tc-99m Sestamibi IV"
* http://loinc.org#39915-4 "NM Heart Gated"
* http://loinc.org#39916-2 "SPECT Heart gated"
* http://loinc.org#39917-0 "NM Heart Gated and Ejection fraction"
* http://loinc.org#39918-8 "SPECT Heart gated and wall motion"
* http://loinc.org#39919-6 "NM Heart Gated and First pass"
* http://loinc.org#39920-4 "NM Heart Gated at rest and W Tc-99m Sestamibi IV"
* http://loinc.org#39921-2 "NM Heart Gated at rest and W radionuclide IV"
* http://loinc.org#39922-0 "NM Heart Gated at rest and W Tc-99m pertechnetate IV"
* http://loinc.org#39923-8 "NM Heart Gated and Ejection fraction at rest and W radionuclide IV"
* http://loinc.org#39924-6 "NM Heart Gated at rest and W stress and W radionuclide IV"
* http://loinc.org#39925-3 "NM Heart Gated and Wall motion and Ejection fraction at rest and W radionuclide IV"
* http://loinc.org#39927-9 "NM Heart Gated W stress and W Tc-99m pertechnetate IV"
* http://loinc.org#39928-7 "NM Heart Gated W stress and W radionuclide IV"
* http://loinc.org#39929-5 "NM Heart Gated and Wall motion W stress and W radionuclide IV"
* http://loinc.org#39930-3 "SPECT Heart gated W stress and W radionuclide IV"
* http://loinc.org#39931-1 "NM Heart Gated and Wall motion and Ejection fraction"
* http://loinc.org#39932-9 "NM Heart Wall motion and Ejection fraction"
* http://loinc.org#39933-7 "NM Unspecified body region Views for infection multiple areas W Ga-67 IV"
* http://loinc.org#39934-5 "NM Unspecified body region Views for tumor multiple areas W Ga-67 IV"
* http://loinc.org#39935-2 "NM Unspecified body region Multiple area Views W Ga-67 IV"
* http://loinc.org#39936-0 "NM Joint Limited Views"
* http://loinc.org#39937-8 "NM Joint Multiple area Views W radionuclide XXX"
* http://loinc.org#39938-6 "SPECT Joint"
* http://loinc.org#39939-4 "NM Joint Views"
* http://loinc.org#39940-2 "NM Lung Clearance W Tc-99m DTPA aerosol IH"
* http://loinc.org#39942-8 "NM Lung Ventilation and Perfusion"
* http://loinc.org#39944-4 "NM Lung Ventilation and Equilibrium and Washout"
* http://loinc.org#39946-9 "NM Lung Ventilation and Perfusion and Differential"
* http://loinc.org#39947-7 "NM Lung Ventilation and Equilibrium"
* http://loinc.org#39949-3 "NM Unspecified body region Multiple area Views W In-111 Satumomab IV"
* http://loinc.org#39950-1 "NM Prostate Multiple area Views W Tc-99m capromab pendatide IV"
* http://loinc.org#39951-9 "NM Unspecified body region Views for tumor multiple areas W Tc-99m Sestamibi IV"
* http://loinc.org#39952-7 "NM Scrotum and testicle Views for blood flow and function"
* http://loinc.org#39953-5 "NM Guidance for localization of tumor multiple areas of Unspecified body region"
* http://loinc.org#39954-3 "NM Vein Views for thrombosis"
* http://loinc.org#41770-9 "NM Gallbladder Views W cholecystokinin and W radionuclide IV"
* http://loinc.org#41771-7 "NM Kidney Views W Tc-99m DMSA IV"
* http://loinc.org#41772-5 "SPECT Bone W In-111 tagged WBC IV"
* http://loinc.org#41836-8 "NM Bone Limited Views W In-111 tagged WBC IV"
* http://loinc.org#41837-6 "SPECT Whole body W Tc-99m Arcitumomab IV"
* http://loinc.org#41838-4 "SPECT Prostate W In-111 Satumomab IV"
* http://loinc.org#42158-6 "NM Adrenal gland Views"
* http://loinc.org#42161-0 "NM Heart Views W dobutamine IV"
* http://loinc.org#42166-9 "NM Heart 2 Views at rest and W Tl-201 IV"
* http://loinc.org#42170-1 "NM Whole body Views for lymphoma"
* http://loinc.org#42171-9 "NM Whole body Views for tumor"
* http://loinc.org#42175-0 "NM Whole body Views"
* http://loinc.org#42261-8 "NM Kidney Views for blood flow"
* http://loinc.org#42262-6 "NM Liver Views for blood flow"
* http://loinc.org#42263-4 "NM Spleen Views for blood flow"
* http://loinc.org#42271-7 "NM Thyroid gland Views and Views uptake W I-123 IV"
* http://loinc.org#42292-3 "SPECT Whole body for tumor W Tl-201 IV"
* http://loinc.org#42305-3 "NM Whole body Views for tumor W Tl-201 IV"
* http://loinc.org#42306-1 "NM Heart Gated and Wall motion"
* http://loinc.org#42308-7 "NM Scrotum and testicle Views for blood flow"
* http://loinc.org#42309-5 "NM Heart Views at rest and W stress and W Tl-201 IV"
* http://loinc.org#42310-3 "SPECT Kidney"
* http://loinc.org#42700-5 "NM Bone Views W Tc-99m tagged WBC IV"
* http://loinc.org#42708-8 "NM Whole body Views W In-111 tiuxetan IV"
* http://loinc.org#42709-6 "NM Liver Blood pool"
* http://loinc.org#42711-2 "NM Whole body Views W In-111 tagged WBC IV"
* http://loinc.org#42776-5 "NM Unspecified body region Views for AV shunt"
* http://loinc.org#43459-7 "NM Brain Views during electroconvulsive shock treatment"
* http://loinc.org#43461-3 "NM Kidney Views W furosemide IV"
* http://loinc.org#43500-8 "NM Vessel Views for blood flow"
* http://loinc.org#43501-6 "NM Vessel Views"
* http://loinc.org#43526-3 "SPECT Unspecified body region"
* http://loinc.org#43550-3 "NM Brain Views for blood flow and function"
* http://loinc.org#43557-8 "NM Liver and Biliary ducts and Gallbladder Views"
* http://loinc.org#43562-8 "NM Skeletal system.axial Views for bone density"
* http://loinc.org#43563-6 "NM Skeletal system.peripheral Views for bone density"
* http://loinc.org#43642-8 "NM Brain Views for blood flow W Tc-99m DTPA IV"
* http://loinc.org#43643-6 "NM Brain Views for blood flow W Tc-99m glucoheptonate IV"
* http://loinc.org#43644-4 "NM Brain Limited Views for blood flow"
* http://loinc.org#43645-1 "NM Heart Qualitative Views for infarct"
* http://loinc.org#43646-9 "NM Heart Qualitative and Quantitative Views for infarct"
* http://loinc.org#43647-7 "NM Heart Quantitative Views for infarct"
* http://loinc.org#43648-5 "NM Unspecified body region Views for endocrine tumor multiple areas W I-131 MIBG IV"
* http://loinc.org#43649-3 "NM Unspecified body region Views for endocrine tumor multiple areas W In-111 pentetreotide IV"
* http://loinc.org#43650-1 "NM Liver and Biliary ducts and Gallbladder Views W cholecystokinin and W radionuclide IV"
* http://loinc.org#43651-9 "NM Liver and Biliary ducts and Gallbladder Views W sincalide and W radionuclide IV"
* http://loinc.org#43652-7 "SPECT Liver and Spleen for blood flow"
* http://loinc.org#43653-5 "NM Liver and Spleen Views for blood flow"
* http://loinc.org#43654-3 "NM Liver Views for blood flow W Tc-99m tagged RBC IV"
* http://loinc.org#43655-0 "SPECT Liver for blood flow"
* http://loinc.org#43656-8 "NM Lung Perfusion quantitative"
* http://loinc.org#43657-6 "NM Lung Quantitative Views"
* http://loinc.org#43658-4 "NM Heart Perfusion quantitative"
* http://loinc.org#43659-2 "SPECT Heart perfusion qualitative at rest and W radionuclide IV"
* http://loinc.org#43660-0 "NM Heart Perfusion qualitative at rest and W radionuclide IV"
* http://loinc.org#43661-8 "NM Heart Perfusion quantitative at rest and W radionuclide IV"
* http://loinc.org#43662-6 "SPECT Renal vessels for blood flow W Tc-99m glucoheptonate IV"
* http://loinc.org#43663-4 "NM Renal vessels Views for blood flow W Tc-99m glucoheptonate IV"
* http://loinc.org#43664-2 "NM Renal vessels Views for blood flow W Tc-99m DTPA IV"
* http://loinc.org#43665-9 "NM Renal vessels Views for blood flow W Tc-99m Mertiatide IV"
* http://loinc.org#43666-7 "NM Kidney+Renal vessels Views for blood flow W Tc-99m glucoheptonate IV"
* http://loinc.org#43667-5 "NM Kidney+Renal vessels Views W Tc-99m DTPA IV"
* http://loinc.org#43669-1 "NM Renal vessels Views"
* http://loinc.org#43670-9 "SPECT Spleen for blood flow"
* http://loinc.org#43671-7 "NM Thyroid gland Spot"
* http://loinc.org#43672-5 "NM Thyroid gland Views and Views uptake"
* http://loinc.org#43673-3 "SPECT Thyroid gland for blood flow"
* http://loinc.org#43777-2 "NM Heart Perfusion at rest and W adenosine and W Tl-201 IV"
* http://loinc.org#43789-7 "NM Liver and Biliary ducts and Gallbladder Views for patency W Tc-99m IV"
* http://loinc.org#44136-0 "PT Unspecified body region"
* http://loinc.org#44137-8 "PT Heart"
* http://loinc.org#44138-6 "PT Brain"
* http://loinc.org#44139-4 "PT Whole body"
* http://loinc.org#44140-2 "NM Abdomen and Pelvis Views for tumor"
* http://loinc.org#44141-0 "NM Liver and Spleen Views W Tc-99m MAA IV"
* http://loinc.org#44142-8 "NM Bone Views W Tc-99m medronate IV"
* http://loinc.org#44143-6 "NM Heart Views W Tc-99m tagged RBC IV"
* http://loinc.org#44144-4 "NM Liver Views W Xe-133 IH"
* http://loinc.org#44145-1 "NM Parathyroid gland Views W Tc-99m Sestamibi IV"
* http://loinc.org#44146-9 "NM Bone marrow Views W Tc-99m SC IV"
* http://loinc.org#44147-7 "NM Thyroid gland Views and Views uptake W Tc-99m pertechnetate IV"
* http://loinc.org#44148-5 "NM Brain Views for blood flow W Tc-99m bicisate IV"
* http://loinc.org#44149-3 "NM Abdomen and Pelvis Views for shunt patency W Tc-99m MAA inj"
* http://loinc.org#44150-1 "NM Brain Views W Tc-99m bicisate IV"
* http://loinc.org#44151-9 "SPECT Heart W Tc-99m Sestamibi IV"
* http://loinc.org#44152-7 "SPECT Brain W Tc-99m bicisate IV"
* http://loinc.org#44153-5 "SPECT Kidney W Tc-99m glucoheptonate IV"
* http://loinc.org#44154-3 "SPECT Heart W dipyridamole and W Tc-99m Sestamibi IV"
* http://loinc.org#44232-7 "NM Kidney Views WO and W Tc-99m Mertiatide IV"
* http://loinc.org#44233-5 "NM Kidney Views WO and W Tc-99m DTPA IV"
* http://loinc.org#44234-3 "NM Kidney Views W Tc-99m glucoheptonate IV"
* http://loinc.org#46297-8 "SPECT Whole body"
* http://loinc.org#46361-2 "NM Lung Ventilation W Xe-133 IH"
* http://loinc.org#46366-1 "SPECT guidance for percutaneous biopsy of Bone"
* http://loinc.org#46373-7 "SPECT Guidance for placement of tube in Chest"
* http://loinc.org#46384-4 "SPECT Guidance for superficial biopsy of Bone"
* http://loinc.org#46395-0 "SPECT Heart gated and ejection fraction at rest and W stress and W radionuclide IV"
* http://loinc.org#46396-8 "SPECT Heart gated at rest and W Tc-99m Sestamibi IV"
* http://loinc.org#47378-5 "SPECT Liver blood pool"
* http://loinc.org#49118-3 "NM Unspecified body region Views"
* http://loinc.org#49566-3 "SPECT Heart at rest and W Tc-99m Sestamibi IV"
* http://loinc.org#49567-1 "SPECT Heart perfusion W adenosine and W Tc-99m Sestamibi IV"
* http://loinc.org#49568-9 "SPECT Heart perfusion at rest and W stress and W Tl-201 IV and W Tc-99m Sestamibi IV"
* http://loinc.org#49569-7 "SPECT Heart perfusion and wall motion at rest and W stress and W Tl-201 IV and W Tc-99m Sestamibi IV"
* http://loinc.org#49571-3 "NM Unspecified body region Limited Views W I-131 MIBG IV"
* http://loinc.org#51389-5 "NM Breast Views W Tl-201 IV"
* http://loinc.org#57822-9 "PT Lung"
* http://loinc.org#57823-7 "PT Esophagus"
* http://loinc.org#58741-0 "PT Skull base to mid-thigh"
* http://loinc.org#58742-8 "PT Head and Neck"
* http://loinc.org#60527-9 "NM Thyroid gland Views and Views uptake W I-123 PO"
* http://loinc.org#64051-6 "NM Breast lymphatic vessels - left Views W radionuclide intra lymphatic"
* http://loinc.org#64052-4 "NM Breast lymphatic vessels - right Views W radionuclide intra lymphatic"
* http://loinc.org#69229-3 "SPECT Liver W Tc-99m SC IV"
* http://loinc.org#69230-1 "NM Liver Views W Tc-99m SC IV"
* http://loinc.org#69231-9 "NM Heart Views W stress and W Tc-99m IV"
* http://loinc.org#69232-7 "NM Heart Views W stress and W Tc-99m Sestamibi IV"
* http://loinc.org#69233-5 "NM Parotid gland Views W Tc-99m pertechnetate IV"
* http://loinc.org#69234-3 "SPECT Spleen W Tc-99m tagged RBC IV"
* http://loinc.org#69235-0 "SPECT Scrotum and testicle for blood flow"
* http://loinc.org#69236-8 "NM Thyroid gland Views and Views uptake W I-131 PO"
* http://loinc.org#69237-6 "SPECT Whole body for tumor"
* http://loinc.org#69238-4 "SPECT Urinary bladder and Urethra W contrast intra bladder during voiding"
* http://loinc.org#81206-5 "NM Liver and Spleen Views W Tc-99m SC IV"
* http://loinc.org#81542-3 "NM Lumbar spine Views for CSF leak post lumbar puncture W radionuclide IT"
* http://loinc.org#81543-1 "NM Head Views for CSF leak with rhinorrhea or otorrhea W radionuclide IT"
* http://loinc.org#81544-9 "NM Gastrointestinal tract Views for gastrointestinal bleeding"
* http://loinc.org#81545-6 "NM Abdomen and Pelvis Views for shunt patency"
* http://loinc.org#81546-4 "NM Views for blood flow and kidney function"
* http://loinc.org#81547-2 "SPECT Whole body W In-111 pentetreotide IV"
* http://loinc.org#81548-0 "SPECT Unspecified body region W tagged WBC IV"
* http://loinc.org#81549-8 "SPECT+CT Lymph node"
* http://loinc.org#81550-6 "SPECT+CT Parathyroid gland"
* http://loinc.org#81551-4 "PET+CT Bone from skull base to mid-thigh W 18F-NaF IV"
* http://loinc.org#81552-2 "PET+CT Whole body Bone W 18F-NaF IV"
* http://loinc.org#81553-0 "PET+CT Guidance limited for localization of tumor of Unspecified body region-- W 18F-FDG IV"
* http://loinc.org#81554-8 "PET+CT Guidance for localization of tumor of Skull base to mid-thigh-- W 18F-FDG IV"
* http://loinc.org#81555-5 "PET+CT Guidance for localization of tumor of Whole body-- W 18F-FDG IV"
* http://loinc.org#81556-3 "SPECT Unspecified body region for infection or inflammation"
* http://loinc.org#81557-1 "SPECT Brain W florbetapir IV"
* http://loinc.org#81558-9 "SPECT Brain W Tc-99m IV"
* http://loinc.org#81559-7 "PET+CT Unspecified body region for simulation limited"
* http://loinc.org#81560-5 "SPECT Whole body W In-111 capromab pendetide IV"
* http://loinc.org#81561-3 "SPECT Heart W multiple states of exercise"
* http://loinc.org#81562-1 "SPECT Heart W single state of exercise"
* http://loinc.org#81563-9 "NM Heart First pass and Blood pool"
* http://loinc.org#81564-7 "PT Heart for sarcoidosis"
* http://loinc.org#81565-4 "PT Heart for tissue viability"
* http://loinc.org#81566-2 "NM Heart Gated and Blood pool and Ejection fraction and Wall motion W multiple states of exercise"
* http://loinc.org#81567-0 "NM Heart Gated and Blood pool and Ejection fraction and Wall motion W single state of exercise"
* http://loinc.org#81568-8 "PT perfusion Heart W multiple states of exercise"
* http://loinc.org#81569-6 "PT perfusion Heart W single state of exercise"
* http://loinc.org#81570-4 "NM Heart Perfusion W single state of exercise"
* http://loinc.org#81571-2 "NM Heart Perfusion W multiple states of exercise"
* http://loinc.org#81572-0 "NM Salivary gland Views for function"
* http://loinc.org#81573-8 "NM Brain Brain death protocol Views"
* http://loinc.org#81574-6 "NM Brain GE 4 Views"
* http://loinc.org#81575-3 "NM Brain GE 4 Views for blood flow"
* http://loinc.org#81576-1 "NM Brain LT 4 Views for blood flow"
* http://loinc.org#81577-9 "PT Brain for amyloidosis"
* http://loinc.org#81578-7 "PT Brain metabolic"
* http://loinc.org#81579-5 "PT perfusion Brain"
* http://loinc.org#81580-3 "NM Thyroid gland Views for therapy W I-131 PO"
* http://loinc.org#81581-1 "NM Thyroid gland Views for dosimetry W radionuclide PO"
* http://loinc.org#81582-9 "NM Thyroid gland Uptake"
* http://loinc.org#81583-7 "NM Whole body Views W Sm-153 IV"
* http://loinc.org#81584-5 "NM Whole body Views W tagged WBC IV"
* http://loinc.org#81585-2 "NM Unspecified body region Views W tagged WBC IV"
* http://loinc.org#81586-0 "NM Whole body Views W Y-90 ibritumomab tiuxetan IV"
* http://loinc.org#81587-8 "NM Unspecified body region Limited Views for infection or inflammation"
* http://loinc.org#81588-6 "NM Whole body Views for thyroid tumor"
* http://loinc.org#81589-4 "NM Whole body Views for infection or inflammation"
* http://loinc.org#81590-2 "NM Extremity veins - bilateral Views for thrombosis"
* http://loinc.org#81591-0 "NM Extremity veins - unilateral Views for thrombosis"
* http://loinc.org#81592-8 "NM Views for transplanted kidney"
* http://loinc.org#81593-6 "NM Lymph node Views"
* http://loinc.org#81594-4 "NM Lymph node - bilateral Views"
* http://loinc.org#81595-1 "NM Lymph node Views for lymphedema"
* http://loinc.org#81596-9 "NM Lung Quantitative Views Ventilation and Perfusion"
* http://loinc.org#81597-7 "NM Bones Views for metastasis W Ra-223 IV"
* http://loinc.org#81598-5 "NM Whole body Views for thyroid tumor metastasis post therapy"
* http://loinc.org#81599-3 "NM Guidance for multiple days for localization of tumor of Whole body"
* http://loinc.org#81600-9 "NM Unspecified body region Limited Views for infection or inflammation W Tc-99m tagged WBC IV"
* http://loinc.org#81601-7 "NM Unspecified body region Limited Views for thyroid tumor metastasis"
* http://loinc.org#81602-5 "NM Stomach Views for gastric emptying solid phase W radionuclide PO"
* http://loinc.org#81603-3 "NM Views for blood flow and kidney function W diuretic IV"
* http://loinc.org#81604-1 "NM Kidney Views for glomerular filtration rate"
* http://loinc.org#81605-8 "NM Ureter and Urinary bladder Views"
* http://loinc.org#81606-6 "NM Liver and Biliary ducts and Gallbladder Views W cholecystokinetic IV"
* http://loinc.org#81607-4 "NM Kidney cortex Views"
* http://loinc.org#81608-2 "NM Views for blood flow and kidney function W ACE inhibitor PO"
* http://loinc.org#81609-0 "NM Liver Views W SIR-spheres intraarterial hepatic injection"
* http://loinc.org#81610-8 "NM Liver Views W Theraspheres intraarterial hepatic injection"
* http://loinc.org#81611-6 "NM Head to Pelvis Views for shunt patency"
* http://loinc.org#81612-4 "NM Heart Blood pool and Ejection fraction and First pass"
* http://loinc.org#81613-2 "SPECT Liver for hemangioma"
* http://loinc.org#82126-4 "PT Guidance for radiation treatment of Unspecified body region"
* http://loinc.org#82136-3 "NM Whole body Views for tumor W I-123 MIBG IV"
* http://loinc.org#82800-4 "PET+CT Heart W contrast IV"
* http://loinc.org#82801-2 "PET+CT Heart WO contrast"
* http://loinc.org#82805-3 "PET+CT Guidance for localization of tumor of Whole body-- W 18F-FDG IV and WO contrast"
* http://loinc.org#82806-1 "PET+CT Guidance for localization of tumor of Whole body-- W 18F-FDG IV and W contrast IV"
* http://loinc.org#82807-9 "PET+CT Guidance for localization of tumor of Skull vertex to mid-thigh-- W 18F-FDG IV and WO contrast"
* http://loinc.org#82808-7 "PET+CT Guidance for localization of tumor of Skull base to mid-thigh-- W 18F-FDG IV and WO contrast"
* http://loinc.org#82809-5 "PET+CT Guidance for localization of tumor of Skull base to mid-thigh-- W 18F-FDG IV and W contrast IV"
* http://loinc.org#86976-8 "PET+CT Brain metabolic"
* http://loinc.org#87905-6 "PET+CT Guidance for localization of tumor of Head and Neck-- W 18F-FDG IV"
* http://loinc.org#87907-2 "PET+CT Brain for amyloidosis"
* http://loinc.org#87915-5 "PET+CT Guidance for localization of tumor of Skull vertex to mid-thigh-- W 18F-FDG IV and W contrast IV"
* http://loinc.org#88944-4 "NM Lung and Liver Views for AV shunt W Tc-99m MAA+W intraarterial hepatic injection"
* http://loinc.org#89631-6 "SPECT+CT Guidance for localization of tumor of Whole body"
* http://loinc.org#89712-4 "PET+CT Guidance for limited for localization of tumor of Unspecified body region-- W 18F-FDG IV and W contrast IV"
* http://loinc.org#89842-9 "SPECT+CT Whole body"
* http://loinc.org#90312-0 "SPECT+CT Skeletal system"
