ValueSet: MyCoreRadiologyProcedureComputedTomographyMyCore
Id: radiology-procedure-ct-my-core
Title: "MY Core Radiology Procedure - Computed tomography"
Description: "NATIONAL SELECTION. The computed tomography subset of the LOINC/RSNA Radiology Playbook. 1058 codes. A modality-scoped pick list; the full catalogue is radiology-procedure-my-core."
* ^url = "https://standards.moh.gov.my/fhir/my-core/ValueSet/radiology-procedure-ct-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^publisher = "Data Team, Digital Health Division, Ministry of Health Malaysia"
* ^copyright = "This value set enumerates LOINC codes. LOINC is copyright Regenstrief Institute, Inc. and the LOINC Committee, and is available at no cost under the LOINC licence. RPID identifiers are from the RSNA Radiology Playbook."
* ^compose.inactive = false
* http://loinc.org#24544-9 "CT Thoracic Aorta"
* http://loinc.org#24545-6 "CT Thoracic Aorta W contrast IV"
* http://loinc.org#24566-2 "CT Retroperitoneum"
* http://loinc.org#24585-2 "CT Guidance for stereotactic biopsy of Head-- W contrast IV"
* http://loinc.org#24623-1 "CT Guidance for nerve block of Celiac plexus"
* http://loinc.org#24627-2 "CT Chest"
* http://loinc.org#24628-0 "CT Chest W contrast IV"
* http://loinc.org#24690-0 "CT Extremity"
* http://loinc.org#24691-8 "CT Extremity W contrast IV"
* http://loinc.org#24696-7 "CT Facial bones"
* http://loinc.org#24697-5 "CT Facial bones W contrast IV"
* http://loinc.org#24725-4 "CT Head"
* http://loinc.org#24726-2 "CT Head WO and W contrast IV"
* http://loinc.org#24727-0 "CT Head W contrast IV"
* http://loinc.org#24728-8 "CT perfusion Head"
* http://loinc.org#24729-6 "CT perfusion Head WO and W contrast IV"
* http://loinc.org#24734-6 "CT Cerebral cisterns W contrast IT"
* http://loinc.org#24753-6 "CT Unspecified body region W contrast IV"
* http://loinc.org#24769-2 "CT Guidance for injection of Joint space"
* http://loinc.org#24811-2 "CT Guidance for fluid aspiration of Liver"
* http://loinc.org#24812-0 "CT Guidance for biopsy of Liver"
* http://loinc.org#24813-8 "CT Guidance for core needle biopsy of Liver"
* http://loinc.org#24814-6 "CT Liver"
* http://loinc.org#24815-3 "CT Liver W contrast IV"
* http://loinc.org#24822-9 "CT Guidance for fluid aspiration of Lung"
* http://loinc.org#24823-7 "CT Guidance for biopsy of Lung"
* http://loinc.org#24835-1 "CT Nasopharynx and Neck"
* http://loinc.org#24836-9 "CT Nasopharynx and Neck W contrast IV"
* http://loinc.org#24837-7 "CT Guidance for fluid aspiration of Neck"
* http://loinc.org#24838-5 "CT Guidance for biopsy of Neck"
* http://loinc.org#24848-4 "CT Orbit - bilateral"
* http://loinc.org#24849-2 "CT Orbit - bilateral WO and W contrast IV"
* http://loinc.org#24850-0 "CT Orbit - bilateral W contrast IV"
* http://loinc.org#24856-7 "CT Guidance for fluid aspiration of Pancreas"
* http://loinc.org#24857-5 "CT Pancreas"
* http://loinc.org#24858-3 "CT Pancreas W contrast IV"
* http://loinc.org#24863-3 "CT Guidance for fluid aspiration of Pelvis"
* http://loinc.org#24864-1 "CT Guidance for biopsy of Pelvis"
* http://loinc.org#24865-8 "CT Pelvis"
* http://loinc.org#24866-6 "CT Pelvis W contrast IV"
* http://loinc.org#24877-3 "CT Petrous part of temporal bone"
* http://loinc.org#24878-1 "CT Petrous part of temporal bone W contrast IV"
* http://loinc.org#24901-1 "CT Guidance for injection of Sacroiliac Joint"
* http://loinc.org#24904-5 "CT Pituitary and Sella turcica WO and W contrast IV"
* http://loinc.org#24913-6 "CT Sinuses limited"
* http://loinc.org#24932-6 "CT Cervical spine"
* http://loinc.org#24933-4 "CT Cervical spine W contrast IV"
* http://loinc.org#24934-2 "CT Cervical spine W contrast IT"
* http://loinc.org#24963-1 "CT Lumbar spine"
* http://loinc.org#24964-9 "CT Lumbar spine W contrast IV"
* http://loinc.org#24965-6 "CT Lumbar spine W contrast IT"
* http://loinc.org#24978-9 "CT Thoracic spine"
* http://loinc.org#24979-7 "CT Thoracic spine W contrast IV"
* http://loinc.org#24986-2 "CT Guidance for biopsy of Spine"
* http://loinc.org#24987-0 "CT Spine W contrast IV"
* http://loinc.org#24988-8 "CT Spleen"
* http://loinc.org#24989-6 "CT Spleen WO and W contrast IV"
* http://loinc.org#25039-9 "CT Unspecified body region limited"
* http://loinc.org#25041-5 "CT Guidance for aspiration or biopsy of Unspecified body region-- W contrast IV"
* http://loinc.org#25042-3 "CT Guidance for aspiration or biopsy of Unspecified body region"
* http://loinc.org#25043-1 "CT Guidance for fluid aspiration of Unspecified body region"
* http://loinc.org#25044-9 "CT Guidance for biopsy of Unspecified body region"
* http://loinc.org#25045-6 "CT Unspecified body region"
* http://loinc.org#25046-4 "CT Unspecified body region W anesthesia"
* http://loinc.org#25047-2 "CT Unspecified body region W conscious sedation"
* http://loinc.org#25053-0 "CT Guidance for radiosurgery of Unspecified body region"
* http://loinc.org#25054-8 "CT Guidance for radiosurgery of Unspecified body region-- W contrast IV"
* http://loinc.org#26184-2 "CT Extremity - bilateral W contrast IV"
* http://loinc.org#26185-9 "CT Extremity - left W contrast IV"
* http://loinc.org#26186-7 "CT Extremity - right W contrast IV"
* http://loinc.org#26224-6 "CT Extremity - bilateral"
* http://loinc.org#26226-1 "CT Extremity - left"
* http://loinc.org#26231-1 "CT Extremity - right"
* http://loinc.org#26319-4 "CT Guidance for injection of Sacroiliac joint - bilateral"
* http://loinc.org#26320-2 "CT Guidance for injection of Sacroiliac joint - left"
* http://loinc.org#26321-0 "CT Guidance for injection of Sacroiliac joint - right"
* http://loinc.org#28566-8 "CT Spine"
* http://loinc.org#29252-4 "CT Chest WO contrast"
* http://loinc.org#30578-9 "CT Guidance for drainage of abscess of Unspecified body region"
* http://loinc.org#30579-7 "CT Guidance for injection of Spine facet joint"
* http://loinc.org#30580-5 "CT Guidance for fine needle aspiration of Unspecified body region"
* http://loinc.org#30581-3 "CT Guidance for radiation treatment of Unspecified body region-- W contrast IV"
* http://loinc.org#30582-1 "CT Guidance for radiation treatment of Unspecified body region-- WO contrast"
* http://loinc.org#30583-9 "CT Internal auditory canal W contrast IV"
* http://loinc.org#30584-7 "CT Internal auditory canal WO contrast"
* http://loinc.org#30585-4 "CT Nasopharynx and Neck WO contrast"
* http://loinc.org#30586-2 "CT Neck WO and W contrast IV"
* http://loinc.org#30587-0 "CT Orbit - bilateral WO contrast"
* http://loinc.org#30588-8 "CT Sinuses"
* http://loinc.org#30589-6 "CT Petrous part of temporal bone WO contrast"
* http://loinc.org#30590-4 "CT Pituitary and Sella turcica W contrast IV"
* http://loinc.org#30591-2 "CT Pituitary and Sella turcica WO contrast"
* http://loinc.org#30592-0 "CT Cervical spine WO contrast"
* http://loinc.org#30593-8 "CTA Head vessels WO and W contrast IV"
* http://loinc.org#30594-6 "CTA Neck vessels WO and W contrast IV"
* http://loinc.org#30595-3 "CT Guidance for fine needle aspiration of Lung"
* http://loinc.org#30596-1 "CT Thoracic spine W contrast IT"
* http://loinc.org#30597-9 "CT Thoracic spine WO contrast"
* http://loinc.org#30598-7 "CT Chest WO and W contrast IV"
* http://loinc.org#30600-1 "CT Small bowel W positive contrast via enteroclysis tube"
* http://loinc.org#30601-9 "CT Guidance for biopsy of Abdomen"
* http://loinc.org#30602-7 "CT Guidance for fine needle aspiration of Abdomen"
* http://loinc.org#30603-5 "CT Guidance for fine needle aspiration of Liver"
* http://loinc.org#30604-3 "CT Guidance for biopsy of Pancreas"
* http://loinc.org#30605-0 "CT Guidance for fine needle aspiration of Pancreas"
* http://loinc.org#30606-8 "CT Guidance for fine needle aspiration of Pelvis"
* http://loinc.org#30607-6 "CT Guidance for biopsy of Kidney - bilateral"
* http://loinc.org#30608-4 "CT Guidance for fine needle aspiration of Kidney - bilateral"
* http://loinc.org#30609-2 "CT Guidance for biopsy of Spleen"
* http://loinc.org#30610-0 "CT Guidance for fine needle aspiration of Spleen"
* http://loinc.org#30611-8 "CT Liver WO contrast"
* http://loinc.org#30612-6 "CT Liver WO and W contrast IV"
* http://loinc.org#30613-4 "CT Pancreas WO contrast"
* http://loinc.org#30614-2 "CT Pancreas WO and W contrast IV"
* http://loinc.org#30615-9 "CT Pelvis WO contrast"
* http://loinc.org#30616-7 "CT Pelvis WO and W contrast IV"
* http://loinc.org#30619-1 "CT Sacroiliac Joint"
* http://loinc.org#30620-9 "CT Lumbar spine WO contrast"
* http://loinc.org#30621-7 "CT Spleen WO contrast"
* http://loinc.org#30622-5 "CT Spleen W contrast IV"
* http://loinc.org#30623-3 "CTA Pelvis vessels WO and W contrast IV"
* http://loinc.org#30624-1 "CT Lower extremity W contrast IV"
* http://loinc.org#30625-8 "CT Lower extremity WO contrast"
* http://loinc.org#30626-6 "CT Upper extremity W contrast IV"
* http://loinc.org#30627-4 "CT Upper extremity WO contrast"
* http://loinc.org#30799-1 "CT Head WO contrast"
* http://loinc.org#30801-5 "CT Maxillofacial region W contrast IV"
* http://loinc.org#30802-3 "CT Maxillofacial region WO contrast"
* http://loinc.org#30803-1 "CT Maxillofacial region WO and W contrast IV"
* http://loinc.org#30804-9 "CTA Chest vessels WO and W contrast IV"
* http://loinc.org#30805-6 "CTA Abdominal vessels WO and W contrast IV"
* http://loinc.org#30807-2 "CTA Lower extremity vessels WO and W contrast IV"
* http://loinc.org#35884-6 "CT Guidance for drainage of abscess of Abdomen"
* http://loinc.org#35886-1 "CT Guidance for fluid aspiration of Breast"
* http://loinc.org#35887-9 "CT Guidance for aspiration of cyst of Unspecified body region"
* http://loinc.org#35891-1 "CT guidance for percutaneous biopsy of Bone"
* http://loinc.org#35892-9 "CT Guidance for biopsy of Head"
* http://loinc.org#35893-7 "CT Guidance for biopsy of Breast"
* http://loinc.org#35895-2 "CT Guidance for biopsy of Chest"
* http://loinc.org#35896-0 "CT Guidance for biopsy of Lower extremity"
* http://loinc.org#35897-8 "CT Guidance for biopsy of Upper extremity"
* http://loinc.org#35898-6 "CT Guidance for biopsy of Salivary gland"
* http://loinc.org#35901-8 "CT Guidance for biopsy of Lymph node"
* http://loinc.org#35903-4 "CT Guidance for biopsy of Prostate"
* http://loinc.org#35904-2 "CT Guidance for biopsy of Cervical spine"
* http://loinc.org#35905-9 "CT Guidance for biopsy of Lumbar spine"
* http://loinc.org#35906-7 "CT Guidance for biopsy of Thoracic spine"
* http://loinc.org#35908-3 "CT Guidance for biopsy of Thyroid gland"
* http://loinc.org#35909-1 "CT Guidance for biopsy of Chest-- W contrast IV"
* http://loinc.org#35910-9 "CT Guidance for biopsy of Chest-- WO and W contrast IV"
* http://loinc.org#35911-7 "CT Guidance for biopsy of Chest-- WO contrast"
* http://loinc.org#35913-3 "CT Guidance for drainage of Abdomen"
* http://loinc.org#35914-1 "CT Guidance for drainage of Anus"
* http://loinc.org#35915-8 "CT Guidance for drainage of Appendix"
* http://loinc.org#35916-6 "CT Guidance for drainage of Chest"
* http://loinc.org#35917-4 "CT Guidance for drainage of Gallbladder"
* http://loinc.org#35918-2 "CT Guidance for drainage of Kidney"
* http://loinc.org#35919-0 "CT Guidance for drainage of Liver"
* http://loinc.org#35920-8 "CT Guidance for drainage of Lymph node"
* http://loinc.org#35921-6 "CT Guidance for drainage of Pelvis"
* http://loinc.org#35922-4 "CT Guidance for drainage of Unspecified body region"
* http://loinc.org#35923-2 "CT Guidance for drainage of Chest-- W contrast IV"
* http://loinc.org#35924-0 "CT Guidance for drainage of Chest-- WO contrast"
* http://loinc.org#35928-1 "CT Guidance for localization of Breast - left"
* http://loinc.org#35929-9 "CT Guidance for localization of Breast - right"
* http://loinc.org#35930-7 "CT Guidance for nerve block of Abdomen"
* http://loinc.org#35931-5 "CT Guidance for nerve block of Pelvis"
* http://loinc.org#35932-3 "CT Guidance for nerve block of Lumbar spine"
* http://loinc.org#35933-1 "CT Guidance for percutaneous vertebroplasty of Spine"
* http://loinc.org#35934-9 "CT Guidance for percutaneous vertebroplasty of Lumbar spine"
* http://loinc.org#35935-6 "CT Guidance for percutaneous vertebroplasty of Thoracic spine"
* http://loinc.org#35937-2 "CT Guidance for placement of radiation therapy fields in Unspecified body region"
* http://loinc.org#35938-0 "CT Guidance for placement of tube in Chest"
* http://loinc.org#35940-6 "CT Ankle"
* http://loinc.org#35941-4 "CT Ankle - bilateral"
* http://loinc.org#35942-2 "CT Ankle - left"
* http://loinc.org#35944-8 "CT Ankle - right"
* http://loinc.org#35945-5 "CT Thoracic and abdominal aorta"
* http://loinc.org#35948-9 "CT Abdominal Aorta"
* http://loinc.org#35952-1 "CT Appendix"
* http://loinc.org#35957-0 "CT Internal auditory canal - left"
* http://loinc.org#35958-8 "CT Internal auditory canal"
* http://loinc.org#35960-4 "CT Clavicle"
* http://loinc.org#35962-0 "CT Elbow"
* http://loinc.org#35965-3 "CT Elbow - bilateral"
* http://loinc.org#35966-1 "CT Elbow - left"
* http://loinc.org#35968-7 "CT Elbow - right"
* http://loinc.org#35969-5 "CT Esophagus"
* http://loinc.org#35971-1 "CT Lower extremity"
* http://loinc.org#35973-7 "CT Lower extremity - bilateral"
* http://loinc.org#35976-0 "CT Lower extremity - left"
* http://loinc.org#35979-4 "CT Lower extremity - right"
* http://loinc.org#35981-0 "CT Upper extremity"
* http://loinc.org#35982-8 "CT Upper extremity - left"
* http://loinc.org#35983-6 "CT Upper extremity - right"
* http://loinc.org#35984-4 "CT Thigh"
* http://loinc.org#35987-7 "CT Thigh - left"
* http://loinc.org#35989-3 "CT Thigh - right"
* http://loinc.org#35991-9 "CT Foot"
* http://loinc.org#35993-5 "CT Foot - bilateral"
* http://loinc.org#35994-3 "CT Foot - left"
* http://loinc.org#35996-8 "CT Foot - right"
* http://loinc.org#35997-6 "CT Forearm"
* http://loinc.org#35998-4 "CT Forearm - bilateral"
* http://loinc.org#35999-2 "CT Forearm - left"
* http://loinc.org#36000-8 "CT Forearm - right"
* http://loinc.org#36002-4 "CT Hand"
* http://loinc.org#36004-0 "CT Hand - bilateral"
* http://loinc.org#36005-7 "CT Hand - left"
* http://loinc.org#36007-3 "CT Hand - right"
* http://loinc.org#36014-9 "CT Hip"
* http://loinc.org#36016-4 "CT Hip - bilateral"
* http://loinc.org#36018-0 "CT Hip - left"
* http://loinc.org#36021-4 "CT Hip - right"
* http://loinc.org#36023-0 "CT Upper arm"
* http://loinc.org#36026-3 "CT Upper arm - bilateral"
* http://loinc.org#36027-1 "CT Upper arm - left"
* http://loinc.org#36029-7 "CT Upper arm - right"
* http://loinc.org#36037-0 "CT Knee"
* http://loinc.org#36040-4 "CT Knee - bilateral"
* http://loinc.org#36041-2 "CT Knee - left"
* http://loinc.org#36043-8 "CT Knee - right"
* http://loinc.org#36047-9 "CT Mandible"
* http://loinc.org#36049-5 "CT Maxilla and Mandible"
* http://loinc.org#36050-3 "CT Maxilla"
* http://loinc.org#36051-1 "CT Neck"
* http://loinc.org#36054-5 "CT Brachial plexus"
* http://loinc.org#36055-2 "CT Posterior fossa"
* http://loinc.org#36057-8 "CT Prostate"
* http://loinc.org#36058-6 "CT Sacrum"
* http://loinc.org#36062-8 "CT Shoulder"
* http://loinc.org#36063-6 "CT Shoulder - bilateral"
* http://loinc.org#36064-4 "CT Shoulder - left"
* http://loinc.org#36066-9 "CT Shoulder - right"
* http://loinc.org#36071-9 "CT Sternum"
* http://loinc.org#36074-3 "CT Lower leg"
* http://loinc.org#36086-7 "CT Abdomen limited"
* http://loinc.org#36087-5 "CT Head limited"
* http://loinc.org#36089-1 "CT Chest limited"
* http://loinc.org#36090-9 "CT Extremity limited"
* http://loinc.org#36092-5 "CT Hip limited"
* http://loinc.org#36095-8 "CT Abdomen limited W contrast IV"
* http://loinc.org#36097-4 "CT Upper extremity limited W contrast IV"
* http://loinc.org#36098-2 "CT Pelvis limited W contrast IV"
* http://loinc.org#36099-0 "CT Cervical spine limited W contrast IV"
* http://loinc.org#36102-2 "CT Abdomen limited WO and W contrast IV"
* http://loinc.org#36103-0 "CT Abdomen limited WO contrast"
* http://loinc.org#36104-8 "CT Head limited WO contrast"
* http://loinc.org#36106-3 "CT Lower extremity limited WO contrast"
* http://loinc.org#36108-9 "CT Pelvis limited WO contrast"
* http://loinc.org#36109-7 "CT Cervical spine limited WO contrast"
* http://loinc.org#36110-5 "CT Lumbar spine limited WO contrast"
* http://loinc.org#36123-8 "CT Sacroiliac Joint Arthrogram"
* http://loinc.org#36124-6 "CT Knee Arthrogram"
* http://loinc.org#36128-7 "CT Shoulder Arthrogram"
* http://loinc.org#36131-1 "CT Shoulder - right Arthrogram"
* http://loinc.org#36135-2 "CT Ankle W contrast IV"
* http://loinc.org#36137-8 "CT Ankle - left W contrast IV"
* http://loinc.org#36139-4 "CT Ankle - right W contrast IV"
* http://loinc.org#36141-0 "CTA Thoracic and abdominal aorta W contrast IV"
* http://loinc.org#36142-8 "CT Thoracic and abdominal aorta W contrast IV"
* http://loinc.org#36143-6 "CT Abdominal Aorta W contrast IV"
* http://loinc.org#36144-4 "CTA Aortic arch W contrast IV"
* http://loinc.org#36145-1 "CT Appendix W contrast IV"
* http://loinc.org#36146-9 "CTA Carotid artery W contrast IV"
* http://loinc.org#36147-7 "CTA Pulmonary arteries W contrast IV"
* http://loinc.org#36157-6 "CT Elbow W contrast IV"
* http://loinc.org#36159-2 "CT Elbow - left W contrast IV"
* http://loinc.org#36161-8 "CT Elbow - right W contrast IV"
* http://loinc.org#36164-2 "CT Lower extremity - left W contrast IV"
* http://loinc.org#36166-7 "CT Lower extremity - right W contrast IV"
* http://loinc.org#36168-3 "CT Upper extremity - bilateral W contrast IV"
* http://loinc.org#36169-1 "CT Upper extremity - left W contrast IV"
* http://loinc.org#36170-9 "CT Upper extremity - right W contrast IV"
* http://loinc.org#36172-5 "CT Thigh W contrast IV"
* http://loinc.org#36174-1 "CT Thigh - left W contrast IV"
* http://loinc.org#36176-6 "CT Thigh - right W contrast IV"
* http://loinc.org#36178-2 "CT Foot W contrast IV"
* http://loinc.org#36181-6 "CT Foot - left W contrast IV"
* http://loinc.org#36183-2 "CT Foot - right W contrast IV"
* http://loinc.org#36185-7 "CT Forearm W contrast IV"
* http://loinc.org#36187-3 "CT Forearm - left W contrast IV"
* http://loinc.org#36189-9 "CT Forearm - right W contrast IV"
* http://loinc.org#36191-5 "CT Hand W contrast IV"
* http://loinc.org#36193-1 "CT Hand - left W contrast IV"
* http://loinc.org#36195-6 "CT Hand - right W contrast IV"
* http://loinc.org#36200-4 "CT Hip W contrast IV"
* http://loinc.org#36201-2 "CT Hip - bilateral W contrast IV"
* http://loinc.org#36203-8 "CT Hip - left W contrast IV"
* http://loinc.org#36205-3 "CT Hip - right W contrast IV"
* http://loinc.org#36207-9 "CT Upper arm W contrast IV"
* http://loinc.org#36209-5 "CT Upper arm - left W contrast IV"
* http://loinc.org#36211-1 "CT Upper arm - right W contrast IV"
* http://loinc.org#36217-8 "CT Sacroiliac Joint W contrast IV"
* http://loinc.org#36222-8 "CT Knee W contrast IV"
* http://loinc.org#36225-1 "CT Knee - left W contrast IV"
* http://loinc.org#36227-7 "CT Knee - right W contrast IV"
* http://loinc.org#36229-3 "CT Larynx W contrast IV"
* http://loinc.org#36232-7 "CT Mandible W contrast IV"
* http://loinc.org#36234-3 "CTA Neck vessels W contrast IV"
* http://loinc.org#36235-0 "CT Neck W contrast IV"
* http://loinc.org#36242-6 "CT Posterior fossa W contrast IV"
* http://loinc.org#36245-9 "CT Sacrum W contrast IV"
* http://loinc.org#36250-9 "CT Shoulder W contrast IV"
* http://loinc.org#36252-5 "CT Shoulder - left W contrast IV"
* http://loinc.org#36253-3 "CT Shoulder - right W contrast IV"
* http://loinc.org#36255-8 "CT Sinuses W contrast IV"
* http://loinc.org#36257-4 "CT Sternum W contrast IV"
* http://loinc.org#36258-2 "CT Lower leg W contrast IV"
* http://loinc.org#36260-8 "CT Lower leg - left W contrast IV"
* http://loinc.org#36262-4 "CT Lower leg - right W contrast IV"
* http://loinc.org#36264-0 "CT Uterus W contrast IV"
* http://loinc.org#36266-5 "CTA Chest vessels W contrast IV"
* http://loinc.org#36267-3 "CT Abdomen WO and W contrast IV"
* http://loinc.org#36268-1 "CT Ankle WO and W contrast IV"
* http://loinc.org#36269-9 "CT Ankle - left WO and W contrast IV"
* http://loinc.org#36270-7 "CT Ankle - right WO and W contrast IV"
* http://loinc.org#36271-5 "CT Abdominal Aorta WO and W contrast IV"
* http://loinc.org#36282-2 "CT Internal auditory canal WO and W contrast IV"
* http://loinc.org#36285-5 "CT Elbow WO and W contrast IV"
* http://loinc.org#36286-3 "CT Elbow - left WO and W contrast IV"
* http://loinc.org#36287-1 "CT Elbow - right WO and W contrast IV"
* http://loinc.org#36288-9 "CT Lower extremity WO and W contrast IV"
* http://loinc.org#36290-5 "CT Lower extremity - left WO and W contrast IV"
* http://loinc.org#36292-1 "CT Lower extremity - right WO and W contrast IV"
* http://loinc.org#36334-1 "CT Upper extremity WO and W contrast IV"
* http://loinc.org#36335-8 "CT Upper extremity - left WO and W contrast IV"
* http://loinc.org#36336-6 "CT Upper extremity - right WO and W contrast IV"
* http://loinc.org#36338-2 "CT Thigh WO and W contrast IV"
* http://loinc.org#36339-0 "CT Thigh - left WO and W contrast IV"
* http://loinc.org#36340-8 "CT Thigh - right WO and W contrast IV"
* http://loinc.org#36341-6 "CT Foot WO and W contrast IV"
* http://loinc.org#36343-2 "CT Foot - left WO and W contrast IV"
* http://loinc.org#36345-7 "CT Foot - right WO and W contrast IV"
* http://loinc.org#36347-3 "CT Forearm WO and W contrast IV"
* http://loinc.org#36348-1 "CT Forearm - left WO and W contrast IV"
* http://loinc.org#36350-7 "CT Forearm - right WO and W contrast IV"
* http://loinc.org#36352-3 "CT Hand WO and W contrast IV"
* http://loinc.org#36353-1 "CT Hand - left WO and W contrast IV"
* http://loinc.org#36355-6 "CT Hand - right WO and W contrast IV"
* http://loinc.org#36359-8 "CT Hip WO and W contrast IV"
* http://loinc.org#36360-6 "CT Hip - bilateral WO and W contrast IV"
* http://loinc.org#36362-2 "CT Hip - left WO and W contrast IV"
* http://loinc.org#36364-8 "CT Hip - right WO and W contrast IV"
* http://loinc.org#36366-3 "CT Upper arm WO and W contrast IV"
* http://loinc.org#36367-1 "CT Upper arm - left WO and W contrast IV"
* http://loinc.org#36369-7 "CT Upper arm - right WO and W contrast IV"
* http://loinc.org#36375-4 "CT Sacroiliac Joint WO and W contrast IV"
* http://loinc.org#36377-0 "CT Kidney - bilateral WO and W contrast IV"
* http://loinc.org#36379-6 "CT Knee WO and W contrast IV"
* http://loinc.org#36380-4 "CT Knee - left WO and W contrast IV"
* http://loinc.org#36381-2 "CT Knee - right WO and W contrast IV"
* http://loinc.org#36383-8 "CT Mandible WO and W contrast IV"
* http://loinc.org#36387-9 "CT Posterior fossa WO and W contrast IV"
* http://loinc.org#36390-3 "CT Sacrum WO and W contrast IV"
* http://loinc.org#36395-2 "CT Shoulder WO and W contrast IV"
* http://loinc.org#36396-0 "CT Shoulder - left WO and W contrast IV"
* http://loinc.org#36397-8 "CT Shoulder - right WO and W contrast IV"
* http://loinc.org#36398-6 "CT Sinuses WO and W contrast IV"
* http://loinc.org#36399-4 "CT Spine WO and W contrast IV"
* http://loinc.org#36401-8 "CT Cervical spine WO and W contrast IV"
* http://loinc.org#36402-6 "CT Lumbar spine WO and W contrast IV"
* http://loinc.org#36403-4 "CT Thoracic spine WO and W contrast IV"
* http://loinc.org#36405-9 "CT Sternum WO and W contrast IV"
* http://loinc.org#36408-3 "CT Lower leg WO and W contrast IV"
* http://loinc.org#36409-1 "CT Lower leg - left WO and W contrast IV"
* http://loinc.org#36411-7 "CT Lower leg - right WO and W contrast IV"
* http://loinc.org#36421-6 "CTA Upper extremity vessels WO and W contrast IV"
* http://loinc.org#36424-0 "CT Abdomen WO contrast"
* http://loinc.org#36425-7 "CT Ankle WO contrast"
* http://loinc.org#36426-5 "CT Ankle - left WO contrast"
* http://loinc.org#36428-1 "CT Ankle - right WO contrast"
* http://loinc.org#36430-7 "CT Thoracic and abdominal aorta WO contrast"
* http://loinc.org#36431-5 "CT Abdominal Aorta WO contrast"
* http://loinc.org#36434-9 "CT Appendix WO contrast"
* http://loinc.org#36443-0 "CT Elbow WO contrast"
* http://loinc.org#36444-8 "CT Elbow - bilateral WO contrast"
* http://loinc.org#36445-5 "CT Elbow - left WO contrast"
* http://loinc.org#36447-1 "CT Elbow - right WO contrast"
* http://loinc.org#36449-7 "CT Lower extremity - bilateral WO contrast"
* http://loinc.org#36452-1 "CT Lower extremity - left WO contrast"
* http://loinc.org#36454-7 "CT Lower extremity - right WO contrast"
* http://loinc.org#36456-2 "CT Upper extremity - bilateral WO contrast"
* http://loinc.org#36457-0 "CT Upper extremity - left WO contrast"
* http://loinc.org#36458-8 "CT Upper extremity - right WO contrast"
* http://loinc.org#36460-4 "CT Thigh WO contrast"
* http://loinc.org#36462-0 "CT Thigh - left WO contrast"
* http://loinc.org#36464-6 "CT Thigh - right WO contrast"
* http://loinc.org#36466-1 "CT Foot WO contrast"
* http://loinc.org#36468-7 "CT Foot - left WO contrast"
* http://loinc.org#36470-3 "CT Foot - right WO contrast"
* http://loinc.org#36472-9 "CT Forearm WO contrast"
* http://loinc.org#36473-7 "CT Forearm - left WO contrast"
* http://loinc.org#36475-2 "CT Forearm - right WO contrast"
* http://loinc.org#36477-8 "CT Hand WO contrast"
* http://loinc.org#36478-6 "CT Hand - left WO contrast"
* http://loinc.org#36480-2 "CT Hand - right WO contrast"
* http://loinc.org#36484-4 "CT Hip WO contrast"
* http://loinc.org#36485-1 "CT Hip - bilateral WO contrast"
* http://loinc.org#36487-7 "CT Hip - left WO contrast"
* http://loinc.org#36489-3 "CT Hip - right WO contrast"
* http://loinc.org#36491-9 "CT Upper arm WO contrast"
* http://loinc.org#36492-7 "CT Upper arm - left WO contrast"
* http://loinc.org#36494-3 "CT Upper arm - right WO contrast"
* http://loinc.org#36501-5 "CT Sacroiliac Joint WO contrast"
* http://loinc.org#36503-1 "CT Kidney - bilateral WO contrast"
* http://loinc.org#36505-6 "CT Knee WO contrast"
* http://loinc.org#36507-2 "CT Knee - left WO contrast"
* http://loinc.org#36509-8 "CT Knee - right WO contrast"
* http://loinc.org#36511-4 "CT Larynx WO contrast"
* http://loinc.org#36512-2 "CT Mandible WO contrast"
* http://loinc.org#36514-8 "CT Neck WO contrast"
* http://loinc.org#36517-1 "CT Posterior fossa WO contrast"
* http://loinc.org#36520-5 "CT Sacrum WO contrast"
* http://loinc.org#36524-7 "CT Shoulder WO contrast"
* http://loinc.org#36526-2 "CT Shoulder - left WO contrast"
* http://loinc.org#36527-0 "CT Shoulder - right WO contrast"
* http://loinc.org#36529-6 "CT Sinuses WO contrast"
* http://loinc.org#36530-4 "CT Spine WO contrast"
* http://loinc.org#36534-6 "CT Sternum WO contrast"
* http://loinc.org#36537-9 "CT Lower leg WO contrast"
* http://loinc.org#36538-7 "CT Lower leg - left WO contrast"
* http://loinc.org#36540-3 "CT Lower leg - right WO contrast"
* http://loinc.org#36767-2 "CT Guidance for biopsy of Adrenal gland"
* http://loinc.org#36768-0 "CT Guidance for percutaneous biopsy of Muscle"
* http://loinc.org#36769-8 "CT Guidance for exchange of nephrostomy tube of Kidney"
* http://loinc.org#36770-6 "CT Guidance for drainage of Biliary ducts and Gallbladder"
* http://loinc.org#36772-2 "CT Guidance for placement of nephrostomy tube in Kidney"
* http://loinc.org#36773-0 "CT Temporal bone"
* http://loinc.org#36809-2 "CTA Hepatic artery W contrast IA"
* http://loinc.org#36811-8 "CT Joint Arthrogram"
* http://loinc.org#36813-4 "CT Abdomen and Pelvis W contrast IV"
* http://loinc.org#36814-2 "CTA Head Arteries W contrast IV"
* http://loinc.org#36815-9 "CT Temporal bone W contrast IV"
* http://loinc.org#36816-7 "CT Temporal bone - right W contrast IV"
* http://loinc.org#36824-1 "CTA Lower extremity veins - left W contrast IV"
* http://loinc.org#36825-8 "CTA Lower extremity veins - right W contrast IV"
* http://loinc.org#36828-2 "CTA Abdominal vessels W contrast IV"
* http://loinc.org#36830-8 "CTA Head vessels W contrast IV"
* http://loinc.org#36831-6 "CTA Lower extremity vessels W contrast IV"
* http://loinc.org#36833-2 "CTA Renal vessels W contrast IV"
* http://loinc.org#36834-0 "CTA Vessel W contrast IV"
* http://loinc.org#36835-7 "CT Petrous part of temporal bone WO and W contrast IV"
* http://loinc.org#36837-3 "CT Temporal bone WO and W contrast IV"
* http://loinc.org#36866-2 "CT Temporal bone WO contrast"
* http://loinc.org#36867-0 "CT Temporal bone - left WO contrast"
* http://loinc.org#36868-8 "CT Temporal bone - right WO contrast"
* http://loinc.org#36926-4 "CT Guidance for aspiration and placement of drainage tube of Abdomen"
* http://loinc.org#36927-2 "CT Guidance for biopsy of Maxillofacial region"
* http://loinc.org#36928-0 "CT Guidance for stereotactic biopsy of Head"
* http://loinc.org#36929-8 "CT Guidance for stereotactic biopsy of Head-- WO contrast"
* http://loinc.org#36930-6 "CT Adrenal gland"
* http://loinc.org#36932-2 "CT Pituitary and Sella turcica"
* http://loinc.org#36934-8 "CT Heart for calcium scoring"
* http://loinc.org#36935-5 "CT Heart for calcium scoring W contrast IV"
* http://loinc.org#36937-1 "CT Maxillofacial region limited"
* http://loinc.org#36938-9 "CT Maxillofacial region limited WO contrast"
* http://loinc.org#36941-3 "CT Salivary gland W contrast intra salivary duct"
* http://loinc.org#36943-9 "CT Adrenal gland W contrast IV"
* http://loinc.org#36950-4 "CT Adrenal gland WO and W contrast IV"
* http://loinc.org#36952-0 "CT Abdomen and Pelvis WO contrast"
* http://loinc.org#36953-8 "CT Adrenal gland WO contrast"
* http://loinc.org#36955-3 "CT Thyroid gland WO contrast"
* http://loinc.org#37210-2 "CT Guidance for aspiration of cyst of Abdomen"
* http://loinc.org#37211-0 "CT Guidance for biopsy of Bone marrow"
* http://loinc.org#37212-8 "CT Guidance for biopsy of Epididymis"
* http://loinc.org#37213-6 "CT Guidance for biopsy of Mediastinum"
* http://loinc.org#37214-4 "CT Guidance for superficial biopsy of Tissue"
* http://loinc.org#37221-9 "CT Unspecified body region for fistula"
* http://loinc.org#37223-5 "CT Parotid gland"
* http://loinc.org#37225-0 "CT Sternoclavicular Joint"
* http://loinc.org#37226-8 "CT Temporomandibular joint"
* http://loinc.org#37232-6 "CT Spine lumbosacral junction"
* http://loinc.org#37237-5 "CT Sinus tract W contrast intra sinus tract"
* http://loinc.org#37238-3 "CT Lower Extremity Joint Arthrogram"
* http://loinc.org#37240-9 "CT Parotid gland W contrast IV"
* http://loinc.org#37242-5 "CT Sternoclavicular Joint W contrast IV"
* http://loinc.org#37243-3 "CT Temporomandibular joint W contrast IV"
* http://loinc.org#37246-6 "CT Temporomandibular joint - left W contrast IV"
* http://loinc.org#37248-2 "CT Temporomandibular joint - right W contrast IV"
* http://loinc.org#37266-4 "CT Sternoclavicular Joint WO and W contrast IV"
* http://loinc.org#37267-2 "CT Temporomandibular joint WO and W contrast IV"
* http://loinc.org#37280-5 "CT Parotid gland WO contrast"
* http://loinc.org#37282-1 "CT Sternoclavicular Joint WO contrast"
* http://loinc.org#37283-9 "CT Temporomandibular joint WO contrast"
* http://loinc.org#37288-8 "CT Spine lumbosacral junction WO contrast"
* http://loinc.org#37428-0 "CT Wrist"
* http://loinc.org#37430-6 "CT Wrist - bilateral"
* http://loinc.org#37431-4 "CT Wrist - left"
* http://loinc.org#37433-0 "CT Wrist - right"
* http://loinc.org#37439-7 "CT Lung parenchyma"
* http://loinc.org#37440-5 "CT Lung parenchyma W contrast IV"
* http://loinc.org#37441-3 "CT Lung parenchyma WO contrast"
* http://loinc.org#37447-0 "CT Wrist W contrast IV"
* http://loinc.org#37450-4 "CT Wrist - left W contrast IV"
* http://loinc.org#37452-0 "CT Wrist - right W contrast IV"
* http://loinc.org#37457-9 "CT Wrist WO and W contrast IV"
* http://loinc.org#37458-7 "CT Wrist - left WO and W contrast IV"
* http://loinc.org#37459-5 "CT Wrist WO contrast"
* http://loinc.org#37461-1 "CT Wrist - bilateral WO contrast"
* http://loinc.org#37463-7 "CT Wrist - left WO contrast"
* http://loinc.org#37465-2 "CT Wrist - right WO contrast"
* http://loinc.org#37491-8 "CT Guidance for fluid aspiration of Pleural space"
* http://loinc.org#37492-6 "CT Guidance for biopsy of Chest Pleura"
* http://loinc.org#37493-4 "CT Guidance for injection of Cervical spine Intervertebral disc"
* http://loinc.org#37495-9 "CT Skull base"
* http://loinc.org#37496-7 "CT Cervical spine W contrast intradisc"
* http://loinc.org#37498-3 "CTA Head vessels and Neck vessels W contrast IV"
* http://loinc.org#37509-7 "CT Lumbar spine W contrast intradisc"
* http://loinc.org#38767-0 "CT Internal auditory canal - right"
* http://loinc.org#38802-5 "CT Wrist - right WO and W contrast IV"
* http://loinc.org#38828-0 "CT Shoulder - left Arthrogram"
* http://loinc.org#38835-5 "CT Temporal bone - left W contrast IV"
* http://loinc.org#39026-0 "CT Guidance for needle localization of Unspecified body region"
* http://loinc.org#39046-8 "CT Pelvis limited for pelvimetry WO contrast"
* http://loinc.org#39142-5 "CT perfusion Head W contrast IV"
* http://loinc.org#39322-3 "CT Spine W contrast intradisc"
* http://loinc.org#41806-1 "CT Abdomen"
* http://loinc.org#41807-9 "CT Orbit"
* http://loinc.org#41808-7 "CT Maxillofacial region"
* http://loinc.org#42020-8 "CT Guidance for needle localization of Lumbar spine"
* http://loinc.org#42021-6 "CT Guidance for needle localization of Cervical spine"
* http://loinc.org#42136-2 "CT Guidance for biopsy of Heart"
* http://loinc.org#42260-0 "CT Guidance for biopsy of Unspecified body region-- W contrast IV"
* http://loinc.org#42265-9 "CT Guidance for superficial biopsy of Bone"
* http://loinc.org#42268-3 "CT Extremity WO and W contrast IV"
* http://loinc.org#42274-1 "CT Abdomen and Pelvis WO and W contrast IV"
* http://loinc.org#42275-8 "CT Chest and Abdomen W contrast IV"
* http://loinc.org#42276-6 "CT Chest and Abdomen WO contrast"
* http://loinc.org#42277-4 "CT Chest and Abdomen WO and W contrast IV"
* http://loinc.org#42278-2 "CT Extremity WO contrast"
* http://loinc.org#42279-0 "CT Guidance for biopsy of Kidney"
* http://loinc.org#42280-8 "CT Guidance for drainage of abscess of Appendix"
* http://loinc.org#42281-6 "CT Guidance for drainage of abscess of Chest"
* http://loinc.org#42282-4 "CT Guidance for drainage of abscess of Liver"
* http://loinc.org#42283-2 "CT Guidance for drainage of Pancreas"
* http://loinc.org#42284-0 "CT Guidance for drainage of abscess of Pleural space"
* http://loinc.org#42285-7 "CT Guidance for drainage of abscess of Kidney"
* http://loinc.org#42286-5 "CT Guidance for drainage of abscess of Pelvis"
* http://loinc.org#42287-3 "CT Guidance for drainage of Retroperitoneum"
* http://loinc.org#42291-5 "CT Retroperitoneum WO contrast"
* http://loinc.org#42293-1 "CTA Head vessels WO contrast"
* http://loinc.org#42294-9 "CTA Pelvis vessels W contrast IV"
* http://loinc.org#42295-6 "CTA Upper extremity vessels W contrast IV"
* http://loinc.org#42377-2 "CT perfusion Head W Xe-133 IH+WO and W contrast IV"
* http://loinc.org#42394-7 "CT Pulmonary system W Xe-133 IH"
* http://loinc.org#42688-2 "CT Guidance for nerve block of Spine"
* http://loinc.org#42701-3 "CT Guidance for localization of placenta of Uterus"
* http://loinc.org#43444-9 "CT Guidance for percutaneous drainage of abscess of Unspecified body region"
* http://loinc.org#43445-6 "CT Pulmonary system"
* http://loinc.org#43502-4 "CT Guidance for drainage of abscess of Subphrenic space"
* http://loinc.org#43525-5 "CT Unspecified body region WO contrast"
* http://loinc.org#43567-7 "CT Guidance for deep biopsy of Bone"
* http://loinc.org#43757-4 "CT Guidance for fine needle aspiration of Kidney"
* http://loinc.org#43766-5 "CT Kidney - bilateral W contrast IV"
* http://loinc.org#43767-3 "CT Kidney - bilateral"
* http://loinc.org#43768-1 "CT Kidney WO and W contrast IV"
* http://loinc.org#43770-7 "CT Kidney WO contrast"
* http://loinc.org#44101-4 "CT Guidance for ablation of tissue of Liver"
* http://loinc.org#44102-2 "CT Guidance for procedure of Joint space"
* http://loinc.org#44103-0 "CT Guidance for fine needle aspiration of Lymph node"
* http://loinc.org#44104-8 "CT Guidance for fine needle aspiration of Mediastinum"
* http://loinc.org#44105-5 "CT Guidance for fine needle aspiration of Muscle"
* http://loinc.org#44106-3 "CT Guidance for FNA of Prostate"
* http://loinc.org#44107-1 "CT Guidance for fine needle aspiration of Retroperitoneum"
* http://loinc.org#44108-9 "CT Guidance for fine needle aspiration of Adrenal gland"
* http://loinc.org#44109-7 "CT Guidance for deep biopsy of Muscle"
* http://loinc.org#44110-5 "CT Guidance for needle localization of Breast"
* http://loinc.org#44111-3 "CT Skull base WO and W contrast IV"
* http://loinc.org#44112-1 "CT Skull base WO contrast"
* http://loinc.org#44113-9 "CT Thoracic spine WO and W contrast IT"
* http://loinc.org#44114-7 "CT Lumbar spine WO and W contrast IT"
* http://loinc.org#44115-4 "CT Abdomen and Pelvis"
* http://loinc.org#44116-2 "CT Mandible limited"
* http://loinc.org#44117-0 "CT Guidance for biopsy of Retroperitoneum"
* http://loinc.org#44118-8 "CT Guidance for needle localization of Breast-- WO and W contrast IV"
* http://loinc.org#44119-6 "CT Breast - bilateral WO contrast"
* http://loinc.org#44228-5 "CT Guidance for ablation of tissue of Kidney"
* http://loinc.org#44229-3 "CT Bone"
* http://loinc.org#46281-2 "CT Guidance for aspiration or injection of cyst of Unspecified body region"
* http://loinc.org#46289-5 "CT Guidance for biopsy of Unspecified body region-- WO and W contrast IV"
* http://loinc.org#46290-3 "CT Guidance for biopsy of Unspecified body region-- WO contrast"
* http://loinc.org#46291-1 "CT Guidance for drainage of Unspecified body region-- WO and W contrast IV"
* http://loinc.org#46292-9 "CT Guidance for drainage of Unspecified body region-- W contrast IV"
* http://loinc.org#46293-7 "CT Guidance for drainage of Unspecified body region-- WO contrast"
* http://loinc.org#46298-6 "CT Mastoid - bilateral"
* http://loinc.org#46304-2 "CT Sinuses limited WO contrast"
* http://loinc.org#46305-9 "CT Whole body"
* http://loinc.org#46306-7 "CT Whole body W contrast IV"
* http://loinc.org#46307-5 "CTA Lower extremity vessels - right WO and W contrast IV"
* http://loinc.org#46308-3 "CTA Lower extremity vessels - left WO and W contrast IV"
* http://loinc.org#46309-1 "CTA Upper extremity vessels - right WO and W contrast IV"
* http://loinc.org#46311-7 "CT Parotid gland WO and W contrast IV"
* http://loinc.org#46312-5 "CTA Upper extremity vessels - left WO and W contrast IV"
* http://loinc.org#46313-3 "CT Pelvis WO and W reduced contrast volume IV"
* http://loinc.org#46314-1 "CT Internal auditory canal WO and W reduced contrast volume IV"
* http://loinc.org#46315-8 "CT Maxillofacial region WO and W reduced contrast volume IV"
* http://loinc.org#46316-6 "CT Head WO and W reduced contrast volume IV"
* http://loinc.org#46317-4 "CT Chest WO and W reduced contrast volume IV"
* http://loinc.org#46318-2 "CT Abdomen WO and W reduced contrast volume IV"
* http://loinc.org#46320-8 "CT Orbit and Face W contrast IV"
* http://loinc.org#46322-4 "CT Kidney W contrast IV"
* http://loinc.org#46325-7 "CT Internal auditory canal W reduced contrast volume IV"
* http://loinc.org#46326-5 "CT Maxillofacial region W reduced contrast volume IV"
* http://loinc.org#46327-3 "CT Chest W reduced contrast volume IV"
* http://loinc.org#46328-1 "CT Head W reduced contrast volume IV"
* http://loinc.org#46329-9 "CT Pelvis W reduced contrast volume IV"
* http://loinc.org#46330-7 "CT Abdomen W reduced contrast volume IV"
* http://loinc.org#46331-5 "CT Orbit WO contrast"
* http://loinc.org#46365-3 "CT Guidance for ablation of tissue of Celiac plexus"
* http://loinc.org#46393-5 "CT Liver W Xe-133 IH"
* http://loinc.org#47366-0 "CT Chest limited WO contrast"
* http://loinc.org#47985-7 "CT Spine W contrast IT"
* http://loinc.org#48442-8 "CT Spine WO and W contrast IT"
* http://loinc.org#48443-6 "CT Nasopharynx WO and W contrast IV"
* http://loinc.org#48446-9 "CT Nasopharynx W contrast IV"
* http://loinc.org#48449-3 "CT Orbit W contrast IV"
* http://loinc.org#48451-9 "CT Orbit WO and W contrast IV"
* http://loinc.org#48743-9 "CT Retroperitoneum WO and W contrast IV"
* http://loinc.org#50755-8 "CT Lower extremity - bilateral W contrast IV"
* http://loinc.org#52790-3 "CT Guidance for percutaneous replacement of drainage tube of Abdomen"
* http://loinc.org#52791-1 "CT Guidance for percutaneous replacement of drainage tube of Pelvis"
* http://loinc.org#58744-4 "CT Heart"
* http://loinc.org#58747-7 "CT Guidance for ablation of tissue of Unspecified body region"
* http://loinc.org#60515-4 "CT Colon and Rectum W air contrast PR"
* http://loinc.org#69083-4 "CT Guidance for biopsy of Abdomen-- WO contrast"
* http://loinc.org#69084-2 "CTA Chest vessels WO contrast"
* http://loinc.org#69087-5 "CT Ankle - bilateral WO contrast"
* http://loinc.org#69088-3 "CT Knee - bilateral W contrast IV"
* http://loinc.org#69089-1 "CT Knee - bilateral WO contrast"
* http://loinc.org#69090-9 "CT Shoulder - bilateral WO contrast"
* http://loinc.org#69091-7 "CT Wrist - bilateral W contrast IV"
* http://loinc.org#69092-5 "CT Guidance for biopsy of Liver-- WO contrast"
* http://loinc.org#69093-3 "CT Guidance for biopsy of Pelvis-- W contrast IV"
* http://loinc.org#69094-1 "CT Guidance for biopsy of Pelvis-- WO contrast"
* http://loinc.org#69095-8 "CT Urinary bladder W contrast IV"
* http://loinc.org#69096-6 "CT Chest limited W contrast IV"
* http://loinc.org#69102-2 "CT Ankle - left Arthrogram"
* http://loinc.org#69103-0 "CT Elbow - left Arthrogram"
* http://loinc.org#69104-8 "CT Extremity - left WO contrast"
* http://loinc.org#69105-5 "CT Hip - left Arthrogram"
* http://loinc.org#69106-3 "CT Knee - left Arthrogram"
* http://loinc.org#69107-1 "CT Wrist - left Arthrogram"
* http://loinc.org#69109-7 "CT Ankle - right Arthrogram"
* http://loinc.org#69110-5 "CT Elbow - right Arthrogram"
* http://loinc.org#69111-3 "CT Extremity - right WO contrast"
* http://loinc.org#69112-1 "CT Hip - right Arthrogram"
* http://loinc.org#69113-9 "CT Kidney - right"
* http://loinc.org#69114-7 "CT Knee - right Arthrogram"
* http://loinc.org#69115-4 "CT Wrist - right Arthrogram"
* http://loinc.org#69116-2 "CT Sacrum and Coccyx"
* http://loinc.org#69117-0 "CT Scapula"
* http://loinc.org#69118-8 "CT Scapula WO contrast"
* http://loinc.org#69119-6 "CTA Thoracic Aorta WO contrast"
* http://loinc.org#69908-2 "CTA Abdominal and Pelvic vessels W contrast IV"
* http://loinc.org#70921-2 "CT Guidance for nerve block of Cervical spine"
* http://loinc.org#70922-0 "CT Guidance for nerve block of Thoracic spine"
* http://loinc.org#70931-1 "CT Thoracic spine W contrast intradisc"
* http://loinc.org#72249-6 "CT Facial bones WO contrast"
* http://loinc.org#72250-4 "CT Small bowel W contrast PO and W contrast IV"
* http://loinc.org#72251-2 "CT Pulmonary arteries for pulmonary embolus"
* http://loinc.org#72252-0 "CT Chest and Abdomen and Pelvis WO and W contrast IV"
* http://loinc.org#72253-8 "CT Chest and Abdomen and Pelvis WO contrast"
* http://loinc.org#72254-6 "CT Chest and Abdomen and Pelvis W contrast IV"
* http://loinc.org#72531-7 "CT Colon and Rectum W contrast IV and W air contrast PR"
* http://loinc.org#75671-8 "CTA Circle of Willis WO and W contrast IV"
* http://loinc.org#75746-8 "CT Guidance for drainage of abscess of Pleural space - bilateral"
* http://loinc.org#75748-4 "CT Guidance for fluid aspiration of Cervical spine Intervertebral disc"
* http://loinc.org#75752-6 "CT Guidance for drainage of abscess of Pleural space - left"
* http://loinc.org#75818-5 "CT Guidance for drainage of abscess of Pleural space - right"
* http://loinc.org#77311-9 "CTA Abdominal aorta and Bilateral vessels for endograft"
* http://loinc.org#77448-9 "CT Hindfoot and Midfoot"
* http://loinc.org#77451-3 "CTA Thoracic and Abdominal Aorta and Bilateral Vessels for endograft"
* http://loinc.org#77456-2 "CT Hindfoot and Midfoot W contrast IV"
* http://loinc.org#77457-0 "CT Hindfoot and Midfoot WO and W contrast IV"
* http://loinc.org#77458-8 "CT Hindfoot and Midfoot WO contrast"
* http://loinc.org#77466-1 "CT Hindfoot - left and Midfoot - left W contrast IV"
* http://loinc.org#77467-9 "CT Hindfoot - right and Midfoot - right W contrast IV"
* http://loinc.org#77468-7 "CT Hindfoot - left and Midfoot - left WO and W contrast IV"
* http://loinc.org#77469-5 "CT Hindfoot - right and Midfoot - right WO and W contrast IV"
* http://loinc.org#77470-3 "CT Hindfoot - left and Midfoot - left WO contrast"
* http://loinc.org#77471-1 "CT Hindfoot - right and Midfoot - right WO contrast"
* http://loinc.org#78031-2 "CTA Abdominal Aorta and Bilateral Runoff Vessels WO and W contrast IV"
* http://loinc.org#78032-0 "CTA Thoracic and Abdominal Aorta and Bilateral Runoff Vessels WO and W contrast IV"
* http://loinc.org#78037-9 "CTA Abdominal Aorta and Bilateral Runoff Vessels W contrast IV"
* http://loinc.org#78038-7 "CTA Thoracic and Abdominal Aorta and Bilateral Runoff Vessels W contrast IV"
* http://loinc.org#78973-5 "CT scanogram Lower extremity - bilateral for leg measurement WO contrast"
* http://loinc.org#79065-9 "CT Abdomen and Pelvis 3D post processing WO contrast"
* http://loinc.org#79066-7 "CT Abdomen 3D post processing WO contrast"
* http://loinc.org#79067-5 "CT Airway WO contrast"
* http://loinc.org#79068-3 "CT Chest for screening W contrast IV"
* http://loinc.org#79069-1 "CT Colon and Rectum for screening WO contrast IV and W air contrast PR"
* http://loinc.org#79071-7 "CT Colon and Rectum WO contrast IV and W air contrast PR"
* http://loinc.org#79072-5 "CT Guidance for radiation treatment of Unspecified body region"
* http://loinc.org#79073-3 "CTA Heart and Coronary arteries W contrast IV"
* http://loinc.org#79074-1 "CT Kidney and Ureter and Urinary bladder 3D post processing WO and W contrast IV"
* http://loinc.org#79075-8 "CT Pelvis by reconstruction W contrast IV"
* http://loinc.org#79076-6 "CT Pelvis by reconstruction WO contrast"
* http://loinc.org#79077-4 "CTA Pulmonary arteries for pulmonary embolus W contrast IV"
* http://loinc.org#79078-2 "CT Cervical spine by reconstruction W contrast IV"
* http://loinc.org#79079-0 "CT Cervical spine by reconstruction WO contrast"
* http://loinc.org#79080-8 "CT Lumbar spine by reconstruction W contrast IV"
* http://loinc.org#79081-6 "CT Lumbar spine by reconstruction WO contrast"
* http://loinc.org#79082-4 "CT Thoracic spine by reconstruction W contrast IV"
* http://loinc.org#79083-2 "CT Temporal bone by reconstruction W contrast IV"
* http://loinc.org#79084-0 "CT Temporal bone by reconstruction WO contrast"
* http://loinc.org#79085-7 "CT Biliary ducts WO and W contrast IV"
* http://loinc.org#79086-5 "CT Chest for screening WO contrast"
* http://loinc.org#79087-3 "CT Heart and Coronary arteries for calcium scoring WO contrast"
* http://loinc.org#79088-1 "CT Heart for congenital disease W contrast IV"
* http://loinc.org#79089-9 "CT Heart W contrast IV"
* http://loinc.org#79090-7 "CT densitometry Lumbar spine WO contrast"
* http://loinc.org#79091-5 "CT Thoracic spine by reconstruction WO contrast"
* http://loinc.org#79092-3 "CT densitometry Thoracic spine WO contrast"
* http://loinc.org#79093-1 "CT Unspecified body region 3D post processing"
* http://loinc.org#79094-9 "CT Urinary bladder W contrast intra bladder"
* http://loinc.org#79095-6 "CT Teeth"
* http://loinc.org#79096-4 "CT Chest 3D post processing WO contrast"
* http://loinc.org#79097-2 "CT Chest and Abdomen 3D post processing WO contrast"
* http://loinc.org#79098-0 "CT Chest and Abdomen and Pelvis 3D post processing WO contrast"
* http://loinc.org#79099-8 "CT Pelvis 3D post processing WO contrast"
* http://loinc.org#79101-2 "CT Colon and Rectum for screening W air contrast PR"
* http://loinc.org#79103-8 "CT Abdomen W contrast IV"
* http://loinc.org#82132-2 "CT Face and Neck WO and W contrast IV"
* http://loinc.org#82133-0 "CT Face and Neck WO contrast"
* http://loinc.org#82676-8 "CT Guidance for fluid aspiration of Knee - left"
* http://loinc.org#82677-6 "CTA Abdominal Aorta W contrast IV"
* http://loinc.org#82678-4 "CTA Abdominal Aorta WO and W contrast IV"
* http://loinc.org#82679-2 "CTA Abdominal vessels and Pelvis vessels WO and W contrast IV"
* http://loinc.org#82680-0 "CTA Head vessels and Neck vessels WO and W contrast IV"
* http://loinc.org#82681-8 "CT Guidance for biopsy of Oral tissue"
* http://loinc.org#82682-6 "CT Clavicle - left WO contrast"
* http://loinc.org#82683-4 "CT Clavicle - right WO contrast"
* http://loinc.org#82684-2 "CT Clavicle WO and W contrast IV"
* http://loinc.org#82685-9 "CT Clavicle W contrast IV"
* http://loinc.org#82686-7 "CT Clavicle - right W contrast IV"
* http://loinc.org#82687-5 "CT Clavicle WO contrast"
* http://loinc.org#82688-3 "CT Colon and Rectum WO and W contrast IV and W air contrast PR"
* http://loinc.org#82689-1 "CT Small bowel W contrast PO and WO and W contrast IV"
* http://loinc.org#82690-9 "CT Head and Cervical spine WO contrast"
* http://loinc.org#82691-7 "CT Head and Neck W contrast IV"
* http://loinc.org#82692-5 "CT Head and Neck WO contrast"
* http://loinc.org#82693-3 "CT Pelvis and Lower extremity W contrast IV"
* http://loinc.org#82694-1 "CT Lower extremity - bilateral WO and W contrast IV"
* http://loinc.org#82695-8 "CT Pelvis and Lower extremity - bilateral W contrast IV"
* http://loinc.org#82696-6 "CT Spine Lumbar and Sacrum W contrast IV"
* http://loinc.org#82697-4 "CT Spine Lumbar and Sacrum WO contrast"
* http://loinc.org#82698-2 "CT Ribs - left W contrast IV"
* http://loinc.org#82699-0 "CT Ribs - left WO contrast"
* http://loinc.org#82700-6 "CT Ribs - right W contrast IV"
* http://loinc.org#82701-4 "CT Ribs - right WO contrast"
* http://loinc.org#82702-2 "CT Ribs - right WO and W contrast IV"
* http://loinc.org#82703-0 "CT Sacrum and Coccyx WO and W contrast IV"
* http://loinc.org#82704-8 "CT Sacrum and Coccyx W contrast IV"
* http://loinc.org#82705-5 "CT Scapula - left WO contrast"
* http://loinc.org#82706-3 "CT Scapula - right WO contrast"
* http://loinc.org#82707-1 "CT Scapula - left WO and W contrast IV"
* http://loinc.org#82708-9 "CTA Lower extremity vessels - bilateral WO and W contrast IV"
* http://loinc.org#82709-7 "CTA Thoracic Aorta"
* http://loinc.org#82710-5 "CTA Lower extremity vessels - right"
* http://loinc.org#82711-3 "CTA Lower extremity vessels - bilateral"
* http://loinc.org#82712-1 "CTA Lower extremity vessels - left"
* http://loinc.org#82713-9 "CTA Upper extremity vessels - left"
* http://loinc.org#82714-7 "CTA Upper extremity vessels - right"
* http://loinc.org#82715-4 "CT Guidance for fluid aspiration of Knee - right"
* http://loinc.org#82716-2 "CT Clavicle - left W contrast IV"
* http://loinc.org#82717-0 "CT Ribs - left WO and W contrast IV"
* http://loinc.org#82718-8 "CT Scapula - right WO and W contrast IV"
* http://loinc.org#82742-8 "CT Head WO and W contrast IV and CT Orbit - bilateral W contrast IV"
* http://loinc.org#82802-0 "CT Head WO and W contrast IV and CT Sinuses W contrast IV"
* http://loinc.org#82803-8 "CT Head WO and W contrast IV and CT Temporal bone W contrast IV"
* http://loinc.org#82804-6 "CT Head WO and W contrast IV and CT Neck W contrast IV"
* http://loinc.org#83289-9 "CT for calcium scoring WO contrast and CTA W contrast IV Heart and coronary arteries"
* http://loinc.org#83290-7 "CTA Pulmonary arteries - bilateral and Pelvis veins and Lower extremity veins - bilateral for pulmonary embolus and deep vein thrombosis W contrast IV"
* http://loinc.org#83291-5 "CT Thumb WO contrast"
* http://loinc.org#83292-3 "CT Scapula W contrast"
* http://loinc.org#83293-1 "CT Spine Cervical and Spine Lumbar W contrast IV"
* http://loinc.org#83294-9 "CT Thoracic and lumbar spine W contrast IV"
* http://loinc.org#83295-6 "CT Neck and Superior mediastinum W contrast IV"
* http://loinc.org#83296-4 "CT Head W contrast IV and CT Orbit - bilateral WO and W contrast IV"
* http://loinc.org#83297-2 "CT Spine Cervical and Spine Lumbar WO and W contrast IV"
* http://loinc.org#83298-0 "CTA Chest vessels and Abdominal vessels and Pelvis vessels WO and W contrast IV"
* http://loinc.org#83299-8 "CT Chest and Abdomen and Pelvis WO and W contrast IV and CTA Thoracic and abdominal aorta WO and W contrast IV"
* http://loinc.org#83300-4 "CT Scapula - bilateral WO and W contrast IV"
* http://loinc.org#83301-2 "CT Neck and Superior mediastinum WO and W contrast IV"
* http://loinc.org#83302-0 "CT Head and Temporal bone WO contrast"
* http://loinc.org#83303-8 "CT Toe WO contrast"
* http://loinc.org#83304-6 "CT Cervical and thoracic spine WO contrast"
* http://loinc.org#83305-3 "CT Spine Cervical and Spine Lumbar WO contrast"
* http://loinc.org#83306-1 "CT Head and Maxillofacial region WO contrast"
* http://loinc.org#83307-9 "CT Head and Mandible WO contrast"
* http://loinc.org#83308-7 "CT Neck and Superior mediastinum WO contrast"
* http://loinc.org#83309-5 "CT Sinuses and Mandible WO contrast"
* http://loinc.org#83310-3 "CT Thoracic and lumbar spine WO contrast"
* http://loinc.org#85040-4 "CT Unspecified body region 3D printed model"
* http://loinc.org#86956-0 "CT Heart WO contrast IV and CT Heart for left ventricular function W contrast IV"
* http://loinc.org#86957-8 "CT Salivary gland WO and W contrast IV"
* http://loinc.org#86958-6 "CT Neck and Chest WO and W contrast IV"
* http://loinc.org#86959-4 "CT Cervical and thoracic spine WO and W contrast IV"
* http://loinc.org#86960-2 "CTA Upper extremity vessels - right W contrast IV"
* http://loinc.org#86961-0 "CTA Upper extremity vessels - left W contrast IV"
* http://loinc.org#86962-8 "CTA Upper extremity vessels - bilateral W contrast IV"
* http://loinc.org#86963-6 "CTA Lower extremity vessels - right W contrast IV"
* http://loinc.org#86964-4 "CTA Lower extremity vessels - left W contrast IV"
* http://loinc.org#86965-1 "CTA Lower extremity vessels - bilateral W contrast IV"
* http://loinc.org#86966-9 "CT Salivary gland WO contrast"
* http://loinc.org#86967-7 "CT Foot - bilateral WO contrast"
* http://loinc.org#86968-5 "CT Hand - bilateral W contrast IV"
* http://loinc.org#86969-3 "CT Shoulder - bilateral W contrast IV"
* http://loinc.org#86970-1 "CT Sacrum and Coccyx WO contrast"
* http://loinc.org#86971-9 "CTA Chest and abdominal vessels WO and W contrast IV"
* http://loinc.org#86972-7 "CT Head and Neck WO and W contrast IV"
* http://loinc.org#86973-5 "CT Foot - bilateral W contrast IV"
* http://loinc.org#86974-3 "CT Thoracic and lumbar spine WO and W contrast IV"
* http://loinc.org#86975-0 "CT Heart for left ventricular function W contrast IV"
* http://loinc.org#86977-6 "CT Head and Temporal bone W contrast IV"
* http://loinc.org#86978-4 "CT Head and Sinuses W contrast IV"
* http://loinc.org#86979-2 "CT Pelvis and Hip - bilateral WO contrast"
* http://loinc.org#86980-0 "CTA Heart and Coronary arteries WO and W contrast IV"
* http://loinc.org#86981-8 "CTA Chest vessels"
* http://loinc.org#86982-6 "CTA Chest and abdominal vessels W contrast IV"
* http://loinc.org#86983-4 "CTA Chest vessels and Abdominal vessels and Pelvis vessels W contrast IV"
* http://loinc.org#86984-2 "CT Cervical and thoracic and lumbar spine W contrast IV"
* http://loinc.org#86985-9 "CT Cervical and thoracic spine W contrast IV"
* http://loinc.org#86986-7 "CT Neck and Chest W contrast IV"
* http://loinc.org#86987-5 "CT Cervical and thoracic and lumbar spine WO contrast"
* http://loinc.org#86988-3 "CT Orbit and Face WO contrast"
* http://loinc.org#86989-1 "CT Head and Orbit - bilateral W contrast IV"
* http://loinc.org#86990-9 "CT Head and Orbit - bilateral WO contrast"
* http://loinc.org#86991-7 "CT Head and Maxillofacial region and Cervical spine WO contrast"
* http://loinc.org#86992-5 "CT Head and Sinuses WO contrast"
* http://loinc.org#87279-6 "CT Chest for screening"
* http://loinc.org#87280-4 "CTA Abdominal veins and Pelvis veins and Lower extremity veins - bilateral W contrast IV"
* http://loinc.org#87281-2 "CTA Lower extremity veins - bilateral W contrast IV"
* http://loinc.org#87836-3 "CTA Hepatic vessels WO and W contrast IV"
* http://loinc.org#87837-1 "CTA Aortic valve W contrast IV"
* http://loinc.org#87838-9 "CTA Abdominal veins and Pelvis veins W contrast IV"
* http://loinc.org#87839-7 "CTA Pulmonary veins W contrast IV"
* http://loinc.org#87840-5 "CTA Coronary arteries and Pulmonary arteries W contrast IV"
* http://loinc.org#87841-3 "CTA Coronary arteries and Thoracic aorta W contrast IV"
* http://loinc.org#87842-1 "CTA Coronary arteries and Pulmonary arteries and Thoracic aorta W contrast IV"
* http://loinc.org#87843-9 "CTA Pelvis veins and Lower extremity veins - bilateral"
* http://loinc.org#87844-7 "CTA Pelvis veins"
* http://loinc.org#87845-4 "CTA Lower extremity vessels"
* http://loinc.org#87846-2 "CTA Renal vessels WO and W contrast IV"
* http://loinc.org#87847-0 "CT Chest WO and CT angiogram Coronary arteries W contrast IV"
* http://loinc.org#87848-8 "CTA Pulmonary arteries - bilateral and Lower extremity veins - bilateral for pulmonary embolus and deep vein thrombosis W contrast IV"
* http://loinc.org#87849-6 "CTA Pulmonary arteries - bilateral and Lower extremity veins - bilateral for pulmonary embolus and deep vein thrombosis"
* http://loinc.org#87850-4 "CTA Deep inferior epigastric artery WO and W contrast IV"
* http://loinc.org#87851-2 "CTA Mesenteric vessels W contrast IV"
* http://loinc.org#87852-0 "CTA Mesenteric vessels WO and W contrast IV"
* http://loinc.org#87853-8 "CT Abdomen and Pelvis and CT angiogram Abdominal aorta WO and W contrast IV"
* http://loinc.org#87854-6 "CT Abdomen and Pelvis and CT angiogram Abdominal aorta W contrast IV"
* http://loinc.org#87855-3 "CTA Circle of Willis and Carotid arteries WO and W contrast IV"
* http://loinc.org#87856-1 "CTA Circle of Willis and Carotid arteries W contrast IV"
* http://loinc.org#87857-9 "CTA Thoracic and abdominal aorta WO and W contrast IV"
* http://loinc.org#87858-7 "CTA Deep inferior epigastric artery W contrast IV"
* http://loinc.org#87859-5 "CT Thoracic Aorta WO and W contrast IV"
* http://loinc.org#87860-3 "CT Thoracic Aorta WO contrast"
* http://loinc.org#87861-1 "CT Thoracic and abdominal aorta WO and W contrast IV"
* http://loinc.org#87862-9 "CT Abdomen WO and CT Abdomen and Pelvis W contrast IV"
* http://loinc.org#87863-7 "CT Abdomen WO and CT Chest and Abdomen W contrast IV"
* http://loinc.org#87864-5 "CT Abdomen WO and CT Chest and Abdomen and Pelvis W contrast IV"
* http://loinc.org#87865-2 "CT Abdomen and Pelvis WO and CT Chest and Abdomen and Pelvis W contrast IV"
* http://loinc.org#87866-0 "CT Kidney and Ureter and Urinary bladder WO and W contrast IV"
* http://loinc.org#87867-8 "CT Lumbar spine by reconstruction"
* http://loinc.org#87868-6 "CT Lumbar spine by reconstruction WO and W contrast IV"
* http://loinc.org#87869-4 "CT Chest and Abdomen and Pelvis"
* http://loinc.org#87870-2 "CT Spine Cervical and Thoracic and Lumbar and Sacrum and Coccyx WO and W contrast IV"
* http://loinc.org#87871-0 "CT Clavicle - left"
* http://loinc.org#87872-8 "CT Clavicle - right"
* http://loinc.org#87873-6 "CT Lung parenchyma WO and W contrast IV"
* http://loinc.org#87874-4 "CT Mediastinum W contrast IV"
* http://loinc.org#87875-1 "CT Thoracic spine by reconstruction"
* http://loinc.org#87876-9 "CT Thymus gland"
* http://loinc.org#87877-7 "CT Neck and Chest WO contrast"
* http://loinc.org#87878-5 "CT Knee - bilateral Arthrogram"
* http://loinc.org#87879-3 "CT Lower leg - bilateral WO contrast"
* http://loinc.org#87880-1 "CT Thigh - bilateral W contrast IV"
* http://loinc.org#87881-9 "CT Thigh - bilateral WO contrast"
* http://loinc.org#87882-7 "CT Lower leg - left"
* http://loinc.org#87883-5 "CT Upper extremity - bilateral WO and W contrast IV"
* http://loinc.org#87884-3 "CT Shoulder - bilateral Arthrogram"
* http://loinc.org#87885-0 "CT Upper arm - bilateral WO contrast"
* http://loinc.org#87886-8 "CT Finger fifth - left WO contrast"
* http://loinc.org#87887-6 "CT Finger fourth - left W contrast IV"
* http://loinc.org#87888-4 "CT Finger second - left WO contrast"
* http://loinc.org#87889-2 "CT Thumb - left WO contrast"
* http://loinc.org#87890-0 "CT Finger fifth - right WO contrast"
* http://loinc.org#87891-8 "CT Finger fourth - right WO contrast"
* http://loinc.org#87892-6 "CT Finger second - right WO contrast"
* http://loinc.org#87893-4 "CT Finger third - right WO contrast"
* http://loinc.org#87894-2 "CT Thumb - right WO contrast"
* http://loinc.org#87895-9 "CT Finger WO contrast"
* http://loinc.org#87896-7 "CT Teeth W contrast IV"
* http://loinc.org#87897-5 "CT Head and Pituitary and Sella turcica W contrast IV"
* http://loinc.org#87898-3 "CT Teeth.maxilla WO contrast"
* http://loinc.org#87899-1 "CT Teeth.mandible WO contrast"
* http://loinc.org#87900-7 "CT Mastoid W contrast IV"
* http://loinc.org#87901-5 "CT Temporal bone - bilateral WO and W contrast IV"
* http://loinc.org#87902-3 "CT Temporal bone - bilateral W contrast IV"
* http://loinc.org#87903-1 "CT Temporal bone - bilateral WO contrast"
* http://loinc.org#87904-9 "CT Temporomandibular joint - bilateral WO contrast"
* http://loinc.org#87906-4 "CT Maxillofacial region - right W contrast IV"
* http://loinc.org#87908-0 "CT Head and Maxillofacial region W contrast IV"
* http://loinc.org#87909-8 "CT Temporomandibular joint Arthrogram"
* http://loinc.org#87910-6 "CT Head and Sinuses WO and W contrast IV"
* http://loinc.org#87911-4 "CT Head and Maxillofacial region WO and W contrast IV"
* http://loinc.org#87912-2 "CT Sinuses and Orbit WO contrast"
* http://loinc.org#87913-0 "CT Pelvis by reconstruction"
* http://loinc.org#87914-8 "CT Pelvis bones WO and W contrast IV"
* http://loinc.org#87916-3 "CT Guidance for injection of cyst of Unspecified body region"
* http://loinc.org#87917-1 "CT Pelvis bones WO contrast"
* http://loinc.org#87918-9 "CT Parathyroid gland WO and W contrast IV"
* http://loinc.org#87919-7 "CT Pelvis bones"
* http://loinc.org#87920-5 "CT Pelvis bones W contrast IV"
* http://loinc.org#87921-3 "CT Trachea WO contrast"
* http://loinc.org#87922-1 "CT Cervical and thoracic spine W contrast IT"
* http://loinc.org#88315-7 "CT Head WO contrast and CT Brain for perfusion W contrast IV and CT angiogram Head and neck vessels W contrast IV"
* http://loinc.org#88316-5 "CT Guidance for biopsy of Spinal cord"
* http://loinc.org#88317-3 "CT Guidance for fluid aspiration of Chest"
* http://loinc.org#88318-1 "CTA Coronary arteries and Pulmonary veins W contrast IV"
* http://loinc.org#88319-9 "CT Abdomen and Pelvis and Lower extremity - bilateral W contrast IV"
* http://loinc.org#88320-7 "CT Neck W contrast IV and CT angiogram Head and neck vessels W contrast IV"
* http://loinc.org#88321-5 "CT Guidance for stereotactic localization of Unspecified body region"
* http://loinc.org#88322-3 "CT Chest W contrast IV and CT angiogram Pulmonary arteries for pulmonary embolus W contrast IV"
* http://loinc.org#88323-1 "CT Guidance for biopsy of Kidney - right"
* http://loinc.org#88324-9 "CT Guidance for biopsy of Lung - left"
* http://loinc.org#88325-6 "CT Guidance for biopsy of Kidney - left"
* http://loinc.org#88326-4 "CT Head WO contrast and CT Brain for perfusion W contrast IV and CT angiogram Head vessels W contrast IV"
* http://loinc.org#88327-2 "CT Head W contrast IV and CT angiogram Head and neck vessels W contrast IV"
* http://loinc.org#88526-9 "CT Guidance for biopsy of Lung - right"
* http://loinc.org#89283-6 "CT Neck+Chest+Abdomen+Pelvis W contrast IV"
* http://loinc.org#89602-7 "CT Guidance for aspiration of cyst of Kidney - left"
* http://loinc.org#89603-5 "CT Guidance for aspiration of cyst of Kidney - right"
* http://loinc.org#89604-3 "CT Guidance for aspiration of cyst of Kidney - bilateral"
* http://loinc.org#89605-0 "CT Guidance for ablation of tissue of Kidney - right"
* http://loinc.org#89606-8 "CT Guidance for ablation of tissue of Kidney - left"
* http://loinc.org#89607-6 "CT Guidance for fluid aspiration of Lung - right"
* http://loinc.org#89608-4 "CT Guidance for fluid aspiration of Lung - left"
* http://loinc.org#89609-2 "CT Guidance for fluid aspiration of Pericardial space"
* http://loinc.org#89610-0 "CT Guidance for placement of catheter in Peritoneal space"
* http://loinc.org#89611-8 "CT Guidance for fluid aspiration of Pleural space - right"
* http://loinc.org#89612-6 "CT Guidance for fluid aspiration of Pleural space - left"
* http://loinc.org#89613-4 "CT Guidance for drainage of Abdomen-- WO contrast"
* http://loinc.org#89614-2 "CT Guidance for biopsy of Kidney-- WO contrast"
* http://loinc.org#89615-9 "CT Guidance for drainage of Abdomen-- W contrast IV"
* http://loinc.org#89616-7 "CT Guidance for aspiration of cyst of Pancreas-- WO contrast"
* http://loinc.org#89617-5 "CT Guidance for aspiration of cyst of Kidney-- W contrast IV"
* http://loinc.org#89618-3 "CT Guidance for aspiration of cyst of Kidney-- WO contrast"
* http://loinc.org#89619-1 "CT Guidance for biopsy of Pancreas-- W contrast IV"
* http://loinc.org#89620-9 "CT Guidance for biopsy of Abdomen-- W contrast IV"
* http://loinc.org#89621-7 "CT Guidance for biopsy of Kidney-- W contrast IV"
* http://loinc.org#89622-5 "CT Guidance for fluid aspiration of Peritoneal space"
* http://loinc.org#89623-3 "CT Guidance for drainage of Peritoneal space"
* http://loinc.org#89624-1 "CT Guidance for drainage of abscess of Peritoneal space"
* http://loinc.org#89625-8 "CT Guidance for aspiration of cyst of Kidney"
* http://loinc.org#89626-6 "CTA Abdominal, Pelvis and Lower extremity vessels W contrast IV"
* http://loinc.org#89627-4 "CT Guidance for aspiration of cyst of Ileum - right"
* http://loinc.org#89628-2 "CT Guidance for aspiration of cyst of Ileum - left"
* http://loinc.org#89629-0 "CT Guidance for aspiration of cyst of Lung - left"
* http://loinc.org#89630-8 "CT Guidance for aspiration of cyst of Lung - right"
* http://loinc.org#89695-1 "CT Guidance for drainage of Pelvis-- WO contrast"
* http://loinc.org#89696-9 "CT Guidance for drainage of Pelvis-- W contrast IV"
* http://loinc.org#89697-7 "CT Guidance for drainage of pseudocyst of Pancreas"
* http://loinc.org#89698-5 "CT Guidance for injection of Ankle - right"
* http://loinc.org#89699-3 "CT Guidance for injection of Ankle - left"
* http://loinc.org#89700-9 "CT Guidance for injection of Hip - right"
* http://loinc.org#89701-7 "CT Guidance for injection of Hip - left"
* http://loinc.org#89702-5 "CT Guidance for injection of Shoulder - bilateral"
* http://loinc.org#89703-3 "CT Guidance for injection of Shoulder - left"
* http://loinc.org#89704-1 "CT Guidance for injection of Shoulder - right"
* http://loinc.org#89705-8 "CT Guidance for injection of Wrist - left"
* http://loinc.org#89706-6 "CT Guidance for injection of Knee - bilateral"
* http://loinc.org#89707-4 "CT Guidance for injection of Knee - right"
* http://loinc.org#89708-2 "CT Guidance for injection of Knee - left"
* http://loinc.org#89709-0 "CT Guidance for greater than 2 levels for injection of Spine facet joint"
* http://loinc.org#89710-8 "CT Guidance for 2 levels injection of Spine facet joint"
* http://loinc.org#89711-6 "CT Guidance for 1 level injection of Spine facet joint"
* http://loinc.org#89713-2 "CT Upper extremity joint - right Arthrogram"
* http://loinc.org#89714-0 "CT Upper extremity joint - left Arthrogram"
* http://loinc.org#89715-7 "CT Lower extremity joint - right Arthrogram"
* http://loinc.org#89716-5 "CT Lower extremity joint - left Arthrogram"
* http://loinc.org#89717-3 "CT Guidance for stereotactic localization of Unspecified body region-- WO and W contrast IV"
* http://loinc.org#89718-1 "CT Guidance for stereotactic localization of Unspecified body region-- W contrast IV"
* http://loinc.org#89719-9 "CT Guidance for drainage of abscess of Lung - right"
* http://loinc.org#89720-7 "CT Guidance for drainage of abscess of Lung - left"
* http://loinc.org#89721-5 "CT Guidance for drainage of abscess of Retroperitoneum"
* http://loinc.org#89722-3 "CTA Upper extremity veins - left W contrast IV"
* http://loinc.org#89723-1 "CTA Upper extremity veins - right W contrast IV"
* http://loinc.org#89827-0 "CT Spine Lumbar and Sacrum WO and W contrast IV"
* http://loinc.org#89828-8 "CT Guidance for superficial biopsy of Muscle"
* http://loinc.org#89829-6 "CT Guidance for biopsy of Retroperitoneum-- WO contrast"
* http://loinc.org#89830-4 "CT Guidance for biopsy of Retroperitoneum-- W contrast IV"
* http://loinc.org#89831-2 "CT Guidance for drainage of Subphrenic space"
* http://loinc.org#89832-0 "CT Guidance for deep biopsy of Tissue"
* http://loinc.org#89833-8 "CT Unspecified body region by reconstruction"
* http://loinc.org#89834-6 "CT Clavicle - bilateral WO contrast"
* http://loinc.org#89835-3 "CT Brachial plexus W contrast IV"
* http://loinc.org#89836-1 "CT Brachial plexus WO contrast"
* http://loinc.org#89837-9 "CT Temporal bone - left WO and W contrast IV"
* http://loinc.org#89838-7 "CT Temporal bone - right WO and W contrast IV"
* http://loinc.org#89839-5 "CT Guidance for biopsy of Sternum"
* http://loinc.org#89840-3 "CT Lumbosacral plexus WO contrast"
* http://loinc.org#89841-1 "CTA Upper extremity vessels - bilateral WO and W contrast IV"
* http://loinc.org#89844-5 "CT Head and Temporal bone WO and W contrast IV"
* http://loinc.org#89845-2 "CT Head and Orbit - bilateral WO and W contrast IV"
* http://loinc.org#89846-0 "CT Midfoot - left and Forefoot - left WO and W contrast IV"
* http://loinc.org#89847-8 "CT Midfoot - right and Forefoot - right"
* http://loinc.org#89848-6 "CT Midfoot - right WO and W contrast IV"
* http://loinc.org#89849-4 "CT Finger - right WO contrast"
* http://loinc.org#89850-2 "CT Finger - left WO contrast"
* http://loinc.org#89851-0 "CTA Unspecified body region limited"
* http://loinc.org#89852-8 "CT Unspecified body region limited W contrast IV"
* http://loinc.org#89853-6 "CT Unspecified body region limited WO contrast"
* http://loinc.org#89854-4 "CT Guidance for drainage of abscess of Perirenal space - left"
* http://loinc.org#89855-1 "CT Guidance for drainage of abscess of Perirenal space - right"
* http://loinc.org#89856-9 "CT Guidance for stereotactic localization of Unspecified body region-- WO contrast"
* http://loinc.org#89857-7 "CT Guidance for biopsy of Pleura - right"
* http://loinc.org#89858-5 "CT Guidance for biopsy of Pleura - left"
* http://loinc.org#89859-3 "CT Guidance for transrectal drainage of abscess of Pelvis"
* http://loinc.org#89860-1 "CT Chest W inspiration and expiration"
* http://loinc.org#89925-2 "CT Pelvis and Lower extremity - bilateral WO and W contrast IV"
* http://loinc.org#89927-8 "CT Heart and aortic root WO contrast for calcium scoring + CTA W contrast IV"
* http://loinc.org#89928-6 "CT Guidance for fluid aspiration of Lumbar spine Intervertebral disc"
* http://loinc.org#89929-4 "CT Guidance for fluid aspiration of Intervertebral disc"
* http://loinc.org#89930-2 "CT Guidance for radiofrequency ablation of Bone"
* http://loinc.org#89931-0 "CT Guidance for drainage of Perirectal region"
* http://loinc.org#89932-8 "CT Guidance for deep placement of needle of Unspecified body region"
* http://loinc.org#89952-6 "CT Guidance for fluid aspiration of Sacroiliac joint - right"
* http://loinc.org#89953-4 "CT Guidance for fluid aspiration of Shoulder - right"
* http://loinc.org#89954-2 "CT Guidance for fluid aspiration of Shoulder - left"
* http://loinc.org#89955-9 "CT Guidance for fluid aspiration of Hip - bilateral"
* http://loinc.org#89956-7 "CT Guidance for fluid aspiration of Hip - left"
* http://loinc.org#89957-5 "CT Guidance for fluid aspiration of Hip - right"
* http://loinc.org#89958-3 "CT Guidance for cryoablation of Pelvis"
* http://loinc.org#89959-1 "CT Guidance for biopsy of Soft tissue"
* http://loinc.org#89960-9 "CT Guidance for drainage of abscess of Kidney - right"
* http://loinc.org#89961-7 "CT Guidance for drainage of abscess of Kidney - left"
* http://loinc.org#89962-5 "CT Guidance for radiofrequency ablation of Lung"
* http://loinc.org#90307-0 "CT Guidance for injection of Foot joint - right"
* http://loinc.org#90308-8 "CT Guidance for needle localization of Thoracic spine"
* http://loinc.org#90309-6 "CT Guidance for drainage of Lung - right"
* http://loinc.org#90310-4 "CT Guidance for drainage of Retroperitoneum-- WO contrast"
* http://loinc.org#90311-2 "CT Guidance for percutaneous replacement of drainage tube of Unspecified body region"
* http://loinc.org#90313-8 "CT Guidance for drainage of Pleural space - left"
* http://loinc.org#90314-6 "CT Guidance for drainage of Retroperitoneum-- W contrast IV"
* http://loinc.org#90315-3 "CT Guidance for deep biopsy of Soft tissue"
* http://loinc.org#90316-1 "CT Guidance for superficial biopsy of Soft tissue"
* http://loinc.org#90317-9 "CT Guidance for drainage of Lower extremity - left"
* http://loinc.org#90318-7 "CT Guidance for drainage of Lower extremity - right"
* http://loinc.org#90319-5 "CT Guidance for drainage of Lung - left"
* http://loinc.org#90334-4 "CT Guidance for injection of Spine Thoracic Facet Joint"
* http://loinc.org#90335-1 "CT Guidance for injection of Spine Lumbar Facet Joint"
* http://loinc.org#90336-9 "CT Guidance for injection of Muscle"
* http://loinc.org#90352-6 "CT Head and CT Brain for perfusion and CT angiogram Head vessels WO and W contrast IV"
* http://loinc.org#90372-4 "CT Guidance for injection of Tendon"
* http://loinc.org#90373-2 "CT Guidance for injection of Tendon or ligament"
