ValueSet: MyCoreRadiologyProcedureUltrasoundMyCore
Id: radiology-procedure-us-my-core
Title: "MY Core Radiology Procedure - Ultrasound"
Description: "NATIONAL SELECTION. The ultrasound subset of the LOINC/RSNA Radiology Playbook. 487 codes. A modality-scoped pick list; the full catalogue is radiology-procedure-my-core."
* ^url = "https://standards.moh.gov.my/fhir/my-core/ValueSet/radiology-procedure-us-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^publisher = "Data Team, Digital Health Division, Ministry of Health Malaysia"
* ^copyright = "This value set enumerates LOINC codes. LOINC is copyright Regenstrief Institute, Inc. and the LOINC Committee, and is available at no cost under the LOINC licence. RPID identifiers are from the RSNA Radiology Playbook."
* ^compose.inactive = false
* http://loinc.org#24531-6 "US Retroperitoneum"
* http://loinc.org#24532-4 "US Abdomen RUQ"
* http://loinc.org#24534-0 "US.doppler Abdominal vessels"
* http://loinc.org#24537-3 "US Guidance for aspiration of amniotic fluid of Uterus"
* http://loinc.org#24542-3 "US Anus"
* http://loinc.org#24547-2 "US Thoracic and abdominal aorta"
* http://loinc.org#24548-0 "US Appendix"
* http://loinc.org#24558-9 "US Abdomen"
* http://loinc.org#24559-7 "US Guidance for drainage of Abdomen"
* http://loinc.org#24596-9 "US Breast specimen"
* http://loinc.org#24599-3 "US Breast limited"
* http://loinc.org#24600-9 "US Guidance for needle localization of Breast"
* http://loinc.org#24601-7 "US Breast"
* http://loinc.org#24616-5 "US Carotid arteries"
* http://loinc.org#24630-6 "US Chest"
* http://loinc.org#24662-9 "US Guidance for fluid aspiration of Pleural space"
* http://loinc.org#24670-2 "US Guidance for biopsy of cyst of Unspecified body region"
* http://loinc.org#24672-8 "US Diaphragm for motion"
* http://loinc.org#24677-7 "US Pelvis transvaginal"
* http://loinc.org#24692-6 "US Guidance for drainage of Extremity"
* http://loinc.org#24693-4 "US Extremity"
* http://loinc.org#24711-4 "US Gallbladder"
* http://loinc.org#24719-7 "US Groin"
* http://loinc.org#24731-2 "US Head"
* http://loinc.org#24732-0 "US Head during surgery"
* http://loinc.org#24733-8 "US.doppler Head vessels"
* http://loinc.org#24760-1 "US Hip"
* http://loinc.org#24772-6 "US Guidance for biopsy of Kidney"
* http://loinc.org#24816-1 "US Guidance for biopsy of Liver"
* http://loinc.org#24818-7 "US Diaphragm and Liver"
* http://loinc.org#24842-7 "US Neck"
* http://loinc.org#24859-1 "US Pancreas"
* http://loinc.org#24868-2 "US Guidance for drainage of Pelvis"
* http://loinc.org#24869-0 "US Pelvis"
* http://loinc.org#24870-8 "US.doppler Pelvis vessels"
* http://loinc.org#24881-5 "US Popliteal space"
* http://loinc.org#24883-1 "US Guidance for percutaneous biopsy of Prostate"
* http://loinc.org#24884-9 "US Prostate transrectal"
* http://loinc.org#24889-8 "US Pylorus for pyloric stenosis"
* http://loinc.org#24892-2 "US Rectum"
* http://loinc.org#24896-3 "US Guidance for drainage of Kidney"
* http://loinc.org#24907-8 "US Shoulder"
* http://loinc.org#24926-8 "US Spine"
* http://loinc.org#24990-4 "US Spleen"
* http://loinc.org#25002-7 "US Scrotum and testicle"
* http://loinc.org#25009-2 "US Guidance for biopsy of Thyroid gland"
* http://loinc.org#25010-0 "US Thyroid gland"
* http://loinc.org#25019-1 "US Urinary bladder"
* http://loinc.org#25036-5 "US Wrist"
* http://loinc.org#25059-7 "US Guidance for biopsy of Unspecified body region"
* http://loinc.org#25060-5 "US Unspecified body region No charge"
* http://loinc.org#25061-3 "US Unspecified body region"
* http://loinc.org#26214-7 "US Breast - bilateral"
* http://loinc.org#26215-4 "US Breast - left"
* http://loinc.org#26216-2 "US Breast - right"
* http://loinc.org#26217-0 "US Carotid arteries - bilateral"
* http://loinc.org#26218-8 "US Carotid arteries - left"
* http://loinc.org#26219-6 "US Carotid arteries -right"
* http://loinc.org#26223-8 "US Extremity - bilateral"
* http://loinc.org#26225-3 "US Extremity - left"
* http://loinc.org#26230-3 "US Extremity - right"
* http://loinc.org#26250-1 "US Hip - bilateral"
* http://loinc.org#26251-9 "US Hip - left"
* http://loinc.org#26252-7 "US Hip - right"
* http://loinc.org#26262-6 "US Popliteal space - bilateral"
* http://loinc.org#26263-4 "US Popliteal space - left"
* http://loinc.org#26264-2 "US Popliteal space - right"
* http://loinc.org#26265-9 "US Shoulder - bilateral"
* http://loinc.org#26267-5 "US Shoulder - left"
* http://loinc.org#26269-1 "US Shoulder - right"
* http://loinc.org#26271-7 "US Scrotum and Testicle - bilateral"
* http://loinc.org#26272-5 "US Scrotum and Testicle - left"
* http://loinc.org#26273-3 "US Scrotum and Testicle - right"
* http://loinc.org#26278-2 "US Wrist - bilateral"
* http://loinc.org#26280-8 "US Wrist - left"
* http://loinc.org#26282-4 "US Wrist - right"
* http://loinc.org#26286-5 "US Breast - bilateral limited"
* http://loinc.org#26288-1 "US Breast - left limited"
* http://loinc.org#26290-7 "US Breast - right limited"
* http://loinc.org#26313-7 "US Guidance for needle localization of Breast - bilateral"
* http://loinc.org#26314-5 "US Guidance for needle localization of Breast - left"
* http://loinc.org#26318-6 "US Guidance for needle localization of Breast - right"
* http://loinc.org#26325-1 "US Guidance for drainage of Extremity - bilateral"
* http://loinc.org#26326-9 "US Guidance for drainage of Extremity - left"
* http://loinc.org#26327-7 "US Guidance for drainage of Extremity - right"
* http://loinc.org#26328-5 "US Guidance for drainage of Kidney - bilateral"
* http://loinc.org#26329-3 "US Guidance for drainage of Kidney - left"
* http://loinc.org#26330-1 "US Guidance for drainage of Kidney - right"
* http://loinc.org#26340-0 "US Guidance for biopsy of Kidney - bilateral"
* http://loinc.org#26341-8 "US Guidance for biopsy of Kidney - left"
* http://loinc.org#26342-6 "US Guidance for biopsy of Kidney - right"
* http://loinc.org#28614-6 "US Liver"
* http://loinc.org#30643-1 "US Guidance for placement of CV catheter in Vein"
* http://loinc.org#30644-9 "US Guidance for placement of CV catheter in Vein-- Tunneled"
* http://loinc.org#30651-4 "US Guidance for percutaneous biopsy.core needle of Breast"
* http://loinc.org#30652-2 "US Guidance for fine needle biopsy of Breast"
* http://loinc.org#30653-0 "US Guidance for aspiration of cyst of Breast"
* http://loinc.org#30698-5 "US Guidance for aspiration of cyst of Unspecified body region"
* http://loinc.org#30699-3 "US Guidance for drainage of Unspecified body region"
* http://loinc.org#30701-7 "US Unspecified body region during surgery"
* http://loinc.org#30702-5 "US Guidance for injection of Thyroid gland"
* http://loinc.org#30703-3 "US Guidance for fluid aspiration of Pericardial space"
* http://loinc.org#30704-1 "US Abdomen limited"
* http://loinc.org#30705-8 "US Uterus and Fallopian tubes"
* http://loinc.org#30706-6 "US Liver during surgery"
* http://loinc.org#30709-0 "US Lower extremity"
* http://loinc.org#30710-8 "US Upper extremity"
* http://loinc.org#30711-6 "US Hip developmental joint assessment"
* http://loinc.org#30712-4 "US Hip WO developmental joint assessment"
* http://loinc.org#30853-6 "US Breast duct W contrast intra duct"
* http://loinc.org#30878-3 "US Guidance for fluid aspiration of Unspecified body region"
* http://loinc.org#30880-9 "US.doppler Head vessels and Neck vessels"
* http://loinc.org#30881-7 "US.doppler Lower extremity vein"
* http://loinc.org#30882-5 "US.doppler Upper extremity vein"
* http://loinc.org#37608-7 "US Guidance for localization of foreign body of Eye"
* http://loinc.org#37912-3 "US Guidance for biopsy of Breast - bilateral"
* http://loinc.org#37913-1 "US Guidance for biopsy of Abdomen"
* http://loinc.org#37914-9 "US Guidance for biopsy of Breast"
* http://loinc.org#37915-6 "US Guidance for biopsy of Chest"
* http://loinc.org#37917-2 "US Guidance for percutaneous biopsy of Muscle"
* http://loinc.org#37918-0 "US Guidance for biopsy of Neck"
* http://loinc.org#37919-8 "US Guidance for biopsy of Pancreas"
* http://loinc.org#37920-6 "US Guidance for biopsy of Salivary gland"
* http://loinc.org#37921-4 "US Guidance for needle localization of Chest"
* http://loinc.org#38011-3 "US Thoracic and abdominal aorta limited"
* http://loinc.org#38012-1 "US Guidance for aspiration of cyst of Breast - bilateral"
* http://loinc.org#38013-9 "US Lower extremity - bilateral"
* http://loinc.org#38014-7 "US Upper extremity artery - bilateral"
* http://loinc.org#38015-4 "US Carotid arteries limited"
* http://loinc.org#38017-0 "US Guidance for FNA of Prostate"
* http://loinc.org#38018-8 "US Guidance for fine needle aspiration of Unspecified body region"
* http://loinc.org#38019-6 "US Guidance for fine needle aspiration of Thyroid gland"
* http://loinc.org#38020-4 "US Gallbladder limited"
* http://loinc.org#38021-2 "US Biliary ducts and Gallbladder"
* http://loinc.org#38022-0 "US Gallbladder W cholecystokinin"
* http://loinc.org#38023-8 "US Guidance for percutaneous biopsy.core needle of Breast - left"
* http://loinc.org#38024-6 "US Guidance for core needle biopsy of Unspecified body region"
* http://loinc.org#38025-3 "US Guidance for percutaneous biopsy.core needle of Breast - right"
* http://loinc.org#38026-1 "US Guidance for fine needle aspiration of Breast - left"
* http://loinc.org#38030-3 "US Guidance for biopsy of Spleen"
* http://loinc.org#38032-9 "US Guidance for needle localization of Unspecified body region"
* http://loinc.org#38033-7 "US Guidance for fine needle aspiration of Breast - right"
* http://loinc.org#38034-5 "US Head limited"
* http://loinc.org#38035-2 "US Kidney limited"
* http://loinc.org#38036-0 "US Kidney"
* http://loinc.org#38037-8 "US Femur - left"
* http://loinc.org#38038-6 "US Kidney - left"
* http://loinc.org#38039-4 "US Lower extremity - left limited"
* http://loinc.org#38040-2 "US Lower extremity - left"
* http://loinc.org#38041-0 "US Upper extremity - left"
* http://loinc.org#38042-8 "US.doppler Lower extremity artery limited"
* http://loinc.org#38043-6 "US Mastoid"
* http://loinc.org#38044-4 "US Mediastinum"
* http://loinc.org#38045-1 "US Parathyroid gland"
* http://loinc.org#38046-9 "US Pelvis limited"
* http://loinc.org#38047-7 "US Retroperitoneum limited"
* http://loinc.org#38048-5 "US Femur - right"
* http://loinc.org#38049-3 "US Kidney - right"
* http://loinc.org#38050-1 "US Lower extremity - right limited"
* http://loinc.org#38051-9 "US Lower extremity - right"
* http://loinc.org#38052-7 "US Upper extremity - right"
* http://loinc.org#38053-5 "US Sacrum"
* http://loinc.org#38054-3 "US Visceral artery"
* http://loinc.org#38126-9 "US Guidance for aspiration of cyst of Kidney"
* http://loinc.org#38127-7 "US Guidance for aspiration of CSF of Spine"
* http://loinc.org#38128-5 "US Femoral vessels - bilateral"
* http://loinc.org#38129-3 "US Iliac vessels - bilateral"
* http://loinc.org#38130-1 "US Lower extremity artery - bilateral"
* http://loinc.org#38131-9 "US Subclavian vessels - bilateral"
* http://loinc.org#38132-7 "US Guidance for biopsy of Scrotum and testicle"
* http://loinc.org#38133-5 "US Guidance for aspiration of cyst of Pancreas"
* http://loinc.org#38134-3 "US Femoral vessels"
* http://loinc.org#38135-0 "US Guidance for deep aspiration.fine needle of Tissue"
* http://loinc.org#38136-8 "US Guidance for superficial aspiration.fine needle of Tissue"
* http://loinc.org#38137-6 "US Iliac vessels - left"
* http://loinc.org#38138-4 "US Parotid gland"
* http://loinc.org#38139-2 "US Penis vessels"
* http://loinc.org#38140-0 "US Penis"
* http://loinc.org#38141-8 "US Iliac vessels - right"
* http://loinc.org#38142-6 "US Guidance for drainage of Chest"
* http://loinc.org#38143-4 "US.doppler Upper extremity artery limited"
* http://loinc.org#38765-4 "US Guidance for biopsy of transplanted liver"
* http://loinc.org#38766-2 "US Guidance for biopsy of transplanted kidney"
* http://loinc.org#39030-2 "US Vein - bilateral"
* http://loinc.org#39031-0 "US.doppler Extremity artery - bilateral"
* http://loinc.org#39032-8 "US for transplanted kidney"
* http://loinc.org#39036-9 "US Vein"
* http://loinc.org#39039-3 "US.doppler Brachiocephalic artery"
* http://loinc.org#39040-1 "US AV fistula"
* http://loinc.org#39042-7 "US.doppler Extremity artery"
* http://loinc.org#39044-3 "US.doppler Head vessels limited"
* http://loinc.org#39045-0 "US Vein limited"
* http://loinc.org#39139-1 "US Guidance for vascular access of Unspecified body region"
* http://loinc.org#39415-5 "US Gastrointestinal tract"
* http://loinc.org#39416-3 "US Genitourinary tract"
* http://loinc.org#39418-9 "US.doppler Extremity vein - bilateral"
* http://loinc.org#39419-7 "US.doppler Renal vessels - bilateral"
* http://loinc.org#39420-5 "US.doppler Lower extremity vein - bilateral"
* http://loinc.org#39421-3 "US.doppler Lower extremity artery - bilateral"
* http://loinc.org#39422-1 "US.doppler Lower extremity vessels - bilateral"
* http://loinc.org#39423-9 "US.doppler Upper extremity artery - bilateral"
* http://loinc.org#39424-7 "US.doppler Extremity vessels limited"
* http://loinc.org#39425-4 "US.doppler Iliac artery"
* http://loinc.org#39426-2 "US.doppler Renal vessels"
* http://loinc.org#39427-0 "US.doppler Carotid arteries - left"
* http://loinc.org#39428-8 "US.doppler Extremity artery - left"
* http://loinc.org#39429-6 "US.doppler Extremity vein - left"
* http://loinc.org#39430-4 "US.doppler Lower extremity vessels - left limited"
* http://loinc.org#39431-2 "US.doppler Lower extremity vessels - left"
* http://loinc.org#39432-0 "US.doppler Lower extremity vein - left"
* http://loinc.org#39433-8 "US.doppler Upper extremity vessels - left"
* http://loinc.org#39434-6 "US.doppler Lower extremity artery"
* http://loinc.org#39435-3 "US.doppler Renal artery"
* http://loinc.org#39436-1 "US.doppler Renal vessels limited"
* http://loinc.org#39437-9 "US.doppler Carotid arteries -right"
* http://loinc.org#39439-5 "US.doppler Extremity artery - right"
* http://loinc.org#39440-3 "US.doppler Extremity vein - right"
* http://loinc.org#39441-1 "US.doppler Lower extremity vessels - right limited"
* http://loinc.org#39442-9 "US.doppler Lower extremity vessels - right"
* http://loinc.org#39443-7 "US.doppler Lower extremity vein - right"
* http://loinc.org#39444-5 "US.doppler Upper extremity vessels - right"
* http://loinc.org#39445-2 "US.doppler Vessels"
* http://loinc.org#39446-0 "US.doppler Testicular vessels"
* http://loinc.org#39447-8 "US.doppler Upper extremity artery"
* http://loinc.org#39448-6 "US.doppler Upper extremity vessels"
* http://loinc.org#39449-4 "US.doppler Extremity vein"
* http://loinc.org#39450-2 "US Gastrointestinal tract W contrast PO"
* http://loinc.org#39451-0 "US Guidance for drainage of abscess of Unspecified body region"
* http://loinc.org#39452-8 "US Guidance for fluid aspiration of Ovary"
* http://loinc.org#39453-6 "US Tendon"
* http://loinc.org#39454-4 "US for transplanted liver"
* http://loinc.org#39494-0 "US Abdominal wall"
* http://loinc.org#39495-7 "US.doppler Extremity vessels - bilateral"
* http://loinc.org#39496-5 "US.doppler Upper extremity vein - bilateral"
* http://loinc.org#39497-3 "US.doppler Iliac vessels"
* http://loinc.org#39498-1 "US.doppler Femoral vessels - left"
* http://loinc.org#39499-9 "US.doppler Lower extremity artery - left"
* http://loinc.org#39500-4 "US.doppler Upper extremity artery - left"
* http://loinc.org#39501-2 "US.doppler Upper extremity vein - left"
* http://loinc.org#39502-0 "US.doppler Ovarian vessels"
* http://loinc.org#39503-8 "US.doppler Extremity vessels - right"
* http://loinc.org#39504-6 "US.doppler Femoral vessels - right"
* http://loinc.org#39505-3 "US.doppler Lower extremity artery - right"
* http://loinc.org#39506-1 "US.doppler Upper extremity artery - right"
* http://loinc.org#39507-9 "US.doppler Upper extremity vein - right"
* http://loinc.org#39508-7 "US.doppler Umbilical vessels Fetal"
* http://loinc.org#39509-5 "US for transplanted pancreas"
* http://loinc.org#39522-8 "US guidance for percutaneous biopsy of Lymph node"
* http://loinc.org#39523-6 "US.doppler Artery"
* http://loinc.org#39524-4 "US.doppler Vein limited"
* http://loinc.org#39525-1 "US.doppler Vein"
* http://loinc.org#39526-9 "US Extremity limited"
* http://loinc.org#39527-7 "US Unspecified body region for foreign body"
* http://loinc.org#41798-0 "US Guidance for drainage of Prostate"
* http://loinc.org#41809-5 "US Guidance for drainage of Retroperitoneum"
* http://loinc.org#41812-9 "US Lower extremity artery limited"
* http://loinc.org#41813-7 "US Upper extremity artery limited"
* http://loinc.org#41814-5 "US Upper extremity artery - right"
* http://loinc.org#41815-2 "US Lower extremity artery - right"
* http://loinc.org#41816-0 "US Extremity veins - right"
* http://loinc.org#41833-5 "US Upper extremity artery - left"
* http://loinc.org#41834-3 "US Lower extremity artery - left"
* http://loinc.org#41835-0 "US Extremity veins - left"
* http://loinc.org#42132-1 "US Breast screening"
* http://loinc.org#42133-9 "US Guidance for drainage of abscess of Liver"
* http://loinc.org#42134-7 "US Guidance for fluid aspiration of Thyroid gland"
* http://loinc.org#42135-4 "US Guidance for superficial biopsy of Bone"
* http://loinc.org#42137-0 "US Guidance for biopsy of Mediastinum"
* http://loinc.org#42140-4 "US Guidance for placement of tube in Chest"
* http://loinc.org#42141-2 "US Guidance for removal of CV catheter of Vein-- Tunneled"
* http://loinc.org#42143-8 "US Uterus and Fallopian tubes W saline IU"
* http://loinc.org#42144-6 "US Extremity vein - right"
* http://loinc.org#42145-3 "US Extremity vein - left"
* http://loinc.org#42146-1 "US.doppler Carotid arteries"
* http://loinc.org#42147-9 "US.doppler Iliac graft"
* http://loinc.org#42148-7 "US Heart"
* http://loinc.org#42149-5 "US Carotid arteries - left limited"
* http://loinc.org#42150-3 "US.doppler Iliac graft limited"
* http://loinc.org#42151-1 "US Carotid arteries -right limited"
* http://loinc.org#42152-9 "US.doppler Pelvis vessels limited"
* http://loinc.org#42333-5 "US Guidance for biopsy of Chest Pleura"
* http://loinc.org#42447-3 "US Guidance for aspiration of cyst of Thyroid gland"
* http://loinc.org#42448-1 "US Guidance for excisional biopsy of Breast"
* http://loinc.org#42449-9 "US Guidance for biopsy of Breast - left"
* http://loinc.org#42450-7 "US Guidance for aspiration of cyst of Breast - left"
* http://loinc.org#42455-6 "US Pelvis transabdominal and transvaginal"
* http://loinc.org#42456-4 "US Guidance for placement of needle wire in Breast"
* http://loinc.org#42457-2 "US Guidance for biopsy of Breast - right"
* http://loinc.org#42458-0 "US Guidance for aspiration of cyst of Breast - right"
* http://loinc.org#42461-4 "US.doppler Lower extremity vessel - left for graft"
* http://loinc.org#42462-2 "US.doppler Lower extremity vessel - right for graft"
* http://loinc.org#42463-0 "US Guidance for biopsy of Endomyocardium"
* http://loinc.org#42468-9 "US Surgical specimen"
* http://loinc.org#42475-4 "US.doppler Upper extremity vessel - left for graft"
* http://loinc.org#42476-2 "US.doppler Upper extremity vessel - right for graft"
* http://loinc.org#42477-0 "US.doppler for transplanted kidney vessels"
* http://loinc.org#42478-8 "US Guidance for drainage of cyst of Kidney"
* http://loinc.org#42705-4 "US Guidance for drainage of abscess of Appendix"
* http://loinc.org#42706-2 "US Guidance for injection of Pleural space"
* http://loinc.org#42707-0 "US Heart limited"
* http://loinc.org#43487-8 "US Guidance for placement of radiation therapy fields in Unspecified body region"
* http://loinc.org#43552-9 "US Carotid arteries - unilateral"
* http://loinc.org#43564-4 "US Guidance for superficial biopsy of Muscle"
* http://loinc.org#43565-1 "US Guidance for deep biopsy of Bone"
* http://loinc.org#43566-9 "US Hip and Thigh"
* http://loinc.org#43572-7 "US.doppler Abdominal vessels limited"
* http://loinc.org#43756-6 "US Guidance for fluid aspiration of Breast"
* http://loinc.org#43758-2 "US Guidance for localization of Breast - left"
* http://loinc.org#43759-0 "US Guidance for localization of Breast - bilateral"
* http://loinc.org#43760-8 "US Guidance for localization of Breast - right"
* http://loinc.org#43765-7 "US.doppler Carotid arteries - bilateral"
* http://loinc.org#43771-5 "US.doppler Extremity vessels"
* http://loinc.org#43774-9 "US Kidney - bilateral"
* http://loinc.org#43776-4 "US.doppler Iliac artery limited"
* http://loinc.org#43797-0 "US Guidance for superficial biopsy of Lymph node"
* http://loinc.org#44155-0 "US Guidance for ablation of tissue of Liver"
* http://loinc.org#44156-8 "US Guidance for ablation of tissue of Kidney"
* http://loinc.org#44157-6 "US Guidance for fine needle aspiration of Pancreas"
* http://loinc.org#44158-4 "US Guidance for fine needle aspiration of Liver"
* http://loinc.org#44159-2 "US Guidance for fine needle aspiration of Kidney"
* http://loinc.org#44160-0 "US Guidance for fine needle aspiration of Breast"
* http://loinc.org#44161-8 "US Guidance for biopsy of Lung"
* http://loinc.org#44162-6 "US Guidance for biopsy of Retroperitoneum"
* http://loinc.org#44163-4 "US Brachial plexus"
* http://loinc.org#44164-2 "US Head and Neck"
* http://loinc.org#44166-7 "US Guidance for drainage of abscess of Subphrenic space"
* http://loinc.org#44167-5 "US Guidance for drainage of abscess of Kidney"
* http://loinc.org#44168-3 "US Guidance for drainage of abscess of Pelvis"
* http://loinc.org#44169-1 "US Guidance for drainage of abscess of Peritoneal space"
* http://loinc.org#44172-5 "US Guidance for drainage of Pancreas"
* http://loinc.org#44173-3 "US Extremity artery limited"
* http://loinc.org#44174-1 "US.doppler Lower extremity vessels"
* http://loinc.org#44175-8 "US.doppler Neck vessels"
* http://loinc.org#44235-0 "US.doppler Superior mesenteric vessels"
* http://loinc.org#44236-8 "US.doppler Upper extremity vessel - bilateral for graft"
* http://loinc.org#44237-6 "US.doppler Upper extremity vessel - bilateral for graft limited"
* http://loinc.org#46282-0 "US Guidance for aspiration or injection of cyst of Unspecified body region"
* http://loinc.org#46285-3 "US Guidance for core needle biopsy of Thyroid gland"
* http://loinc.org#46288-7 "US Guidance for biopsy of Prostate"
* http://loinc.org#46301-8 "US.doppler Extremity vein - bilateral limited"
* http://loinc.org#46302-6 "US.doppler Upper extremity artery - bilateral limited"
* http://loinc.org#46303-4 "US.doppler Upper extremity vessels limited"
* http://loinc.org#46362-0 "US.doppler Foot vessels"
* http://loinc.org#46363-8 "US Lower extremity vein"
* http://loinc.org#46364-6 "US Lower extremity vein - bilateral"
* http://loinc.org#46369-5 "US Guidance for biopsy of Ovary"
* http://loinc.org#46370-3 "US Guidance for biopsy of Pelvis"
* http://loinc.org#46374-5 "US Cerebral arteries"
* http://loinc.org#46375-2 "US Artery"
* http://loinc.org#46379-4 "US.doppler Upper extremity vessels - bilateral"
* http://loinc.org#46382-8 "US.doppler Hand vessels"
* http://loinc.org#46385-1 "US.doppler Upper extremity vessel for graft"
* http://loinc.org#46388-5 "US.doppler Thoracic and abdominal aorta"
* http://loinc.org#48434-5 "US Guidance for fluid aspiration of Kidney"
* http://loinc.org#48448-5 "US Upper extremity artery"
* http://loinc.org#48688-6 "US Upper extremity vein - right"
* http://loinc.org#48689-4 "US Upper extremity vein - left"
* http://loinc.org#48690-2 "US Upper extremity vein - bilateral"
* http://loinc.org#48691-0 "US Lower extremity vein - right"
* http://loinc.org#48692-8 "US Lower extremity vein - left"
* http://loinc.org#48693-6 "US Lower extremity artery"
* http://loinc.org#48742-1 "US.doppler Scrotum and testicle"
* http://loinc.org#58743-6 "US Guidance for ablation of tissue of Unspecified body region"
* http://loinc.org#62451-0 "US Extremity - left limited"
* http://loinc.org#62452-8 "US Extremity - right limited"
* http://loinc.org#62494-0 "US Guidance for percutaneous drainage of Unspecified body region"
* http://loinc.org#64993-9 "US Guidance for placement of needle in Unspecified body region"
* http://loinc.org#69276-4 "US Abdominal Aorta"
* http://loinc.org#69277-2 "US Adrenal gland"
* http://loinc.org#69278-0 "US Guidance for fluid aspiration of Breast - bilateral"
* http://loinc.org#69279-8 "US Guidance for core needle biopsy of Lymph node"
* http://loinc.org#69280-6 "US Urinary bladder limited"
* http://loinc.org#69282-2 "US.doppler Unspecified body region limited"
* http://loinc.org#69283-0 "US.doppler Extremity veins - bilateral"
* http://loinc.org#69284-8 "US.doppler Portal vein and Hepatic vein"
* http://loinc.org#69285-5 "US.doppler Umbilical artery Fetal"
* http://loinc.org#69286-3 "US Eye limited"
* http://loinc.org#69287-1 "US Guidance for fluid aspiration of Lymph node"
* http://loinc.org#69292-1 "US Guidance for fluid aspiration of Breast - left"
* http://loinc.org#69293-9 "US Extremity artery - left"
* http://loinc.org#69294-7 "US Renal artery"
* http://loinc.org#69295-4 "US Renal vessels"
* http://loinc.org#69296-2 "US Guidance for fluid aspiration of Breast - right"
* http://loinc.org#69297-0 "US Extremity artery - right"
* http://loinc.org#69298-8 "US Salivary gland"
* http://loinc.org#69299-6 "US Scrotum and testicle limited"
* http://loinc.org#69300-2 "US for transplanted kidney limited"
* http://loinc.org#69385-3 "US Lower extremity veins - bilateral"
* http://loinc.org#69387-9 "US Guidance for biopsy of Epididymis"
* http://loinc.org#69388-7 "US Urinary bladder post void"
* http://loinc.org#69389-5 "US Femoral artery and Popliteal artery"
* http://loinc.org#69390-3 "US Ovary"
* http://loinc.org#69391-1 "US Guidance for cordocentesis"
* http://loinc.org#69392-9 "US Lower extremity veins - left"
* http://loinc.org#69393-7 "US Lumbar spine"
* http://loinc.org#69394-5 "US Mesenteric arteries"
* http://loinc.org#69395-2 "US Upper extremity veins"
* http://loinc.org#69396-0 "US Guidance for biopsy of Spinal cord"
* http://loinc.org#69397-8 "US.doppler Breast vessels"
* http://loinc.org#69398-6 "US.doppler Extremity vessels - left"
* http://loinc.org#69399-4 "US Femoral vein and Popliteal vein"
* http://loinc.org#69400-0 "US Guidance for chorionic villus sampling"
* http://loinc.org#69402-6 "US Kidney - bilateral and Urinary bladder"
* http://loinc.org#70915-4 "US Guidance for aspiration of CSF of Cervical spine"
* http://loinc.org#70916-2 "US Guidance for aspiration of CSF of Lumbar spine"
* http://loinc.org#70917-0 "US Guidance for aspiration of CSF of Thoracic spine"
* http://loinc.org#70926-1 "US Cervical spine"
* http://loinc.org#70927-9 "US Thoracic spine"
* http://loinc.org#72528-3 "US Axilla - right"
* http://loinc.org#72529-1 "US Axilla - left"
* http://loinc.org#72530-9 "US Guidance for injection of Joint"
* http://loinc.org#72532-5 "US Guidance for ambulatory phlebectomy of Extremity vein - right"
* http://loinc.org#72533-3 "US Guidance for ambulatory phlebectomy of Extremity vein - left"
* http://loinc.org#72534-1 "US Guidance for laser ablation of Extremity vein - right"
* http://loinc.org#72535-8 "US Guidance for laser ablation of Extremity vein - left"
* http://loinc.org#72536-6 "US Guidance for vascular sclerotherapy of Extremity veins - bilateral"
* http://loinc.org#72537-4 "US Guidance for vascular sclerotherapy of Extremity vein - bilateral"
* http://loinc.org#72642-2 "US Guidance for vascular sclerotherapy of Extremity veins - right"
* http://loinc.org#72643-0 "US Guidance for vascular sclerotherapy of Extremity veins - left"
* http://loinc.org#72644-8 "US Guidance for vascular sclerotherapy of Extremity vein - right"
* http://loinc.org#72645-5 "US Guidance for vascular sclerotherapy of Extremity vein - left"
* http://loinc.org#72830-3 "US.doppler Extremity arteries - bilateral for physiologic artery study"
* http://loinc.org#72831-1 "US.doppler Extremity arteries - bilateral for physiologic artery study limited"
* http://loinc.org#72832-9 "US.doppler Extremity arteries - bilateral for physiologic artery study at rest and with exercise"
* http://loinc.org#75672-6 "US Guidance for placement of nephrostomy tube in Kidney"
* http://loinc.org#79374-5 "US Abdominal Aorta for screening"
* http://loinc.org#80833-7 "US for multiple gestation pregnancy limited"
* http://loinc.org#80834-5 "US for multiple gestation pregnancy in first trimester"
* http://loinc.org#80835-2 "US transabdominal and transvaginal for multiple gestation pregnancy in first trimester"
* http://loinc.org#80836-0 "US for multiple gestation pregnancy in second or third trimester"
* http://loinc.org#80837-8 "US for multiple gestation pregnancy with fetal abnormality"
* http://loinc.org#80838-6 "US Liver limited"
* http://loinc.org#80839-4 "US Pancreas limited"
* http://loinc.org#80840-2 "US Spleen limited"
* http://loinc.org#80841-0 "US Guidance for placement of needle in Breast"
* http://loinc.org#80842-8 "US Guidance for additional aspiration of cyst of Breast - left"
* http://loinc.org#80843-6 "US Guidance for vacuum biopsy of Breast - left"
* http://loinc.org#80844-4 "US Guidance for fine needle biopsy of Breast - left"
* http://loinc.org#80846-9 "US Guidance for additional aspiration of cyst of Breast - right"
* http://loinc.org#80847-7 "US Guidance for vacuum biopsy of Breast - right"
* http://loinc.org#80848-5 "US Guidance for fine needle biopsy of Breast - right"
* http://loinc.org#80850-1 "US.doppler Carotid arteries limited"
* http://loinc.org#80851-9 "US.doppler Cerebral artery middle Fetal for pregnancy"
* http://loinc.org#80852-7 "US Axilla"
* http://loinc.org#80853-5 "US Guidance for injection of Elbow"
* http://loinc.org#80854-3 "US Extremity musculoskeletal tissue limited"
* http://loinc.org#80855-0 "US Extremity musculoskeletal tissue"
* http://loinc.org#80856-8 "US.doppler Head limited"
* http://loinc.org#80857-6 "US.doppler Head"
* http://loinc.org#80858-4 "US Head and neck soft tissue"
* http://loinc.org#80859-2 "US.doppler Heart"
* http://loinc.org#80860-0 "US Lower extremity veins - unilateral limited"
* http://loinc.org#80861-8 "US Lower extremity soft tissue"
* http://loinc.org#80862-6 "US Pelvis for in vitro fertilization"
* http://loinc.org#80863-4 "US.doppler for transplanted kidney"
* http://loinc.org#80864-2 "US.doppler for pregnancy"
* http://loinc.org#80865-9 "US transvaginal for pregnancy"
* http://loinc.org#80866-7 "US for pregnancy in second or third trimester"
* http://loinc.org#80867-5 "US transabdominal and transvaginal for pregnancy in first trimester"
* http://loinc.org#80868-3 "US for pregnancy with fetal abnormality"
* http://loinc.org#80869-1 "US for pregnancy in first trimester"
* http://loinc.org#80870-9 "US for pregnancy limited"
* http://loinc.org#80871-7 "US Ovary for torsion"
* http://loinc.org#80872-5 "US.doppler Uterus and Fallopian tubes W saline IU"
* http://loinc.org#80873-3 "US.doppler Penis limited"
* http://loinc.org#80874-1 "US.doppler Penis vessels"
* http://loinc.org#80875-8 "US Penis soft tissue"
* http://loinc.org#80876-6 "US Prostate transrectal for volume measurement"
* http://loinc.org#80877-4 "US Scrotum and testicle for torsion"
* http://loinc.org#80878-2 "US.doppler Umbilical artery Fetal for pregnancy"
* http://loinc.org#80879-0 "US Upper extremity veins - unilateral limited"
* http://loinc.org#80880-8 "US Guidance for injection of Carpal tunnel"
* http://loinc.org#80881-6 "US Upper extremity soft tissue"
* http://loinc.org#80882-4 "US Guidance of Unspecified body region-- during surgery"
* http://loinc.org#80895-6 "US Upper extremity veins - bilateral"
* http://loinc.org#80896-4 "US.doppler Aorta and Iliac artery - bilateral"
* http://loinc.org#80897-2 "US.doppler Aorta and Iliac artery - bilateral limited"
* http://loinc.org#80898-0 "US Groin and Pseudoaneurysm"
* http://loinc.org#81158-8 "US Pediatric Head"
* http://loinc.org#81159-6 "US Pediatric Cervical and thoracic and lumbar spine"
* http://loinc.org#81160-4 "US.doppler Pediatric limited Head"
* http://loinc.org#81161-2 "US.doppler Heart for blood flow"
* http://loinc.org#81162-0 "US Guidance for needle localization Breast - left and MG Views Breast specimen"
* http://loinc.org#81163-8 "US Guidance for needle localization Breast - right and MG Views Breast specimen"
* http://loinc.org#81164-6 "US Pediatric limited Hip - bilateral"
* http://loinc.org#81165-3 "US Guidance for peripheral venous access of Vein"
* http://loinc.org#82124-9 "US Guidance for radiation treatment of Unspecified body region"
