ValueSet: MyCoreRadiologyProcedurePortableAndMobileMyCore
Id: radiology-procedure-portable-my-core
Title: "MY Core Radiology Procedure - Portable and mobile"
Description: "NATIONAL SELECTION. The portable and mobile subset of the LOINC/RSNA Radiology Playbook. 101 codes. A modality-scoped pick list; the full catalogue is radiology-procedure-my-core."
* ^url = "https://standards.moh.gov.my/fhir/my-core/ValueSet/radiology-procedure-portable-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^publisher = "Data Team, Digital Health Division, Ministry of Health Malaysia"
* ^copyright = "This value set enumerates LOINC codes. LOINC is copyright Regenstrief Institute, Inc. and the LOINC Committee, and is available at no cost under the LOINC licence. RPID identifiers are from the RSNA Radiology Playbook."
* ^compose.inactive = false
* http://loinc.org#24560-5 "Portable XR Abdomen AP left lateral-decubitus"
* http://loinc.org#24564-7 "Portable XR Abdomen AP upright"
* http://loinc.org#24632-2 "Portable XR Chest Views AP"
* http://loinc.org#24634-8 "Portable XR Chest Views W inspiration and expiration"
* http://loinc.org#24636-3 "Portable XR Chest AP left lateral-decubitus"
* http://loinc.org#24638-9 "Portable XR Chest Left lateral upright"
* http://loinc.org#24641-3 "Portable XR Chest Left oblique"
* http://loinc.org#24644-7 "Portable XR Chest PA and Lateral upright"
* http://loinc.org#24645-4 "Portable XR Chest PA and Right lateral and Right oblique and Left oblique upright"
* http://loinc.org#24649-6 "Portable XR Chest Right lateral-decubitus and Left lateral-decubitus"
* http://loinc.org#24652-0 "Portable XR Chest AP right lateral-decubitus"
* http://loinc.org#24654-6 "Portable XR Chest AP and AP right lateral-decubitus"
* http://loinc.org#24792-4 "Portable XR Abdomen AP and AP left lateral-decubitus"
* http://loinc.org#24793-2 "Portable XR Abdomen AP and Lateral"
* http://loinc.org#24795-7 "Portable XR Abdomen Supine and Upright"
* http://loinc.org#30722-3 "Portable XR Skull Single view"
* http://loinc.org#30723-1 "Portable XR Skull Views"
* http://loinc.org#30724-9 "Portable XR Cervical spine Single view"
* http://loinc.org#30726-4 "Portable XR Cervical spine AP and Lateral"
* http://loinc.org#30727-2 "Portable XR Cervical spine AP"
* http://loinc.org#30729-8 "Portable XR Spine Cervical Odontoid and Cervical axis AP"
* http://loinc.org#30730-6 "Portable XR Zygomatic arch - bilateral Views"
* http://loinc.org#30731-4 "Portable XR Zygomatic arch Views"
* http://loinc.org#30733-0 "Portable XR Chest Right oblique and Left oblique"
* http://loinc.org#30735-5 "Portable XR Chest AP lateral-decubitus"
* http://loinc.org#30738-9 "Portable XR Chest Left lateral"
* http://loinc.org#30739-7 "Portable XR Chest Oblique"
* http://loinc.org#30743-9 "Portable XR Chest PA and Lateral and Right oblique and Left oblique"
* http://loinc.org#30746-2 "Portable XR Chest Views"
* http://loinc.org#30747-0 "Portable XR Ribs Views"
* http://loinc.org#30749-6 "Portable XR Shoulder Single view"
* http://loinc.org#30754-6 "Portable XR Thoracic spine AP and Lateral"
* http://loinc.org#30755-3 "Portable XR Thoracic spine AP"
* http://loinc.org#30757-9 "Portable XR Thoracic spine Lateral"
* http://loinc.org#30759-5 "Portable XR Thoracic spine Oblique"
* http://loinc.org#30763-7 "Portable XR Abdomen AP and Lateral crosstable"
* http://loinc.org#30764-5 "Portable XR Acetabulum - bilateral Views"
* http://loinc.org#30765-2 "Portable XR Acetabulum Views"
* http://loinc.org#30772-8 "Portable XR Pelvis Views"
* http://loinc.org#30774-4 "Portable XR Lumbar spine Single view"
* http://loinc.org#30776-9 "Portable XR Lumbar spine 3 Views"
* http://loinc.org#30792-6 "Portable XR Patella Views"
* http://loinc.org#36588-2 "Portable XR Abdomen AP"
* http://loinc.org#36589-0 "Portable XR Chest AP single view"
* http://loinc.org#36674-0 "Portable XR Lumbar spine 2 Views"
* http://loinc.org#36960-3 "Portable XR Chest AP upright"
* http://loinc.org#36991-8 "Portable XR Cervical spine Lateral crosstable"
* http://loinc.org#36992-6 "Portable XR Lumbar spine Lateral crosstable"
* http://loinc.org#37075-9 "Portable XR Hip Views AP"
* http://loinc.org#37076-7 "Portable XR Abdomen Supine and Lateral-decubitus"
* http://loinc.org#37077-5 "Portable XR Hip AP and Lateral crosstable"
* http://loinc.org#37078-3 "Portable XR Lumbar spine AP and Lateral"
* http://loinc.org#37079-1 "Portable XR Cervical spine AP and Lateral and Odontoid"
* http://loinc.org#37151-8 "Portable RF Unspecified body region Views"
* http://loinc.org#37168-2 "Portable XR Hip Views"
* http://loinc.org#37169-0 "Portable XR Hip - left Views"
* http://loinc.org#37170-8 "Portable XR Humerus Views"
* http://loinc.org#37171-6 "Portable XR Cervical spine Views"
* http://loinc.org#37172-4 "Portable XR Lumbar spine Views"
* http://loinc.org#38796-9 "Portable XR Hip - right Views"
* http://loinc.org#41773-3 "Portable XR Facial bones Views"
* http://loinc.org#41774-1 "Portable XR Neck Lateral"
* http://loinc.org#41775-8 "Portable XR Pelvis Single view"
* http://loinc.org#41776-6 "Portable XR Pelvis and Hip - right AP and Lateral frog"
* http://loinc.org#41777-4 "Portable XR Hip - right AP and Lateral"
* http://loinc.org#41778-2 "Portable XR Femur - right Views"
* http://loinc.org#41779-0 "Portable XR Knee - right Views"
* http://loinc.org#41782-4 "Portable XR Ankle - right Views"
* http://loinc.org#41783-2 "Portable XR Shoulder - right Views"
* http://loinc.org#41784-0 "Portable XR Humerus - right Views"
* http://loinc.org#41786-5 "Portable XR Elbow - right Views"
* http://loinc.org#41787-3 "Portable XR Wrist - right Views"
* http://loinc.org#41788-1 "Portable XR Hand - right Views"
* http://loinc.org#41791-5 "Portable XR Ribs - right Views"
* http://loinc.org#41817-8 "Portable XR Hip - left AP and Lateral"
* http://loinc.org#41818-6 "Portable XR Femur - left Views"
* http://loinc.org#41820-2 "Portable XR Knee - left Views"
* http://loinc.org#41823-6 "Portable XR Ankle - left Views"
* http://loinc.org#41824-4 "Portable XR Shoulder - left Views"
* http://loinc.org#41825-1 "Portable XR Humerus - left Views"
* http://loinc.org#41827-7 "Portable XR Elbow - left Views"
* http://loinc.org#41828-5 "Portable XR Wrist - left Views"
* http://loinc.org#41829-3 "Portable XR Hand - left Views"
* http://loinc.org#41831-9 "Portable XR Ribs - left Views"
* http://loinc.org#43570-1 "Portable XR Hand Views"
* http://loinc.org#43778-0 "Portable XR Chest AP supine"
* http://loinc.org#44176-6 "Portable XR Hip Single view"
* http://loinc.org#44182-4 "Portable XR Hand 2 Views"
* http://loinc.org#44183-2 "Portable XR Radius and Ulna 2 Views"
* http://loinc.org#44184-0 "Portable XR Elbow 2 Views"
* http://loinc.org#44185-7 "Portable XR Femur AP and Lateral"
* http://loinc.org#44186-5 "Portable XR Foot AP and Lateral"
* http://loinc.org#44187-3 "Portable XR Cervical spine AP and Oblique and Odontoid and (Lateral W flexion and W extension)"
* http://loinc.org#44192-3 "Portable XR Pelvis GE 3 Views"
* http://loinc.org#44193-1 "Portable XR Hand GE 3 Views"
* http://loinc.org#44201-2 "Portable XR Pelvis 1 or 2 Views"
* http://loinc.org#44202-0 "Portable XR Knee 1 or 2 Views"
* http://loinc.org#44203-8 "Portable XR Cervical and thoracic and lumbar spine Views"
* http://loinc.org#44239-2 "Portable XR Ribs - unilateral GE 3 Views and Chest PA"
* http://loinc.org#46391-9 "Portable XR Shoulder Views"
* http://loinc.org#70932-9 "Portable XR Thoracic spine Single view"
