ValueSet: MyCoreImagingRegionBodySiteVS
Id: imaging-region-bodysite-my-core
Title: "MY Core Imaging Body Site (retired)"
Description: """RETIRED in 2.1.0. Superseded by radlex-anatomy-my-core: body site now
binds to RadLex, the RSNA radiology anatomy lexicon, rather than to a national list.
Retained so that legacy RIS extracts can be translated through
ConceptMap/imaging-region-my-core-to-radlex.

The body-region concepts from the national imaging region list — the concepts whose conceptClass is region. Procedures,
modalities and administrative categories in that list are deliberately excluded.
Each concept is mapped to RadLex."""
* ^url = "https://standards.moh.gov.my/fhir/my-core/ValueSet/imaging-region-bodysite-my-core"
* ^version = "2.1.1"
* ^status = #active
* ^experimental = false
* ^date = "2026-10-01T03:16:33.657151Z"
* ^compose.inactive = false
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#001 "ABDOMEN"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#004 "CHEST"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#007 "EXTREMITIES"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#049 "PELVIS"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#062 "SKULL & FACIAL BONES"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#079 "SPINES"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#089 "ABDOMEN (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#091 "CHEST (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#093 "EXTREMITIES (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#120 "PELVIS (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#124 "SKULL (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#126 "SPINE (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#132 "ABDOMEN"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#158 "EXTREMITIES"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#176 "HEAD AND NECK"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#194 "TMJ (Temporo-Mandibular Joints)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#196 "PELVIS"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#198 "SPINES"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#206 "THORAX"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#217 "ABDOMEN"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#243 "BREAST"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#250 "EXTREMITIES"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#280 "HEAD & NECK"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#294 "HEPATOBILIARY SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#297 "MRI PELVIS"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#303 "MRI SPINES"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#309 "MRI THORAX"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#312 "URINARY SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#321 "BREAST (MAMMOGRAPHY)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#327 "ANATOMICAL REGION"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#334 "BREAST"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#336 "CNS"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#341 "CIRCULATORY SYSTEM - ARTERIES"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#352 "CIRCULATORY SYSTEM - VEINS"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#363 "DIGESTIVE SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#366 "ENDOCRINE SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#369 "HEPATOBILIARY SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#375 "INTEGUMENT & MUSCULOSKELETAL SYSTEM & SOFT TISSUES"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#382 "MUSCULOSKELETAL SYSTEM (BONES & JOINTS)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#395 "REPRODUCTIVE SYSTEM - FEMALE"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#399 "REPRODUCTIVE SYSTEM - MALE"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#405 "RESPIRATORY SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#408 "URINARY SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#417 "ANATOMICAL REGION (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#421 "CNS (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#425 "CIRCULATORY SYSTEM - ARTERIES (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#436 "CIRCULATORY SYSTEM - VEINS (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#446 "HEPATOBILIARY SYSTEM (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#451 "RESPIRATORY SYSTEM (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#454 "URINARY SYSTEM (Mobile)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#607 "GASTROINTESTINAL SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#612 "HEPATOBILIARY SYSTEM & PANCREAS"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#623 "RESPIRATORY SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#631 "URINARY SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#655 "BREAST"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#713 "URINARY SYSTEM (IVU)"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#814 "SKULL AND FACIAL BONES"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#818 "DIGESTIVE SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#837 "HEPATOBILIARY SYSTEM & PANCREAS"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#842 "MUSCULOSKELETAL SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#847 "REPRODUCTIVE SYSTEM - FEMALE"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#849 "RESPIRATORY SYSTEM"
* https://standards.moh.gov.my/fhir/my-core/CodeSystem/imaging-region-my-core#851 "URINARY SYSTEM"
