#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STREAM_DIR="$ROOT_DIR/input/resources-legacy-migrated"
FSH_DIR="$ROOT_DIR/input/fsh"
EXCLUSION_FILE="$FSH_DIR/migration-exclusions.txt"
TEMP_DIR="$ROOT_DIR/temp/gofsh-promote-$$"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/jsonresource-to-fsh.sh <resource-id-or-json-path> [--exclude]

Examples:
  ./scripts/jsonresource-to-fsh.sh Patient-my-core
  ./scripts/jsonresource-to-fsh.sh input/resources-legacy-migrated/StructureDefinition-Patient-my-core.json --exclude
EOF
}

if [[ $# -lt 1 ]]; then
  usage >&2
  exit 1
fi

RESOURCE_ARG=""
SHOULD_EXCLUDE="false"

for arg in "$@"; do
  case "$arg" in
    --exclude)
      SHOULD_EXCLUDE="true"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [[ -n "$RESOURCE_ARG" ]]; then
        echo "Only one resource id or path may be supplied." >&2
        exit 1
      fi
      RESOURCE_ARG="$arg"
      ;;
  esac
done

if [[ -z "$RESOURCE_ARG" ]]; then
  usage >&2
  exit 1
fi

resolve_resource_path() {
  local resource_arg="$1"
  if [[ -f "$resource_arg" ]]; then
    printf '%s\n' "$resource_arg"
    return 0
  fi

  local direct_match="$STREAM_DIR/$resource_arg.json"
  if [[ -f "$direct_match" ]]; then
    printf '%s\n' "$direct_match"
    return 0
  fi

  local matches=()
  while IFS= read -r match; do
    matches+=("$match")
  done < <(find "$STREAM_DIR" -maxdepth 1 -type f -name "*-$resource_arg.json" | sort)

  if [[ ${#matches[@]} -eq 1 ]]; then
    printf '%s\n' "${matches[0]}"
    return 0
  fi

  if [[ ${#matches[@]} -gt 1 ]]; then
    echo "Multiple migrated resources matched '$resource_arg':" >&2
    printf '  %s\n' "${matches[@]}" >&2
    exit 1
  fi

  echo "No migrated resource matched '$resource_arg'." >&2
  exit 1
}

if [[ -x "$ROOT_DIR/node_modules/.bin/gofsh" ]]; then
  GOFSH_CMD="$ROOT_DIR/node_modules/.bin/gofsh"
else
  GOFSH_CMD="$(command -v gofsh || true)"
fi

if [[ -z "$GOFSH_CMD" ]]; then
  echo "GoFSH is required. Run 'npm ci' in ig/ to install the local devDependency." >&2
  exit 1
fi

if command -v python >/dev/null 2>&1; then
  PYTHON_CMD="python"
elif command -v python3 >/dev/null 2>&1; then
  PYTHON_CMD="python3"
else
  echo "Python is required to inspect the migrated JSON resource." >&2
  exit 1
fi

RESOURCE_PATH="$(resolve_resource_path "$RESOURCE_ARG")"

RESOURCE_ID="$(
  RESOURCE_PATH="$RESOURCE_PATH" "$PYTHON_CMD" - <<'PY'
import json
import os
from pathlib import Path

path = Path(os.environ['RESOURCE_PATH'])
data = json.loads(path.read_text(encoding='utf-8'))
print(data.get('id') or path.stem)
PY
)"

rm -rf "$TEMP_DIR"
mkdir -p "$TEMP_DIR"

"$GOFSH_CMD" "$RESOURCE_PATH" \
  --out "$TEMP_DIR" \
  --style single-file \
  --no-alias

GENERATED_FILES=()
while IFS= read -r generated_file; do
  GENERATED_FILES+=("$generated_file")
done < <(find "$TEMP_DIR" -type f -path '*/input/fsh/*.fsh' | sort)

if [[ ${#GENERATED_FILES[@]} -eq 0 ]]; then
  echo 'GoFSH did not produce an FSH file.' >&2
  exit 1
fi

if [[ ${#GENERATED_FILES[@]} -gt 1 ]]; then
  echo 'GoFSH produced more than one FSH file for a single resource conversion:' >&2
  printf '  %s\n' "${GENERATED_FILES[@]}" >&2
  exit 1
fi

GENERATED_FILE="${GENERATED_FILES[0]}"

DEST_FILE="$FSH_DIR/zz-promoted-$RESOURCE_ID.fsh"
{
  printf '// Promoted from %s\n' "${RESOURCE_PATH#$ROOT_DIR/}"
  printf '// Generated by scripts/jsonresource-to-fsh.sh\n\n'
  cat "$GENERATED_FILE"
  printf '\n'
} > "$DEST_FILE"

if [[ "$SHOULD_EXCLUDE" == "true" ]]; then
  if ! grep -Fxq "$RESOURCE_ID" "$EXCLUSION_FILE"; then
    printf '%s\n' "$RESOURCE_ID" >> "$EXCLUSION_FILE"
  fi
fi

printf 'Wrote %s\n' "${DEST_FILE#$ROOT_DIR/}"
if [[ "$SHOULD_EXCLUDE" == "true" ]]; then
  printf 'Added %s to %s\n' "$RESOURCE_ID" "${EXCLUSION_FILE#$ROOT_DIR/}"
else
  printf 'Next step: add %s to %s once the FSH version is ready to replace migrated JSON.\n' "$RESOURCE_ID" "${EXCLUSION_FILE#$ROOT_DIR/}"
fi
